// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i control-plane/internal/workers.AgentSubscribeService -o agent_subscribe_service_mock.go -n AgentSubscribeServiceMock -p mocks

import (
	"context"
	"control-plane/internal/model"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// AgentSubscribeServiceMock implements mm_workers.AgentSubscribeService
type AgentSubscribeServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcStartUserSubscribe          func(ctx context.Context, input model.SubscriptionActivatedEvent) (err error)
	funcStartUserSubscribeOrigin    string
	inspectFuncStartUserSubscribe   func(ctx context.Context, input model.SubscriptionActivatedEvent)
	afterStartUserSubscribeCounter  uint64
	beforeStartUserSubscribeCounter uint64
	StartUserSubscribeMock          mAgentSubscribeServiceMockStartUserSubscribe

	funcStopUserSubscribe          func(ctx context.Context, input model.SubscriptionCancelEvent) (err error)
	funcStopUserSubscribeOrigin    string
	inspectFuncStopUserSubscribe   func(ctx context.Context, input model.SubscriptionCancelEvent)
	afterStopUserSubscribeCounter  uint64
	beforeStopUserSubscribeCounter uint64
	StopUserSubscribeMock          mAgentSubscribeServiceMockStopUserSubscribe
}

// NewAgentSubscribeServiceMock returns a mock for mm_workers.AgentSubscribeService
func NewAgentSubscribeServiceMock(t minimock.Tester) *AgentSubscribeServiceMock {
	m := &AgentSubscribeServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.StartUserSubscribeMock = mAgentSubscribeServiceMockStartUserSubscribe{mock: m}
	m.StartUserSubscribeMock.callArgs = []*AgentSubscribeServiceMockStartUserSubscribeParams{}

	m.StopUserSubscribeMock = mAgentSubscribeServiceMockStopUserSubscribe{mock: m}
	m.StopUserSubscribeMock.callArgs = []*AgentSubscribeServiceMockStopUserSubscribeParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAgentSubscribeServiceMockStartUserSubscribe struct {
	optional           bool
	mock               *AgentSubscribeServiceMock
	defaultExpectation *AgentSubscribeServiceMockStartUserSubscribeExpectation
	expectations       []*AgentSubscribeServiceMockStartUserSubscribeExpectation

	callArgs []*AgentSubscribeServiceMockStartUserSubscribeParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AgentSubscribeServiceMockStartUserSubscribeExpectation specifies expectation struct of the AgentSubscribeService.StartUserSubscribe
type AgentSubscribeServiceMockStartUserSubscribeExpectation struct {
	mock               *AgentSubscribeServiceMock
	params             *AgentSubscribeServiceMockStartUserSubscribeParams
	paramPtrs          *AgentSubscribeServiceMockStartUserSubscribeParamPtrs
	expectationOrigins AgentSubscribeServiceMockStartUserSubscribeExpectationOrigins
	results            *AgentSubscribeServiceMockStartUserSubscribeResults
	returnOrigin       string
	Counter            uint64
}

// AgentSubscribeServiceMockStartUserSubscribeParams contains parameters of the AgentSubscribeService.StartUserSubscribe
type AgentSubscribeServiceMockStartUserSubscribeParams struct {
	ctx   context.Context
	input model.SubscriptionActivatedEvent
}

// AgentSubscribeServiceMockStartUserSubscribeParamPtrs contains pointers to parameters of the AgentSubscribeService.StartUserSubscribe
type AgentSubscribeServiceMockStartUserSubscribeParamPtrs struct {
	ctx   *context.Context
	input *model.SubscriptionActivatedEvent
}

// AgentSubscribeServiceMockStartUserSubscribeResults contains results of the AgentSubscribeService.StartUserSubscribe
type AgentSubscribeServiceMockStartUserSubscribeResults struct {
	err error
}

// AgentSubscribeServiceMockStartUserSubscribeOrigins contains origins of expectations of the AgentSubscribeService.StartUserSubscribe
type AgentSubscribeServiceMockStartUserSubscribeExpectationOrigins struct {
	origin      string
	originCtx   string
	originInput string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmStartUserSubscribe *mAgentSubscribeServiceMockStartUserSubscribe) Optional() *mAgentSubscribeServiceMockStartUserSubscribe {
	mmStartUserSubscribe.optional = true
	return mmStartUserSubscribe
}

// Expect sets up expected params for AgentSubscribeService.StartUserSubscribe
func (mmStartUserSubscribe *mAgentSubscribeServiceMockStartUserSubscribe) Expect(ctx context.Context, input model.SubscriptionActivatedEvent) *mAgentSubscribeServiceMockStartUserSubscribe {
	if mmStartUserSubscribe.mock.funcStartUserSubscribe != nil {
		mmStartUserSubscribe.mock.t.Fatalf("AgentSubscribeServiceMock.StartUserSubscribe mock is already set by Set")
	}

	if mmStartUserSubscribe.defaultExpectation == nil {
		mmStartUserSubscribe.defaultExpectation = &AgentSubscribeServiceMockStartUserSubscribeExpectation{}
	}

	if mmStartUserSubscribe.defaultExpectation.paramPtrs != nil {
		mmStartUserSubscribe.mock.t.Fatalf("AgentSubscribeServiceMock.StartUserSubscribe mock is already set by ExpectParams functions")
	}

	mmStartUserSubscribe.defaultExpectation.params = &AgentSubscribeServiceMockStartUserSubscribeParams{ctx, input}
	mmStartUserSubscribe.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmStartUserSubscribe.expectations {
		if minimock.Equal(e.params, mmStartUserSubscribe.defaultExpectation.params) {
			mmStartUserSubscribe.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmStartUserSubscribe.defaultExpectation.params)
		}
	}

	return mmStartUserSubscribe
}

// ExpectCtxParam1 sets up expected param ctx for AgentSubscribeService.StartUserSubscribe
func (mmStartUserSubscribe *mAgentSubscribeServiceMockStartUserSubscribe) ExpectCtxParam1(ctx context.Context) *mAgentSubscribeServiceMockStartUserSubscribe {
	if mmStartUserSubscribe.mock.funcStartUserSubscribe != nil {
		mmStartUserSubscribe.mock.t.Fatalf("AgentSubscribeServiceMock.StartUserSubscribe mock is already set by Set")
	}

	if mmStartUserSubscribe.defaultExpectation == nil {
		mmStartUserSubscribe.defaultExpectation = &AgentSubscribeServiceMockStartUserSubscribeExpectation{}
	}

	if mmStartUserSubscribe.defaultExpectation.params != nil {
		mmStartUserSubscribe.mock.t.Fatalf("AgentSubscribeServiceMock.StartUserSubscribe mock is already set by Expect")
	}

	if mmStartUserSubscribe.defaultExpectation.paramPtrs == nil {
		mmStartUserSubscribe.defaultExpectation.paramPtrs = &AgentSubscribeServiceMockStartUserSubscribeParamPtrs{}
	}
	mmStartUserSubscribe.defaultExpectation.paramPtrs.ctx = &ctx
	mmStartUserSubscribe.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmStartUserSubscribe
}

// ExpectInputParam2 sets up expected param input for AgentSubscribeService.StartUserSubscribe
func (mmStartUserSubscribe *mAgentSubscribeServiceMockStartUserSubscribe) ExpectInputParam2(input model.SubscriptionActivatedEvent) *mAgentSubscribeServiceMockStartUserSubscribe {
	if mmStartUserSubscribe.mock.funcStartUserSubscribe != nil {
		mmStartUserSubscribe.mock.t.Fatalf("AgentSubscribeServiceMock.StartUserSubscribe mock is already set by Set")
	}

	if mmStartUserSubscribe.defaultExpectation == nil {
		mmStartUserSubscribe.defaultExpectation = &AgentSubscribeServiceMockStartUserSubscribeExpectation{}
	}

	if mmStartUserSubscribe.defaultExpectation.params != nil {
		mmStartUserSubscribe.mock.t.Fatalf("AgentSubscribeServiceMock.StartUserSubscribe mock is already set by Expect")
	}

	if mmStartUserSubscribe.defaultExpectation.paramPtrs == nil {
		mmStartUserSubscribe.defaultExpectation.paramPtrs = &AgentSubscribeServiceMockStartUserSubscribeParamPtrs{}
	}
	mmStartUserSubscribe.defaultExpectation.paramPtrs.input = &input
	mmStartUserSubscribe.defaultExpectation.expectationOrigins.originInput = minimock.CallerInfo(1)

	return mmStartUserSubscribe
}

// Inspect accepts an inspector function that has same arguments as the AgentSubscribeService.StartUserSubscribe
func (mmStartUserSubscribe *mAgentSubscribeServiceMockStartUserSubscribe) Inspect(f func(ctx context.Context, input model.SubscriptionActivatedEvent)) *mAgentSubscribeServiceMockStartUserSubscribe {
	if mmStartUserSubscribe.mock.inspectFuncStartUserSubscribe != nil {
		mmStartUserSubscribe.mock.t.Fatalf("Inspect function is already set for AgentSubscribeServiceMock.StartUserSubscribe")
	}

	mmStartUserSubscribe.mock.inspectFuncStartUserSubscribe = f

	return mmStartUserSubscribe
}

// Return sets up results that will be returned by AgentSubscribeService.StartUserSubscribe
func (mmStartUserSubscribe *mAgentSubscribeServiceMockStartUserSubscribe) Return(err error) *AgentSubscribeServiceMock {
	if mmStartUserSubscribe.mock.funcStartUserSubscribe != nil {
		mmStartUserSubscribe.mock.t.Fatalf("AgentSubscribeServiceMock.StartUserSubscribe mock is already set by Set")
	}

	if mmStartUserSubscribe.defaultExpectation == nil {
		mmStartUserSubscribe.defaultExpectation = &AgentSubscribeServiceMockStartUserSubscribeExpectation{mock: mmStartUserSubscribe.mock}
	}
	mmStartUserSubscribe.defaultExpectation.results = &AgentSubscribeServiceMockStartUserSubscribeResults{err}
	mmStartUserSubscribe.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmStartUserSubscribe.mock
}

// Set uses given function f to mock the AgentSubscribeService.StartUserSubscribe method
func (mmStartUserSubscribe *mAgentSubscribeServiceMockStartUserSubscribe) Set(f func(ctx context.Context, input model.SubscriptionActivatedEvent) (err error)) *AgentSubscribeServiceMock {
	if mmStartUserSubscribe.defaultExpectation != nil {
		mmStartUserSubscribe.mock.t.Fatalf("Default expectation is already set for the AgentSubscribeService.StartUserSubscribe method")
	}

	if len(mmStartUserSubscribe.expectations) > 0 {
		mmStartUserSubscribe.mock.t.Fatalf("Some expectations are already set for the AgentSubscribeService.StartUserSubscribe method")
	}

	mmStartUserSubscribe.mock.funcStartUserSubscribe = f
	mmStartUserSubscribe.mock.funcStartUserSubscribeOrigin = minimock.CallerInfo(1)
	return mmStartUserSubscribe.mock
}

// When sets expectation for the AgentSubscribeService.StartUserSubscribe which will trigger the result defined by the following
// Then helper
func (mmStartUserSubscribe *mAgentSubscribeServiceMockStartUserSubscribe) When(ctx context.Context, input model.SubscriptionActivatedEvent) *AgentSubscribeServiceMockStartUserSubscribeExpectation {
	if mmStartUserSubscribe.mock.funcStartUserSubscribe != nil {
		mmStartUserSubscribe.mock.t.Fatalf("AgentSubscribeServiceMock.StartUserSubscribe mock is already set by Set")
	}

	expectation := &AgentSubscribeServiceMockStartUserSubscribeExpectation{
		mock:               mmStartUserSubscribe.mock,
		params:             &AgentSubscribeServiceMockStartUserSubscribeParams{ctx, input},
		expectationOrigins: AgentSubscribeServiceMockStartUserSubscribeExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmStartUserSubscribe.expectations = append(mmStartUserSubscribe.expectations, expectation)
	return expectation
}

// Then sets up AgentSubscribeService.StartUserSubscribe return parameters for the expectation previously defined by the When method
func (e *AgentSubscribeServiceMockStartUserSubscribeExpectation) Then(err error) *AgentSubscribeServiceMock {
	e.results = &AgentSubscribeServiceMockStartUserSubscribeResults{err}
	return e.mock
}

// Times sets number of times AgentSubscribeService.StartUserSubscribe should be invoked
func (mmStartUserSubscribe *mAgentSubscribeServiceMockStartUserSubscribe) Times(n uint64) *mAgentSubscribeServiceMockStartUserSubscribe {
	if n == 0 {
		mmStartUserSubscribe.mock.t.Fatalf("Times of AgentSubscribeServiceMock.StartUserSubscribe mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmStartUserSubscribe.expectedInvocations, n)
	mmStartUserSubscribe.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmStartUserSubscribe
}

func (mmStartUserSubscribe *mAgentSubscribeServiceMockStartUserSubscribe) invocationsDone() bool {
	if len(mmStartUserSubscribe.expectations) == 0 && mmStartUserSubscribe.defaultExpectation == nil && mmStartUserSubscribe.mock.funcStartUserSubscribe == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmStartUserSubscribe.mock.afterStartUserSubscribeCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmStartUserSubscribe.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// StartUserSubscribe implements mm_workers.AgentSubscribeService
func (mmStartUserSubscribe *AgentSubscribeServiceMock) StartUserSubscribe(ctx context.Context, input model.SubscriptionActivatedEvent) (err error) {
	mm_atomic.AddUint64(&mmStartUserSubscribe.beforeStartUserSubscribeCounter, 1)
	defer mm_atomic.AddUint64(&mmStartUserSubscribe.afterStartUserSubscribeCounter, 1)

	mmStartUserSubscribe.t.Helper()

	if mmStartUserSubscribe.inspectFuncStartUserSubscribe != nil {
		mmStartUserSubscribe.inspectFuncStartUserSubscribe(ctx, input)
	}

	mm_params := AgentSubscribeServiceMockStartUserSubscribeParams{ctx, input}

	// Record call args
	mmStartUserSubscribe.StartUserSubscribeMock.mutex.Lock()
	mmStartUserSubscribe.StartUserSubscribeMock.callArgs = append(mmStartUserSubscribe.StartUserSubscribeMock.callArgs, &mm_params)
	mmStartUserSubscribe.StartUserSubscribeMock.mutex.Unlock()

	for _, e := range mmStartUserSubscribe.StartUserSubscribeMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmStartUserSubscribe.StartUserSubscribeMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmStartUserSubscribe.StartUserSubscribeMock.defaultExpectation.Counter, 1)
		mm_want := mmStartUserSubscribe.StartUserSubscribeMock.defaultExpectation.params
		mm_want_ptrs := mmStartUserSubscribe.StartUserSubscribeMock.defaultExpectation.paramPtrs

		mm_got := AgentSubscribeServiceMockStartUserSubscribeParams{ctx, input}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmStartUserSubscribe.t.Errorf("AgentSubscribeServiceMock.StartUserSubscribe got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStartUserSubscribe.StartUserSubscribeMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.input != nil && !minimock.Equal(*mm_want_ptrs.input, mm_got.input) {
				mmStartUserSubscribe.t.Errorf("AgentSubscribeServiceMock.StartUserSubscribe got unexpected parameter input, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStartUserSubscribe.StartUserSubscribeMock.defaultExpectation.expectationOrigins.originInput, *mm_want_ptrs.input, mm_got.input, minimock.Diff(*mm_want_ptrs.input, mm_got.input))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmStartUserSubscribe.t.Errorf("AgentSubscribeServiceMock.StartUserSubscribe got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmStartUserSubscribe.StartUserSubscribeMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmStartUserSubscribe.StartUserSubscribeMock.defaultExpectation.results
		if mm_results == nil {
			mmStartUserSubscribe.t.Fatal("No results are set for the AgentSubscribeServiceMock.StartUserSubscribe")
		}
		return (*mm_results).err
	}
	if mmStartUserSubscribe.funcStartUserSubscribe != nil {
		return mmStartUserSubscribe.funcStartUserSubscribe(ctx, input)
	}
	mmStartUserSubscribe.t.Fatalf("Unexpected call to AgentSubscribeServiceMock.StartUserSubscribe. %v %v", ctx, input)
	return
}

// StartUserSubscribeAfterCounter returns a count of finished AgentSubscribeServiceMock.StartUserSubscribe invocations
func (mmStartUserSubscribe *AgentSubscribeServiceMock) StartUserSubscribeAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStartUserSubscribe.afterStartUserSubscribeCounter)
}

// StartUserSubscribeBeforeCounter returns a count of AgentSubscribeServiceMock.StartUserSubscribe invocations
func (mmStartUserSubscribe *AgentSubscribeServiceMock) StartUserSubscribeBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStartUserSubscribe.beforeStartUserSubscribeCounter)
}

// Calls returns a list of arguments used in each call to AgentSubscribeServiceMock.StartUserSubscribe.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmStartUserSubscribe *mAgentSubscribeServiceMockStartUserSubscribe) Calls() []*AgentSubscribeServiceMockStartUserSubscribeParams {
	mmStartUserSubscribe.mutex.RLock()

	argCopy := make([]*AgentSubscribeServiceMockStartUserSubscribeParams, len(mmStartUserSubscribe.callArgs))
	copy(argCopy, mmStartUserSubscribe.callArgs)

	mmStartUserSubscribe.mutex.RUnlock()

	return argCopy
}

// MinimockStartUserSubscribeDone returns true if the count of the StartUserSubscribe invocations corresponds
// the number of defined expectations
func (m *AgentSubscribeServiceMock) MinimockStartUserSubscribeDone() bool {
	if m.StartUserSubscribeMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.StartUserSubscribeMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.StartUserSubscribeMock.invocationsDone()
}

// MinimockStartUserSubscribeInspect logs each unmet expectation
func (m *AgentSubscribeServiceMock) MinimockStartUserSubscribeInspect() {
	for _, e := range m.StartUserSubscribeMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AgentSubscribeServiceMock.StartUserSubscribe at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterStartUserSubscribeCounter := mm_atomic.LoadUint64(&m.afterStartUserSubscribeCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.StartUserSubscribeMock.defaultExpectation != nil && afterStartUserSubscribeCounter < 1 {
		if m.StartUserSubscribeMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AgentSubscribeServiceMock.StartUserSubscribe at\n%s", m.StartUserSubscribeMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AgentSubscribeServiceMock.StartUserSubscribe at\n%s with params: %#v", m.StartUserSubscribeMock.defaultExpectation.expectationOrigins.origin, *m.StartUserSubscribeMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStartUserSubscribe != nil && afterStartUserSubscribeCounter < 1 {
		m.t.Errorf("Expected call to AgentSubscribeServiceMock.StartUserSubscribe at\n%s", m.funcStartUserSubscribeOrigin)
	}

	if !m.StartUserSubscribeMock.invocationsDone() && afterStartUserSubscribeCounter > 0 {
		m.t.Errorf("Expected %d calls to AgentSubscribeServiceMock.StartUserSubscribe at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.StartUserSubscribeMock.expectedInvocations), m.StartUserSubscribeMock.expectedInvocationsOrigin, afterStartUserSubscribeCounter)
	}
}

type mAgentSubscribeServiceMockStopUserSubscribe struct {
	optional           bool
	mock               *AgentSubscribeServiceMock
	defaultExpectation *AgentSubscribeServiceMockStopUserSubscribeExpectation
	expectations       []*AgentSubscribeServiceMockStopUserSubscribeExpectation

	callArgs []*AgentSubscribeServiceMockStopUserSubscribeParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AgentSubscribeServiceMockStopUserSubscribeExpectation specifies expectation struct of the AgentSubscribeService.StopUserSubscribe
type AgentSubscribeServiceMockStopUserSubscribeExpectation struct {
	mock               *AgentSubscribeServiceMock
	params             *AgentSubscribeServiceMockStopUserSubscribeParams
	paramPtrs          *AgentSubscribeServiceMockStopUserSubscribeParamPtrs
	expectationOrigins AgentSubscribeServiceMockStopUserSubscribeExpectationOrigins
	results            *AgentSubscribeServiceMockStopUserSubscribeResults
	returnOrigin       string
	Counter            uint64
}

// AgentSubscribeServiceMockStopUserSubscribeParams contains parameters of the AgentSubscribeService.StopUserSubscribe
type AgentSubscribeServiceMockStopUserSubscribeParams struct {
	ctx   context.Context
	input model.SubscriptionCancelEvent
}

// AgentSubscribeServiceMockStopUserSubscribeParamPtrs contains pointers to parameters of the AgentSubscribeService.StopUserSubscribe
type AgentSubscribeServiceMockStopUserSubscribeParamPtrs struct {
	ctx   *context.Context
	input *model.SubscriptionCancelEvent
}

// AgentSubscribeServiceMockStopUserSubscribeResults contains results of the AgentSubscribeService.StopUserSubscribe
type AgentSubscribeServiceMockStopUserSubscribeResults struct {
	err error
}

// AgentSubscribeServiceMockStopUserSubscribeOrigins contains origins of expectations of the AgentSubscribeService.StopUserSubscribe
type AgentSubscribeServiceMockStopUserSubscribeExpectationOrigins struct {
	origin      string
	originCtx   string
	originInput string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmStopUserSubscribe *mAgentSubscribeServiceMockStopUserSubscribe) Optional() *mAgentSubscribeServiceMockStopUserSubscribe {
	mmStopUserSubscribe.optional = true
	return mmStopUserSubscribe
}

// Expect sets up expected params for AgentSubscribeService.StopUserSubscribe
func (mmStopUserSubscribe *mAgentSubscribeServiceMockStopUserSubscribe) Expect(ctx context.Context, input model.SubscriptionCancelEvent) *mAgentSubscribeServiceMockStopUserSubscribe {
	if mmStopUserSubscribe.mock.funcStopUserSubscribe != nil {
		mmStopUserSubscribe.mock.t.Fatalf("AgentSubscribeServiceMock.StopUserSubscribe mock is already set by Set")
	}

	if mmStopUserSubscribe.defaultExpectation == nil {
		mmStopUserSubscribe.defaultExpectation = &AgentSubscribeServiceMockStopUserSubscribeExpectation{}
	}

	if mmStopUserSubscribe.defaultExpectation.paramPtrs != nil {
		mmStopUserSubscribe.mock.t.Fatalf("AgentSubscribeServiceMock.StopUserSubscribe mock is already set by ExpectParams functions")
	}

	mmStopUserSubscribe.defaultExpectation.params = &AgentSubscribeServiceMockStopUserSubscribeParams{ctx, input}
	mmStopUserSubscribe.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmStopUserSubscribe.expectations {
		if minimock.Equal(e.params, mmStopUserSubscribe.defaultExpectation.params) {
			mmStopUserSubscribe.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmStopUserSubscribe.defaultExpectation.params)
		}
	}

	return mmStopUserSubscribe
}

// ExpectCtxParam1 sets up expected param ctx for AgentSubscribeService.StopUserSubscribe
func (mmStopUserSubscribe *mAgentSubscribeServiceMockStopUserSubscribe) ExpectCtxParam1(ctx context.Context) *mAgentSubscribeServiceMockStopUserSubscribe {
	if mmStopUserSubscribe.mock.funcStopUserSubscribe != nil {
		mmStopUserSubscribe.mock.t.Fatalf("AgentSubscribeServiceMock.StopUserSubscribe mock is already set by Set")
	}

	if mmStopUserSubscribe.defaultExpectation == nil {
		mmStopUserSubscribe.defaultExpectation = &AgentSubscribeServiceMockStopUserSubscribeExpectation{}
	}

	if mmStopUserSubscribe.defaultExpectation.params != nil {
		mmStopUserSubscribe.mock.t.Fatalf("AgentSubscribeServiceMock.StopUserSubscribe mock is already set by Expect")
	}

	if mmStopUserSubscribe.defaultExpectation.paramPtrs == nil {
		mmStopUserSubscribe.defaultExpectation.paramPtrs = &AgentSubscribeServiceMockStopUserSubscribeParamPtrs{}
	}
	mmStopUserSubscribe.defaultExpectation.paramPtrs.ctx = &ctx
	mmStopUserSubscribe.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmStopUserSubscribe
}

// ExpectInputParam2 sets up expected param input for AgentSubscribeService.StopUserSubscribe
func (mmStopUserSubscribe *mAgentSubscribeServiceMockStopUserSubscribe) ExpectInputParam2(input model.SubscriptionCancelEvent) *mAgentSubscribeServiceMockStopUserSubscribe {
	if mmStopUserSubscribe.mock.funcStopUserSubscribe != nil {
		mmStopUserSubscribe.mock.t.Fatalf("AgentSubscribeServiceMock.StopUserSubscribe mock is already set by Set")
	}

	if mmStopUserSubscribe.defaultExpectation == nil {
		mmStopUserSubscribe.defaultExpectation = &AgentSubscribeServiceMockStopUserSubscribeExpectation{}
	}

	if mmStopUserSubscribe.defaultExpectation.params != nil {
		mmStopUserSubscribe.mock.t.Fatalf("AgentSubscribeServiceMock.StopUserSubscribe mock is already set by Expect")
	}

	if mmStopUserSubscribe.defaultExpectation.paramPtrs == nil {
		mmStopUserSubscribe.defaultExpectation.paramPtrs = &AgentSubscribeServiceMockStopUserSubscribeParamPtrs{}
	}
	mmStopUserSubscribe.defaultExpectation.paramPtrs.input = &input
	mmStopUserSubscribe.defaultExpectation.expectationOrigins.originInput = minimock.CallerInfo(1)

	return mmStopUserSubscribe
}

// Inspect accepts an inspector function that has same arguments as the AgentSubscribeService.StopUserSubscribe
func (mmStopUserSubscribe *mAgentSubscribeServiceMockStopUserSubscribe) Inspect(f func(ctx context.Context, input model.SubscriptionCancelEvent)) *mAgentSubscribeServiceMockStopUserSubscribe {
	if mmStopUserSubscribe.mock.inspectFuncStopUserSubscribe != nil {
		mmStopUserSubscribe.mock.t.Fatalf("Inspect function is already set for AgentSubscribeServiceMock.StopUserSubscribe")
	}

	mmStopUserSubscribe.mock.inspectFuncStopUserSubscribe = f

	return mmStopUserSubscribe
}

// Return sets up results that will be returned by AgentSubscribeService.StopUserSubscribe
func (mmStopUserSubscribe *mAgentSubscribeServiceMockStopUserSubscribe) Return(err error) *AgentSubscribeServiceMock {
	if mmStopUserSubscribe.mock.funcStopUserSubscribe != nil {
		mmStopUserSubscribe.mock.t.Fatalf("AgentSubscribeServiceMock.StopUserSubscribe mock is already set by Set")
	}

	if mmStopUserSubscribe.defaultExpectation == nil {
		mmStopUserSubscribe.defaultExpectation = &AgentSubscribeServiceMockStopUserSubscribeExpectation{mock: mmStopUserSubscribe.mock}
	}
	mmStopUserSubscribe.defaultExpectation.results = &AgentSubscribeServiceMockStopUserSubscribeResults{err}
	mmStopUserSubscribe.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmStopUserSubscribe.mock
}

// Set uses given function f to mock the AgentSubscribeService.StopUserSubscribe method
func (mmStopUserSubscribe *mAgentSubscribeServiceMockStopUserSubscribe) Set(f func(ctx context.Context, input model.SubscriptionCancelEvent) (err error)) *AgentSubscribeServiceMock {
	if mmStopUserSubscribe.defaultExpectation != nil {
		mmStopUserSubscribe.mock.t.Fatalf("Default expectation is already set for the AgentSubscribeService.StopUserSubscribe method")
	}

	if len(mmStopUserSubscribe.expectations) > 0 {
		mmStopUserSubscribe.mock.t.Fatalf("Some expectations are already set for the AgentSubscribeService.StopUserSubscribe method")
	}

	mmStopUserSubscribe.mock.funcStopUserSubscribe = f
	mmStopUserSubscribe.mock.funcStopUserSubscribeOrigin = minimock.CallerInfo(1)
	return mmStopUserSubscribe.mock
}

// When sets expectation for the AgentSubscribeService.StopUserSubscribe which will trigger the result defined by the following
// Then helper
func (mmStopUserSubscribe *mAgentSubscribeServiceMockStopUserSubscribe) When(ctx context.Context, input model.SubscriptionCancelEvent) *AgentSubscribeServiceMockStopUserSubscribeExpectation {
	if mmStopUserSubscribe.mock.funcStopUserSubscribe != nil {
		mmStopUserSubscribe.mock.t.Fatalf("AgentSubscribeServiceMock.StopUserSubscribe mock is already set by Set")
	}

	expectation := &AgentSubscribeServiceMockStopUserSubscribeExpectation{
		mock:               mmStopUserSubscribe.mock,
		params:             &AgentSubscribeServiceMockStopUserSubscribeParams{ctx, input},
		expectationOrigins: AgentSubscribeServiceMockStopUserSubscribeExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmStopUserSubscribe.expectations = append(mmStopUserSubscribe.expectations, expectation)
	return expectation
}

// Then sets up AgentSubscribeService.StopUserSubscribe return parameters for the expectation previously defined by the When method
func (e *AgentSubscribeServiceMockStopUserSubscribeExpectation) Then(err error) *AgentSubscribeServiceMock {
	e.results = &AgentSubscribeServiceMockStopUserSubscribeResults{err}
	return e.mock
}

// Times sets number of times AgentSubscribeService.StopUserSubscribe should be invoked
func (mmStopUserSubscribe *mAgentSubscribeServiceMockStopUserSubscribe) Times(n uint64) *mAgentSubscribeServiceMockStopUserSubscribe {
	if n == 0 {
		mmStopUserSubscribe.mock.t.Fatalf("Times of AgentSubscribeServiceMock.StopUserSubscribe mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmStopUserSubscribe.expectedInvocations, n)
	mmStopUserSubscribe.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmStopUserSubscribe
}

func (mmStopUserSubscribe *mAgentSubscribeServiceMockStopUserSubscribe) invocationsDone() bool {
	if len(mmStopUserSubscribe.expectations) == 0 && mmStopUserSubscribe.defaultExpectation == nil && mmStopUserSubscribe.mock.funcStopUserSubscribe == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmStopUserSubscribe.mock.afterStopUserSubscribeCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmStopUserSubscribe.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// StopUserSubscribe implements mm_workers.AgentSubscribeService
func (mmStopUserSubscribe *AgentSubscribeServiceMock) StopUserSubscribe(ctx context.Context, input model.SubscriptionCancelEvent) (err error) {
	mm_atomic.AddUint64(&mmStopUserSubscribe.beforeStopUserSubscribeCounter, 1)
	defer mm_atomic.AddUint64(&mmStopUserSubscribe.afterStopUserSubscribeCounter, 1)

	mmStopUserSubscribe.t.Helper()

	if mmStopUserSubscribe.inspectFuncStopUserSubscribe != nil {
		mmStopUserSubscribe.inspectFuncStopUserSubscribe(ctx, input)
	}

	mm_params := AgentSubscribeServiceMockStopUserSubscribeParams{ctx, input}

	// Record call args
	mmStopUserSubscribe.StopUserSubscribeMock.mutex.Lock()
	mmStopUserSubscribe.StopUserSubscribeMock.callArgs = append(mmStopUserSubscribe.StopUserSubscribeMock.callArgs, &mm_params)
	mmStopUserSubscribe.StopUserSubscribeMock.mutex.Unlock()

	for _, e := range mmStopUserSubscribe.StopUserSubscribeMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmStopUserSubscribe.StopUserSubscribeMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmStopUserSubscribe.StopUserSubscribeMock.defaultExpectation.Counter, 1)
		mm_want := mmStopUserSubscribe.StopUserSubscribeMock.defaultExpectation.params
		mm_want_ptrs := mmStopUserSubscribe.StopUserSubscribeMock.defaultExpectation.paramPtrs

		mm_got := AgentSubscribeServiceMockStopUserSubscribeParams{ctx, input}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmStopUserSubscribe.t.Errorf("AgentSubscribeServiceMock.StopUserSubscribe got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStopUserSubscribe.StopUserSubscribeMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.input != nil && !minimock.Equal(*mm_want_ptrs.input, mm_got.input) {
				mmStopUserSubscribe.t.Errorf("AgentSubscribeServiceMock.StopUserSubscribe got unexpected parameter input, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStopUserSubscribe.StopUserSubscribeMock.defaultExpectation.expectationOrigins.originInput, *mm_want_ptrs.input, mm_got.input, minimock.Diff(*mm_want_ptrs.input, mm_got.input))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmStopUserSubscribe.t.Errorf("AgentSubscribeServiceMock.StopUserSubscribe got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmStopUserSubscribe.StopUserSubscribeMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmStopUserSubscribe.StopUserSubscribeMock.defaultExpectation.results
		if mm_results == nil {
			mmStopUserSubscribe.t.Fatal("No results are set for the AgentSubscribeServiceMock.StopUserSubscribe")
		}
		return (*mm_results).err
	}
	if mmStopUserSubscribe.funcStopUserSubscribe != nil {
		return mmStopUserSubscribe.funcStopUserSubscribe(ctx, input)
	}
	mmStopUserSubscribe.t.Fatalf("Unexpected call to AgentSubscribeServiceMock.StopUserSubscribe. %v %v", ctx, input)
	return
}

// StopUserSubscribeAfterCounter returns a count of finished AgentSubscribeServiceMock.StopUserSubscribe invocations
func (mmStopUserSubscribe *AgentSubscribeServiceMock) StopUserSubscribeAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStopUserSubscribe.afterStopUserSubscribeCounter)
}

// StopUserSubscribeBeforeCounter returns a count of AgentSubscribeServiceMock.StopUserSubscribe invocations
func (mmStopUserSubscribe *AgentSubscribeServiceMock) StopUserSubscribeBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStopUserSubscribe.beforeStopUserSubscribeCounter)
}

// Calls returns a list of arguments used in each call to AgentSubscribeServiceMock.StopUserSubscribe.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmStopUserSubscribe *mAgentSubscribeServiceMockStopUserSubscribe) Calls() []*AgentSubscribeServiceMockStopUserSubscribeParams {
	mmStopUserSubscribe.mutex.RLock()

	argCopy := make([]*AgentSubscribeServiceMockStopUserSubscribeParams, len(mmStopUserSubscribe.callArgs))
	copy(argCopy, mmStopUserSubscribe.callArgs)

	mmStopUserSubscribe.mutex.RUnlock()

	return argCopy
}

// MinimockStopUserSubscribeDone returns true if the count of the StopUserSubscribe invocations corresponds
// the number of defined expectations
func (m *AgentSubscribeServiceMock) MinimockStopUserSubscribeDone() bool {
	if m.StopUserSubscribeMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.StopUserSubscribeMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.StopUserSubscribeMock.invocationsDone()
}

// MinimockStopUserSubscribeInspect logs each unmet expectation
func (m *AgentSubscribeServiceMock) MinimockStopUserSubscribeInspect() {
	for _, e := range m.StopUserSubscribeMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AgentSubscribeServiceMock.StopUserSubscribe at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterStopUserSubscribeCounter := mm_atomic.LoadUint64(&m.afterStopUserSubscribeCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.StopUserSubscribeMock.defaultExpectation != nil && afterStopUserSubscribeCounter < 1 {
		if m.StopUserSubscribeMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AgentSubscribeServiceMock.StopUserSubscribe at\n%s", m.StopUserSubscribeMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AgentSubscribeServiceMock.StopUserSubscribe at\n%s with params: %#v", m.StopUserSubscribeMock.defaultExpectation.expectationOrigins.origin, *m.StopUserSubscribeMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStopUserSubscribe != nil && afterStopUserSubscribeCounter < 1 {
		m.t.Errorf("Expected call to AgentSubscribeServiceMock.StopUserSubscribe at\n%s", m.funcStopUserSubscribeOrigin)
	}

	if !m.StopUserSubscribeMock.invocationsDone() && afterStopUserSubscribeCounter > 0 {
		m.t.Errorf("Expected %d calls to AgentSubscribeServiceMock.StopUserSubscribe at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.StopUserSubscribeMock.expectedInvocations), m.StopUserSubscribeMock.expectedInvocationsOrigin, afterStopUserSubscribeCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AgentSubscribeServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockStartUserSubscribeInspect()

			m.MinimockStopUserSubscribeInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AgentSubscribeServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AgentSubscribeServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockStartUserSubscribeDone() &&
		m.MinimockStopUserSubscribeDone()
}
