// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i control-plane/internal/workers.Storage -o storage_mock.go -n StorageMock -p mocks

import (
	"context"
	"control-plane/internal/model"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// StorageMock implements mm_workers.Storage
type StorageMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcFetchUnprocessedOutboxEvents          func(ctx context.Context, limit int, attemptsLimit int) (oa1 []model.OutboxEvent, err error)
	funcFetchUnprocessedOutboxEventsOrigin    string
	inspectFuncFetchUnprocessedOutboxEvents   func(ctx context.Context, limit int, attemptsLimit int)
	afterFetchUnprocessedOutboxEventsCounter  uint64
	beforeFetchUnprocessedOutboxEventsCounter uint64
	FetchUnprocessedOutboxEventsMock          mStorageMockFetchUnprocessedOutboxEvents

	funcMarkOutboxEventFailed          func(ctx context.Context, id string, errMsg string) (err error)
	funcMarkOutboxEventFailedOrigin    string
	inspectFuncMarkOutboxEventFailed   func(ctx context.Context, id string, errMsg string)
	afterMarkOutboxEventFailedCounter  uint64
	beforeMarkOutboxEventFailedCounter uint64
	MarkOutboxEventFailedMock          mStorageMockMarkOutboxEventFailed

	funcMarkOutboxEventProcessed          func(ctx context.Context, id string) (err error)
	funcMarkOutboxEventProcessedOrigin    string
	inspectFuncMarkOutboxEventProcessed   func(ctx context.Context, id string)
	afterMarkOutboxEventProcessedCounter  uint64
	beforeMarkOutboxEventProcessedCounter uint64
	MarkOutboxEventProcessedMock          mStorageMockMarkOutboxEventProcessed

	funcSaveOutboxEvent          func(ctx context.Context, eventType string, payload any) (err error)
	funcSaveOutboxEventOrigin    string
	inspectFuncSaveOutboxEvent   func(ctx context.Context, eventType string, payload any)
	afterSaveOutboxEventCounter  uint64
	beforeSaveOutboxEventCounter uint64
	SaveOutboxEventMock          mStorageMockSaveOutboxEvent
}

// NewStorageMock returns a mock for mm_workers.Storage
func NewStorageMock(t minimock.Tester) *StorageMock {
	m := &StorageMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.FetchUnprocessedOutboxEventsMock = mStorageMockFetchUnprocessedOutboxEvents{mock: m}
	m.FetchUnprocessedOutboxEventsMock.callArgs = []*StorageMockFetchUnprocessedOutboxEventsParams{}

	m.MarkOutboxEventFailedMock = mStorageMockMarkOutboxEventFailed{mock: m}
	m.MarkOutboxEventFailedMock.callArgs = []*StorageMockMarkOutboxEventFailedParams{}

	m.MarkOutboxEventProcessedMock = mStorageMockMarkOutboxEventProcessed{mock: m}
	m.MarkOutboxEventProcessedMock.callArgs = []*StorageMockMarkOutboxEventProcessedParams{}

	m.SaveOutboxEventMock = mStorageMockSaveOutboxEvent{mock: m}
	m.SaveOutboxEventMock.callArgs = []*StorageMockSaveOutboxEventParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mStorageMockFetchUnprocessedOutboxEvents struct {
	optional           bool
	mock               *StorageMock
	defaultExpectation *StorageMockFetchUnprocessedOutboxEventsExpectation
	expectations       []*StorageMockFetchUnprocessedOutboxEventsExpectation

	callArgs []*StorageMockFetchUnprocessedOutboxEventsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageMockFetchUnprocessedOutboxEventsExpectation specifies expectation struct of the Storage.FetchUnprocessedOutboxEvents
type StorageMockFetchUnprocessedOutboxEventsExpectation struct {
	mock               *StorageMock
	params             *StorageMockFetchUnprocessedOutboxEventsParams
	paramPtrs          *StorageMockFetchUnprocessedOutboxEventsParamPtrs
	expectationOrigins StorageMockFetchUnprocessedOutboxEventsExpectationOrigins
	results            *StorageMockFetchUnprocessedOutboxEventsResults
	returnOrigin       string
	Counter            uint64
}

// StorageMockFetchUnprocessedOutboxEventsParams contains parameters of the Storage.FetchUnprocessedOutboxEvents
type StorageMockFetchUnprocessedOutboxEventsParams struct {
	ctx           context.Context
	limit         int
	attemptsLimit int
}

// StorageMockFetchUnprocessedOutboxEventsParamPtrs contains pointers to parameters of the Storage.FetchUnprocessedOutboxEvents
type StorageMockFetchUnprocessedOutboxEventsParamPtrs struct {
	ctx           *context.Context
	limit         *int
	attemptsLimit *int
}

// StorageMockFetchUnprocessedOutboxEventsResults contains results of the Storage.FetchUnprocessedOutboxEvents
type StorageMockFetchUnprocessedOutboxEventsResults struct {
	oa1 []model.OutboxEvent
	err error
}

// StorageMockFetchUnprocessedOutboxEventsOrigins contains origins of expectations of the Storage.FetchUnprocessedOutboxEvents
type StorageMockFetchUnprocessedOutboxEventsExpectationOrigins struct {
	origin              string
	originCtx           string
	originLimit         string
	originAttemptsLimit string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmFetchUnprocessedOutboxEvents *mStorageMockFetchUnprocessedOutboxEvents) Optional() *mStorageMockFetchUnprocessedOutboxEvents {
	mmFetchUnprocessedOutboxEvents.optional = true
	return mmFetchUnprocessedOutboxEvents
}

// Expect sets up expected params for Storage.FetchUnprocessedOutboxEvents
func (mmFetchUnprocessedOutboxEvents *mStorageMockFetchUnprocessedOutboxEvents) Expect(ctx context.Context, limit int, attemptsLimit int) *mStorageMockFetchUnprocessedOutboxEvents {
	if mmFetchUnprocessedOutboxEvents.mock.funcFetchUnprocessedOutboxEvents != nil {
		mmFetchUnprocessedOutboxEvents.mock.t.Fatalf("StorageMock.FetchUnprocessedOutboxEvents mock is already set by Set")
	}

	if mmFetchUnprocessedOutboxEvents.defaultExpectation == nil {
		mmFetchUnprocessedOutboxEvents.defaultExpectation = &StorageMockFetchUnprocessedOutboxEventsExpectation{}
	}

	if mmFetchUnprocessedOutboxEvents.defaultExpectation.paramPtrs != nil {
		mmFetchUnprocessedOutboxEvents.mock.t.Fatalf("StorageMock.FetchUnprocessedOutboxEvents mock is already set by ExpectParams functions")
	}

	mmFetchUnprocessedOutboxEvents.defaultExpectation.params = &StorageMockFetchUnprocessedOutboxEventsParams{ctx, limit, attemptsLimit}
	mmFetchUnprocessedOutboxEvents.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmFetchUnprocessedOutboxEvents.expectations {
		if minimock.Equal(e.params, mmFetchUnprocessedOutboxEvents.defaultExpectation.params) {
			mmFetchUnprocessedOutboxEvents.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmFetchUnprocessedOutboxEvents.defaultExpectation.params)
		}
	}

	return mmFetchUnprocessedOutboxEvents
}

// ExpectCtxParam1 sets up expected param ctx for Storage.FetchUnprocessedOutboxEvents
func (mmFetchUnprocessedOutboxEvents *mStorageMockFetchUnprocessedOutboxEvents) ExpectCtxParam1(ctx context.Context) *mStorageMockFetchUnprocessedOutboxEvents {
	if mmFetchUnprocessedOutboxEvents.mock.funcFetchUnprocessedOutboxEvents != nil {
		mmFetchUnprocessedOutboxEvents.mock.t.Fatalf("StorageMock.FetchUnprocessedOutboxEvents mock is already set by Set")
	}

	if mmFetchUnprocessedOutboxEvents.defaultExpectation == nil {
		mmFetchUnprocessedOutboxEvents.defaultExpectation = &StorageMockFetchUnprocessedOutboxEventsExpectation{}
	}

	if mmFetchUnprocessedOutboxEvents.defaultExpectation.params != nil {
		mmFetchUnprocessedOutboxEvents.mock.t.Fatalf("StorageMock.FetchUnprocessedOutboxEvents mock is already set by Expect")
	}

	if mmFetchUnprocessedOutboxEvents.defaultExpectation.paramPtrs == nil {
		mmFetchUnprocessedOutboxEvents.defaultExpectation.paramPtrs = &StorageMockFetchUnprocessedOutboxEventsParamPtrs{}
	}
	mmFetchUnprocessedOutboxEvents.defaultExpectation.paramPtrs.ctx = &ctx
	mmFetchUnprocessedOutboxEvents.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmFetchUnprocessedOutboxEvents
}

// ExpectLimitParam2 sets up expected param limit for Storage.FetchUnprocessedOutboxEvents
func (mmFetchUnprocessedOutboxEvents *mStorageMockFetchUnprocessedOutboxEvents) ExpectLimitParam2(limit int) *mStorageMockFetchUnprocessedOutboxEvents {
	if mmFetchUnprocessedOutboxEvents.mock.funcFetchUnprocessedOutboxEvents != nil {
		mmFetchUnprocessedOutboxEvents.mock.t.Fatalf("StorageMock.FetchUnprocessedOutboxEvents mock is already set by Set")
	}

	if mmFetchUnprocessedOutboxEvents.defaultExpectation == nil {
		mmFetchUnprocessedOutboxEvents.defaultExpectation = &StorageMockFetchUnprocessedOutboxEventsExpectation{}
	}

	if mmFetchUnprocessedOutboxEvents.defaultExpectation.params != nil {
		mmFetchUnprocessedOutboxEvents.mock.t.Fatalf("StorageMock.FetchUnprocessedOutboxEvents mock is already set by Expect")
	}

	if mmFetchUnprocessedOutboxEvents.defaultExpectation.paramPtrs == nil {
		mmFetchUnprocessedOutboxEvents.defaultExpectation.paramPtrs = &StorageMockFetchUnprocessedOutboxEventsParamPtrs{}
	}
	mmFetchUnprocessedOutboxEvents.defaultExpectation.paramPtrs.limit = &limit
	mmFetchUnprocessedOutboxEvents.defaultExpectation.expectationOrigins.originLimit = minimock.CallerInfo(1)

	return mmFetchUnprocessedOutboxEvents
}

// ExpectAttemptsLimitParam3 sets up expected param attemptsLimit for Storage.FetchUnprocessedOutboxEvents
func (mmFetchUnprocessedOutboxEvents *mStorageMockFetchUnprocessedOutboxEvents) ExpectAttemptsLimitParam3(attemptsLimit int) *mStorageMockFetchUnprocessedOutboxEvents {
	if mmFetchUnprocessedOutboxEvents.mock.funcFetchUnprocessedOutboxEvents != nil {
		mmFetchUnprocessedOutboxEvents.mock.t.Fatalf("StorageMock.FetchUnprocessedOutboxEvents mock is already set by Set")
	}

	if mmFetchUnprocessedOutboxEvents.defaultExpectation == nil {
		mmFetchUnprocessedOutboxEvents.defaultExpectation = &StorageMockFetchUnprocessedOutboxEventsExpectation{}
	}

	if mmFetchUnprocessedOutboxEvents.defaultExpectation.params != nil {
		mmFetchUnprocessedOutboxEvents.mock.t.Fatalf("StorageMock.FetchUnprocessedOutboxEvents mock is already set by Expect")
	}

	if mmFetchUnprocessedOutboxEvents.defaultExpectation.paramPtrs == nil {
		mmFetchUnprocessedOutboxEvents.defaultExpectation.paramPtrs = &StorageMockFetchUnprocessedOutboxEventsParamPtrs{}
	}
	mmFetchUnprocessedOutboxEvents.defaultExpectation.paramPtrs.attemptsLimit = &attemptsLimit
	mmFetchUnprocessedOutboxEvents.defaultExpectation.expectationOrigins.originAttemptsLimit = minimock.CallerInfo(1)

	return mmFetchUnprocessedOutboxEvents
}

// Inspect accepts an inspector function that has same arguments as the Storage.FetchUnprocessedOutboxEvents
func (mmFetchUnprocessedOutboxEvents *mStorageMockFetchUnprocessedOutboxEvents) Inspect(f func(ctx context.Context, limit int, attemptsLimit int)) *mStorageMockFetchUnprocessedOutboxEvents {
	if mmFetchUnprocessedOutboxEvents.mock.inspectFuncFetchUnprocessedOutboxEvents != nil {
		mmFetchUnprocessedOutboxEvents.mock.t.Fatalf("Inspect function is already set for StorageMock.FetchUnprocessedOutboxEvents")
	}

	mmFetchUnprocessedOutboxEvents.mock.inspectFuncFetchUnprocessedOutboxEvents = f

	return mmFetchUnprocessedOutboxEvents
}

// Return sets up results that will be returned by Storage.FetchUnprocessedOutboxEvents
func (mmFetchUnprocessedOutboxEvents *mStorageMockFetchUnprocessedOutboxEvents) Return(oa1 []model.OutboxEvent, err error) *StorageMock {
	if mmFetchUnprocessedOutboxEvents.mock.funcFetchUnprocessedOutboxEvents != nil {
		mmFetchUnprocessedOutboxEvents.mock.t.Fatalf("StorageMock.FetchUnprocessedOutboxEvents mock is already set by Set")
	}

	if mmFetchUnprocessedOutboxEvents.defaultExpectation == nil {
		mmFetchUnprocessedOutboxEvents.defaultExpectation = &StorageMockFetchUnprocessedOutboxEventsExpectation{mock: mmFetchUnprocessedOutboxEvents.mock}
	}
	mmFetchUnprocessedOutboxEvents.defaultExpectation.results = &StorageMockFetchUnprocessedOutboxEventsResults{oa1, err}
	mmFetchUnprocessedOutboxEvents.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmFetchUnprocessedOutboxEvents.mock
}

// Set uses given function f to mock the Storage.FetchUnprocessedOutboxEvents method
func (mmFetchUnprocessedOutboxEvents *mStorageMockFetchUnprocessedOutboxEvents) Set(f func(ctx context.Context, limit int, attemptsLimit int) (oa1 []model.OutboxEvent, err error)) *StorageMock {
	if mmFetchUnprocessedOutboxEvents.defaultExpectation != nil {
		mmFetchUnprocessedOutboxEvents.mock.t.Fatalf("Default expectation is already set for the Storage.FetchUnprocessedOutboxEvents method")
	}

	if len(mmFetchUnprocessedOutboxEvents.expectations) > 0 {
		mmFetchUnprocessedOutboxEvents.mock.t.Fatalf("Some expectations are already set for the Storage.FetchUnprocessedOutboxEvents method")
	}

	mmFetchUnprocessedOutboxEvents.mock.funcFetchUnprocessedOutboxEvents = f
	mmFetchUnprocessedOutboxEvents.mock.funcFetchUnprocessedOutboxEventsOrigin = minimock.CallerInfo(1)
	return mmFetchUnprocessedOutboxEvents.mock
}

// When sets expectation for the Storage.FetchUnprocessedOutboxEvents which will trigger the result defined by the following
// Then helper
func (mmFetchUnprocessedOutboxEvents *mStorageMockFetchUnprocessedOutboxEvents) When(ctx context.Context, limit int, attemptsLimit int) *StorageMockFetchUnprocessedOutboxEventsExpectation {
	if mmFetchUnprocessedOutboxEvents.mock.funcFetchUnprocessedOutboxEvents != nil {
		mmFetchUnprocessedOutboxEvents.mock.t.Fatalf("StorageMock.FetchUnprocessedOutboxEvents mock is already set by Set")
	}

	expectation := &StorageMockFetchUnprocessedOutboxEventsExpectation{
		mock:               mmFetchUnprocessedOutboxEvents.mock,
		params:             &StorageMockFetchUnprocessedOutboxEventsParams{ctx, limit, attemptsLimit},
		expectationOrigins: StorageMockFetchUnprocessedOutboxEventsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmFetchUnprocessedOutboxEvents.expectations = append(mmFetchUnprocessedOutboxEvents.expectations, expectation)
	return expectation
}

// Then sets up Storage.FetchUnprocessedOutboxEvents return parameters for the expectation previously defined by the When method
func (e *StorageMockFetchUnprocessedOutboxEventsExpectation) Then(oa1 []model.OutboxEvent, err error) *StorageMock {
	e.results = &StorageMockFetchUnprocessedOutboxEventsResults{oa1, err}
	return e.mock
}

// Times sets number of times Storage.FetchUnprocessedOutboxEvents should be invoked
func (mmFetchUnprocessedOutboxEvents *mStorageMockFetchUnprocessedOutboxEvents) Times(n uint64) *mStorageMockFetchUnprocessedOutboxEvents {
	if n == 0 {
		mmFetchUnprocessedOutboxEvents.mock.t.Fatalf("Times of StorageMock.FetchUnprocessedOutboxEvents mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmFetchUnprocessedOutboxEvents.expectedInvocations, n)
	mmFetchUnprocessedOutboxEvents.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmFetchUnprocessedOutboxEvents
}

func (mmFetchUnprocessedOutboxEvents *mStorageMockFetchUnprocessedOutboxEvents) invocationsDone() bool {
	if len(mmFetchUnprocessedOutboxEvents.expectations) == 0 && mmFetchUnprocessedOutboxEvents.defaultExpectation == nil && mmFetchUnprocessedOutboxEvents.mock.funcFetchUnprocessedOutboxEvents == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmFetchUnprocessedOutboxEvents.mock.afterFetchUnprocessedOutboxEventsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmFetchUnprocessedOutboxEvents.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// FetchUnprocessedOutboxEvents implements mm_workers.Storage
func (mmFetchUnprocessedOutboxEvents *StorageMock) FetchUnprocessedOutboxEvents(ctx context.Context, limit int, attemptsLimit int) (oa1 []model.OutboxEvent, err error) {
	mm_atomic.AddUint64(&mmFetchUnprocessedOutboxEvents.beforeFetchUnprocessedOutboxEventsCounter, 1)
	defer mm_atomic.AddUint64(&mmFetchUnprocessedOutboxEvents.afterFetchUnprocessedOutboxEventsCounter, 1)

	mmFetchUnprocessedOutboxEvents.t.Helper()

	if mmFetchUnprocessedOutboxEvents.inspectFuncFetchUnprocessedOutboxEvents != nil {
		mmFetchUnprocessedOutboxEvents.inspectFuncFetchUnprocessedOutboxEvents(ctx, limit, attemptsLimit)
	}

	mm_params := StorageMockFetchUnprocessedOutboxEventsParams{ctx, limit, attemptsLimit}

	// Record call args
	mmFetchUnprocessedOutboxEvents.FetchUnprocessedOutboxEventsMock.mutex.Lock()
	mmFetchUnprocessedOutboxEvents.FetchUnprocessedOutboxEventsMock.callArgs = append(mmFetchUnprocessedOutboxEvents.FetchUnprocessedOutboxEventsMock.callArgs, &mm_params)
	mmFetchUnprocessedOutboxEvents.FetchUnprocessedOutboxEventsMock.mutex.Unlock()

	for _, e := range mmFetchUnprocessedOutboxEvents.FetchUnprocessedOutboxEventsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.oa1, e.results.err
		}
	}

	if mmFetchUnprocessedOutboxEvents.FetchUnprocessedOutboxEventsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmFetchUnprocessedOutboxEvents.FetchUnprocessedOutboxEventsMock.defaultExpectation.Counter, 1)
		mm_want := mmFetchUnprocessedOutboxEvents.FetchUnprocessedOutboxEventsMock.defaultExpectation.params
		mm_want_ptrs := mmFetchUnprocessedOutboxEvents.FetchUnprocessedOutboxEventsMock.defaultExpectation.paramPtrs

		mm_got := StorageMockFetchUnprocessedOutboxEventsParams{ctx, limit, attemptsLimit}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmFetchUnprocessedOutboxEvents.t.Errorf("StorageMock.FetchUnprocessedOutboxEvents got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmFetchUnprocessedOutboxEvents.FetchUnprocessedOutboxEventsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.limit != nil && !minimock.Equal(*mm_want_ptrs.limit, mm_got.limit) {
				mmFetchUnprocessedOutboxEvents.t.Errorf("StorageMock.FetchUnprocessedOutboxEvents got unexpected parameter limit, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmFetchUnprocessedOutboxEvents.FetchUnprocessedOutboxEventsMock.defaultExpectation.expectationOrigins.originLimit, *mm_want_ptrs.limit, mm_got.limit, minimock.Diff(*mm_want_ptrs.limit, mm_got.limit))
			}

			if mm_want_ptrs.attemptsLimit != nil && !minimock.Equal(*mm_want_ptrs.attemptsLimit, mm_got.attemptsLimit) {
				mmFetchUnprocessedOutboxEvents.t.Errorf("StorageMock.FetchUnprocessedOutboxEvents got unexpected parameter attemptsLimit, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmFetchUnprocessedOutboxEvents.FetchUnprocessedOutboxEventsMock.defaultExpectation.expectationOrigins.originAttemptsLimit, *mm_want_ptrs.attemptsLimit, mm_got.attemptsLimit, minimock.Diff(*mm_want_ptrs.attemptsLimit, mm_got.attemptsLimit))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmFetchUnprocessedOutboxEvents.t.Errorf("StorageMock.FetchUnprocessedOutboxEvents got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmFetchUnprocessedOutboxEvents.FetchUnprocessedOutboxEventsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmFetchUnprocessedOutboxEvents.FetchUnprocessedOutboxEventsMock.defaultExpectation.results
		if mm_results == nil {
			mmFetchUnprocessedOutboxEvents.t.Fatal("No results are set for the StorageMock.FetchUnprocessedOutboxEvents")
		}
		return (*mm_results).oa1, (*mm_results).err
	}
	if mmFetchUnprocessedOutboxEvents.funcFetchUnprocessedOutboxEvents != nil {
		return mmFetchUnprocessedOutboxEvents.funcFetchUnprocessedOutboxEvents(ctx, limit, attemptsLimit)
	}
	mmFetchUnprocessedOutboxEvents.t.Fatalf("Unexpected call to StorageMock.FetchUnprocessedOutboxEvents. %v %v %v", ctx, limit, attemptsLimit)
	return
}

// FetchUnprocessedOutboxEventsAfterCounter returns a count of finished StorageMock.FetchUnprocessedOutboxEvents invocations
func (mmFetchUnprocessedOutboxEvents *StorageMock) FetchUnprocessedOutboxEventsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFetchUnprocessedOutboxEvents.afterFetchUnprocessedOutboxEventsCounter)
}

// FetchUnprocessedOutboxEventsBeforeCounter returns a count of StorageMock.FetchUnprocessedOutboxEvents invocations
func (mmFetchUnprocessedOutboxEvents *StorageMock) FetchUnprocessedOutboxEventsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFetchUnprocessedOutboxEvents.beforeFetchUnprocessedOutboxEventsCounter)
}

// Calls returns a list of arguments used in each call to StorageMock.FetchUnprocessedOutboxEvents.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmFetchUnprocessedOutboxEvents *mStorageMockFetchUnprocessedOutboxEvents) Calls() []*StorageMockFetchUnprocessedOutboxEventsParams {
	mmFetchUnprocessedOutboxEvents.mutex.RLock()

	argCopy := make([]*StorageMockFetchUnprocessedOutboxEventsParams, len(mmFetchUnprocessedOutboxEvents.callArgs))
	copy(argCopy, mmFetchUnprocessedOutboxEvents.callArgs)

	mmFetchUnprocessedOutboxEvents.mutex.RUnlock()

	return argCopy
}

// MinimockFetchUnprocessedOutboxEventsDone returns true if the count of the FetchUnprocessedOutboxEvents invocations corresponds
// the number of defined expectations
func (m *StorageMock) MinimockFetchUnprocessedOutboxEventsDone() bool {
	if m.FetchUnprocessedOutboxEventsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.FetchUnprocessedOutboxEventsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.FetchUnprocessedOutboxEventsMock.invocationsDone()
}

// MinimockFetchUnprocessedOutboxEventsInspect logs each unmet expectation
func (m *StorageMock) MinimockFetchUnprocessedOutboxEventsInspect() {
	for _, e := range m.FetchUnprocessedOutboxEventsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageMock.FetchUnprocessedOutboxEvents at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterFetchUnprocessedOutboxEventsCounter := mm_atomic.LoadUint64(&m.afterFetchUnprocessedOutboxEventsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.FetchUnprocessedOutboxEventsMock.defaultExpectation != nil && afterFetchUnprocessedOutboxEventsCounter < 1 {
		if m.FetchUnprocessedOutboxEventsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageMock.FetchUnprocessedOutboxEvents at\n%s", m.FetchUnprocessedOutboxEventsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageMock.FetchUnprocessedOutboxEvents at\n%s with params: %#v", m.FetchUnprocessedOutboxEventsMock.defaultExpectation.expectationOrigins.origin, *m.FetchUnprocessedOutboxEventsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcFetchUnprocessedOutboxEvents != nil && afterFetchUnprocessedOutboxEventsCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.FetchUnprocessedOutboxEvents at\n%s", m.funcFetchUnprocessedOutboxEventsOrigin)
	}

	if !m.FetchUnprocessedOutboxEventsMock.invocationsDone() && afterFetchUnprocessedOutboxEventsCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageMock.FetchUnprocessedOutboxEvents at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.FetchUnprocessedOutboxEventsMock.expectedInvocations), m.FetchUnprocessedOutboxEventsMock.expectedInvocationsOrigin, afterFetchUnprocessedOutboxEventsCounter)
	}
}

type mStorageMockMarkOutboxEventFailed struct {
	optional           bool
	mock               *StorageMock
	defaultExpectation *StorageMockMarkOutboxEventFailedExpectation
	expectations       []*StorageMockMarkOutboxEventFailedExpectation

	callArgs []*StorageMockMarkOutboxEventFailedParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageMockMarkOutboxEventFailedExpectation specifies expectation struct of the Storage.MarkOutboxEventFailed
type StorageMockMarkOutboxEventFailedExpectation struct {
	mock               *StorageMock
	params             *StorageMockMarkOutboxEventFailedParams
	paramPtrs          *StorageMockMarkOutboxEventFailedParamPtrs
	expectationOrigins StorageMockMarkOutboxEventFailedExpectationOrigins
	results            *StorageMockMarkOutboxEventFailedResults
	returnOrigin       string
	Counter            uint64
}

// StorageMockMarkOutboxEventFailedParams contains parameters of the Storage.MarkOutboxEventFailed
type StorageMockMarkOutboxEventFailedParams struct {
	ctx    context.Context
	id     string
	errMsg string
}

// StorageMockMarkOutboxEventFailedParamPtrs contains pointers to parameters of the Storage.MarkOutboxEventFailed
type StorageMockMarkOutboxEventFailedParamPtrs struct {
	ctx    *context.Context
	id     *string
	errMsg *string
}

// StorageMockMarkOutboxEventFailedResults contains results of the Storage.MarkOutboxEventFailed
type StorageMockMarkOutboxEventFailedResults struct {
	err error
}

// StorageMockMarkOutboxEventFailedOrigins contains origins of expectations of the Storage.MarkOutboxEventFailed
type StorageMockMarkOutboxEventFailedExpectationOrigins struct {
	origin       string
	originCtx    string
	originId     string
	originErrMsg string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmMarkOutboxEventFailed *mStorageMockMarkOutboxEventFailed) Optional() *mStorageMockMarkOutboxEventFailed {
	mmMarkOutboxEventFailed.optional = true
	return mmMarkOutboxEventFailed
}

// Expect sets up expected params for Storage.MarkOutboxEventFailed
func (mmMarkOutboxEventFailed *mStorageMockMarkOutboxEventFailed) Expect(ctx context.Context, id string, errMsg string) *mStorageMockMarkOutboxEventFailed {
	if mmMarkOutboxEventFailed.mock.funcMarkOutboxEventFailed != nil {
		mmMarkOutboxEventFailed.mock.t.Fatalf("StorageMock.MarkOutboxEventFailed mock is already set by Set")
	}

	if mmMarkOutboxEventFailed.defaultExpectation == nil {
		mmMarkOutboxEventFailed.defaultExpectation = &StorageMockMarkOutboxEventFailedExpectation{}
	}

	if mmMarkOutboxEventFailed.defaultExpectation.paramPtrs != nil {
		mmMarkOutboxEventFailed.mock.t.Fatalf("StorageMock.MarkOutboxEventFailed mock is already set by ExpectParams functions")
	}

	mmMarkOutboxEventFailed.defaultExpectation.params = &StorageMockMarkOutboxEventFailedParams{ctx, id, errMsg}
	mmMarkOutboxEventFailed.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmMarkOutboxEventFailed.expectations {
		if minimock.Equal(e.params, mmMarkOutboxEventFailed.defaultExpectation.params) {
			mmMarkOutboxEventFailed.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmMarkOutboxEventFailed.defaultExpectation.params)
		}
	}

	return mmMarkOutboxEventFailed
}

// ExpectCtxParam1 sets up expected param ctx for Storage.MarkOutboxEventFailed
func (mmMarkOutboxEventFailed *mStorageMockMarkOutboxEventFailed) ExpectCtxParam1(ctx context.Context) *mStorageMockMarkOutboxEventFailed {
	if mmMarkOutboxEventFailed.mock.funcMarkOutboxEventFailed != nil {
		mmMarkOutboxEventFailed.mock.t.Fatalf("StorageMock.MarkOutboxEventFailed mock is already set by Set")
	}

	if mmMarkOutboxEventFailed.defaultExpectation == nil {
		mmMarkOutboxEventFailed.defaultExpectation = &StorageMockMarkOutboxEventFailedExpectation{}
	}

	if mmMarkOutboxEventFailed.defaultExpectation.params != nil {
		mmMarkOutboxEventFailed.mock.t.Fatalf("StorageMock.MarkOutboxEventFailed mock is already set by Expect")
	}

	if mmMarkOutboxEventFailed.defaultExpectation.paramPtrs == nil {
		mmMarkOutboxEventFailed.defaultExpectation.paramPtrs = &StorageMockMarkOutboxEventFailedParamPtrs{}
	}
	mmMarkOutboxEventFailed.defaultExpectation.paramPtrs.ctx = &ctx
	mmMarkOutboxEventFailed.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmMarkOutboxEventFailed
}

// ExpectIdParam2 sets up expected param id for Storage.MarkOutboxEventFailed
func (mmMarkOutboxEventFailed *mStorageMockMarkOutboxEventFailed) ExpectIdParam2(id string) *mStorageMockMarkOutboxEventFailed {
	if mmMarkOutboxEventFailed.mock.funcMarkOutboxEventFailed != nil {
		mmMarkOutboxEventFailed.mock.t.Fatalf("StorageMock.MarkOutboxEventFailed mock is already set by Set")
	}

	if mmMarkOutboxEventFailed.defaultExpectation == nil {
		mmMarkOutboxEventFailed.defaultExpectation = &StorageMockMarkOutboxEventFailedExpectation{}
	}

	if mmMarkOutboxEventFailed.defaultExpectation.params != nil {
		mmMarkOutboxEventFailed.mock.t.Fatalf("StorageMock.MarkOutboxEventFailed mock is already set by Expect")
	}

	if mmMarkOutboxEventFailed.defaultExpectation.paramPtrs == nil {
		mmMarkOutboxEventFailed.defaultExpectation.paramPtrs = &StorageMockMarkOutboxEventFailedParamPtrs{}
	}
	mmMarkOutboxEventFailed.defaultExpectation.paramPtrs.id = &id
	mmMarkOutboxEventFailed.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmMarkOutboxEventFailed
}

// ExpectErrMsgParam3 sets up expected param errMsg for Storage.MarkOutboxEventFailed
func (mmMarkOutboxEventFailed *mStorageMockMarkOutboxEventFailed) ExpectErrMsgParam3(errMsg string) *mStorageMockMarkOutboxEventFailed {
	if mmMarkOutboxEventFailed.mock.funcMarkOutboxEventFailed != nil {
		mmMarkOutboxEventFailed.mock.t.Fatalf("StorageMock.MarkOutboxEventFailed mock is already set by Set")
	}

	if mmMarkOutboxEventFailed.defaultExpectation == nil {
		mmMarkOutboxEventFailed.defaultExpectation = &StorageMockMarkOutboxEventFailedExpectation{}
	}

	if mmMarkOutboxEventFailed.defaultExpectation.params != nil {
		mmMarkOutboxEventFailed.mock.t.Fatalf("StorageMock.MarkOutboxEventFailed mock is already set by Expect")
	}

	if mmMarkOutboxEventFailed.defaultExpectation.paramPtrs == nil {
		mmMarkOutboxEventFailed.defaultExpectation.paramPtrs = &StorageMockMarkOutboxEventFailedParamPtrs{}
	}
	mmMarkOutboxEventFailed.defaultExpectation.paramPtrs.errMsg = &errMsg
	mmMarkOutboxEventFailed.defaultExpectation.expectationOrigins.originErrMsg = minimock.CallerInfo(1)

	return mmMarkOutboxEventFailed
}

// Inspect accepts an inspector function that has same arguments as the Storage.MarkOutboxEventFailed
func (mmMarkOutboxEventFailed *mStorageMockMarkOutboxEventFailed) Inspect(f func(ctx context.Context, id string, errMsg string)) *mStorageMockMarkOutboxEventFailed {
	if mmMarkOutboxEventFailed.mock.inspectFuncMarkOutboxEventFailed != nil {
		mmMarkOutboxEventFailed.mock.t.Fatalf("Inspect function is already set for StorageMock.MarkOutboxEventFailed")
	}

	mmMarkOutboxEventFailed.mock.inspectFuncMarkOutboxEventFailed = f

	return mmMarkOutboxEventFailed
}

// Return sets up results that will be returned by Storage.MarkOutboxEventFailed
func (mmMarkOutboxEventFailed *mStorageMockMarkOutboxEventFailed) Return(err error) *StorageMock {
	if mmMarkOutboxEventFailed.mock.funcMarkOutboxEventFailed != nil {
		mmMarkOutboxEventFailed.mock.t.Fatalf("StorageMock.MarkOutboxEventFailed mock is already set by Set")
	}

	if mmMarkOutboxEventFailed.defaultExpectation == nil {
		mmMarkOutboxEventFailed.defaultExpectation = &StorageMockMarkOutboxEventFailedExpectation{mock: mmMarkOutboxEventFailed.mock}
	}
	mmMarkOutboxEventFailed.defaultExpectation.results = &StorageMockMarkOutboxEventFailedResults{err}
	mmMarkOutboxEventFailed.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmMarkOutboxEventFailed.mock
}

// Set uses given function f to mock the Storage.MarkOutboxEventFailed method
func (mmMarkOutboxEventFailed *mStorageMockMarkOutboxEventFailed) Set(f func(ctx context.Context, id string, errMsg string) (err error)) *StorageMock {
	if mmMarkOutboxEventFailed.defaultExpectation != nil {
		mmMarkOutboxEventFailed.mock.t.Fatalf("Default expectation is already set for the Storage.MarkOutboxEventFailed method")
	}

	if len(mmMarkOutboxEventFailed.expectations) > 0 {
		mmMarkOutboxEventFailed.mock.t.Fatalf("Some expectations are already set for the Storage.MarkOutboxEventFailed method")
	}

	mmMarkOutboxEventFailed.mock.funcMarkOutboxEventFailed = f
	mmMarkOutboxEventFailed.mock.funcMarkOutboxEventFailedOrigin = minimock.CallerInfo(1)
	return mmMarkOutboxEventFailed.mock
}

// When sets expectation for the Storage.MarkOutboxEventFailed which will trigger the result defined by the following
// Then helper
func (mmMarkOutboxEventFailed *mStorageMockMarkOutboxEventFailed) When(ctx context.Context, id string, errMsg string) *StorageMockMarkOutboxEventFailedExpectation {
	if mmMarkOutboxEventFailed.mock.funcMarkOutboxEventFailed != nil {
		mmMarkOutboxEventFailed.mock.t.Fatalf("StorageMock.MarkOutboxEventFailed mock is already set by Set")
	}

	expectation := &StorageMockMarkOutboxEventFailedExpectation{
		mock:               mmMarkOutboxEventFailed.mock,
		params:             &StorageMockMarkOutboxEventFailedParams{ctx, id, errMsg},
		expectationOrigins: StorageMockMarkOutboxEventFailedExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmMarkOutboxEventFailed.expectations = append(mmMarkOutboxEventFailed.expectations, expectation)
	return expectation
}

// Then sets up Storage.MarkOutboxEventFailed return parameters for the expectation previously defined by the When method
func (e *StorageMockMarkOutboxEventFailedExpectation) Then(err error) *StorageMock {
	e.results = &StorageMockMarkOutboxEventFailedResults{err}
	return e.mock
}

// Times sets number of times Storage.MarkOutboxEventFailed should be invoked
func (mmMarkOutboxEventFailed *mStorageMockMarkOutboxEventFailed) Times(n uint64) *mStorageMockMarkOutboxEventFailed {
	if n == 0 {
		mmMarkOutboxEventFailed.mock.t.Fatalf("Times of StorageMock.MarkOutboxEventFailed mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmMarkOutboxEventFailed.expectedInvocations, n)
	mmMarkOutboxEventFailed.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmMarkOutboxEventFailed
}

func (mmMarkOutboxEventFailed *mStorageMockMarkOutboxEventFailed) invocationsDone() bool {
	if len(mmMarkOutboxEventFailed.expectations) == 0 && mmMarkOutboxEventFailed.defaultExpectation == nil && mmMarkOutboxEventFailed.mock.funcMarkOutboxEventFailed == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmMarkOutboxEventFailed.mock.afterMarkOutboxEventFailedCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmMarkOutboxEventFailed.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// MarkOutboxEventFailed implements mm_workers.Storage
func (mmMarkOutboxEventFailed *StorageMock) MarkOutboxEventFailed(ctx context.Context, id string, errMsg string) (err error) {
	mm_atomic.AddUint64(&mmMarkOutboxEventFailed.beforeMarkOutboxEventFailedCounter, 1)
	defer mm_atomic.AddUint64(&mmMarkOutboxEventFailed.afterMarkOutboxEventFailedCounter, 1)

	mmMarkOutboxEventFailed.t.Helper()

	if mmMarkOutboxEventFailed.inspectFuncMarkOutboxEventFailed != nil {
		mmMarkOutboxEventFailed.inspectFuncMarkOutboxEventFailed(ctx, id, errMsg)
	}

	mm_params := StorageMockMarkOutboxEventFailedParams{ctx, id, errMsg}

	// Record call args
	mmMarkOutboxEventFailed.MarkOutboxEventFailedMock.mutex.Lock()
	mmMarkOutboxEventFailed.MarkOutboxEventFailedMock.callArgs = append(mmMarkOutboxEventFailed.MarkOutboxEventFailedMock.callArgs, &mm_params)
	mmMarkOutboxEventFailed.MarkOutboxEventFailedMock.mutex.Unlock()

	for _, e := range mmMarkOutboxEventFailed.MarkOutboxEventFailedMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmMarkOutboxEventFailed.MarkOutboxEventFailedMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmMarkOutboxEventFailed.MarkOutboxEventFailedMock.defaultExpectation.Counter, 1)
		mm_want := mmMarkOutboxEventFailed.MarkOutboxEventFailedMock.defaultExpectation.params
		mm_want_ptrs := mmMarkOutboxEventFailed.MarkOutboxEventFailedMock.defaultExpectation.paramPtrs

		mm_got := StorageMockMarkOutboxEventFailedParams{ctx, id, errMsg}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmMarkOutboxEventFailed.t.Errorf("StorageMock.MarkOutboxEventFailed got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmMarkOutboxEventFailed.MarkOutboxEventFailedMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmMarkOutboxEventFailed.t.Errorf("StorageMock.MarkOutboxEventFailed got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmMarkOutboxEventFailed.MarkOutboxEventFailedMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

			if mm_want_ptrs.errMsg != nil && !minimock.Equal(*mm_want_ptrs.errMsg, mm_got.errMsg) {
				mmMarkOutboxEventFailed.t.Errorf("StorageMock.MarkOutboxEventFailed got unexpected parameter errMsg, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmMarkOutboxEventFailed.MarkOutboxEventFailedMock.defaultExpectation.expectationOrigins.originErrMsg, *mm_want_ptrs.errMsg, mm_got.errMsg, minimock.Diff(*mm_want_ptrs.errMsg, mm_got.errMsg))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmMarkOutboxEventFailed.t.Errorf("StorageMock.MarkOutboxEventFailed got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmMarkOutboxEventFailed.MarkOutboxEventFailedMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmMarkOutboxEventFailed.MarkOutboxEventFailedMock.defaultExpectation.results
		if mm_results == nil {
			mmMarkOutboxEventFailed.t.Fatal("No results are set for the StorageMock.MarkOutboxEventFailed")
		}
		return (*mm_results).err
	}
	if mmMarkOutboxEventFailed.funcMarkOutboxEventFailed != nil {
		return mmMarkOutboxEventFailed.funcMarkOutboxEventFailed(ctx, id, errMsg)
	}
	mmMarkOutboxEventFailed.t.Fatalf("Unexpected call to StorageMock.MarkOutboxEventFailed. %v %v %v", ctx, id, errMsg)
	return
}

// MarkOutboxEventFailedAfterCounter returns a count of finished StorageMock.MarkOutboxEventFailed invocations
func (mmMarkOutboxEventFailed *StorageMock) MarkOutboxEventFailedAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmMarkOutboxEventFailed.afterMarkOutboxEventFailedCounter)
}

// MarkOutboxEventFailedBeforeCounter returns a count of StorageMock.MarkOutboxEventFailed invocations
func (mmMarkOutboxEventFailed *StorageMock) MarkOutboxEventFailedBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmMarkOutboxEventFailed.beforeMarkOutboxEventFailedCounter)
}

// Calls returns a list of arguments used in each call to StorageMock.MarkOutboxEventFailed.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmMarkOutboxEventFailed *mStorageMockMarkOutboxEventFailed) Calls() []*StorageMockMarkOutboxEventFailedParams {
	mmMarkOutboxEventFailed.mutex.RLock()

	argCopy := make([]*StorageMockMarkOutboxEventFailedParams, len(mmMarkOutboxEventFailed.callArgs))
	copy(argCopy, mmMarkOutboxEventFailed.callArgs)

	mmMarkOutboxEventFailed.mutex.RUnlock()

	return argCopy
}

// MinimockMarkOutboxEventFailedDone returns true if the count of the MarkOutboxEventFailed invocations corresponds
// the number of defined expectations
func (m *StorageMock) MinimockMarkOutboxEventFailedDone() bool {
	if m.MarkOutboxEventFailedMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.MarkOutboxEventFailedMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.MarkOutboxEventFailedMock.invocationsDone()
}

// MinimockMarkOutboxEventFailedInspect logs each unmet expectation
func (m *StorageMock) MinimockMarkOutboxEventFailedInspect() {
	for _, e := range m.MarkOutboxEventFailedMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageMock.MarkOutboxEventFailed at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterMarkOutboxEventFailedCounter := mm_atomic.LoadUint64(&m.afterMarkOutboxEventFailedCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.MarkOutboxEventFailedMock.defaultExpectation != nil && afterMarkOutboxEventFailedCounter < 1 {
		if m.MarkOutboxEventFailedMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageMock.MarkOutboxEventFailed at\n%s", m.MarkOutboxEventFailedMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageMock.MarkOutboxEventFailed at\n%s with params: %#v", m.MarkOutboxEventFailedMock.defaultExpectation.expectationOrigins.origin, *m.MarkOutboxEventFailedMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcMarkOutboxEventFailed != nil && afterMarkOutboxEventFailedCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.MarkOutboxEventFailed at\n%s", m.funcMarkOutboxEventFailedOrigin)
	}

	if !m.MarkOutboxEventFailedMock.invocationsDone() && afterMarkOutboxEventFailedCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageMock.MarkOutboxEventFailed at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.MarkOutboxEventFailedMock.expectedInvocations), m.MarkOutboxEventFailedMock.expectedInvocationsOrigin, afterMarkOutboxEventFailedCounter)
	}
}

type mStorageMockMarkOutboxEventProcessed struct {
	optional           bool
	mock               *StorageMock
	defaultExpectation *StorageMockMarkOutboxEventProcessedExpectation
	expectations       []*StorageMockMarkOutboxEventProcessedExpectation

	callArgs []*StorageMockMarkOutboxEventProcessedParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageMockMarkOutboxEventProcessedExpectation specifies expectation struct of the Storage.MarkOutboxEventProcessed
type StorageMockMarkOutboxEventProcessedExpectation struct {
	mock               *StorageMock
	params             *StorageMockMarkOutboxEventProcessedParams
	paramPtrs          *StorageMockMarkOutboxEventProcessedParamPtrs
	expectationOrigins StorageMockMarkOutboxEventProcessedExpectationOrigins
	results            *StorageMockMarkOutboxEventProcessedResults
	returnOrigin       string
	Counter            uint64
}

// StorageMockMarkOutboxEventProcessedParams contains parameters of the Storage.MarkOutboxEventProcessed
type StorageMockMarkOutboxEventProcessedParams struct {
	ctx context.Context
	id  string
}

// StorageMockMarkOutboxEventProcessedParamPtrs contains pointers to parameters of the Storage.MarkOutboxEventProcessed
type StorageMockMarkOutboxEventProcessedParamPtrs struct {
	ctx *context.Context
	id  *string
}

// StorageMockMarkOutboxEventProcessedResults contains results of the Storage.MarkOutboxEventProcessed
type StorageMockMarkOutboxEventProcessedResults struct {
	err error
}

// StorageMockMarkOutboxEventProcessedOrigins contains origins of expectations of the Storage.MarkOutboxEventProcessed
type StorageMockMarkOutboxEventProcessedExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmMarkOutboxEventProcessed *mStorageMockMarkOutboxEventProcessed) Optional() *mStorageMockMarkOutboxEventProcessed {
	mmMarkOutboxEventProcessed.optional = true
	return mmMarkOutboxEventProcessed
}

// Expect sets up expected params for Storage.MarkOutboxEventProcessed
func (mmMarkOutboxEventProcessed *mStorageMockMarkOutboxEventProcessed) Expect(ctx context.Context, id string) *mStorageMockMarkOutboxEventProcessed {
	if mmMarkOutboxEventProcessed.mock.funcMarkOutboxEventProcessed != nil {
		mmMarkOutboxEventProcessed.mock.t.Fatalf("StorageMock.MarkOutboxEventProcessed mock is already set by Set")
	}

	if mmMarkOutboxEventProcessed.defaultExpectation == nil {
		mmMarkOutboxEventProcessed.defaultExpectation = &StorageMockMarkOutboxEventProcessedExpectation{}
	}

	if mmMarkOutboxEventProcessed.defaultExpectation.paramPtrs != nil {
		mmMarkOutboxEventProcessed.mock.t.Fatalf("StorageMock.MarkOutboxEventProcessed mock is already set by ExpectParams functions")
	}

	mmMarkOutboxEventProcessed.defaultExpectation.params = &StorageMockMarkOutboxEventProcessedParams{ctx, id}
	mmMarkOutboxEventProcessed.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmMarkOutboxEventProcessed.expectations {
		if minimock.Equal(e.params, mmMarkOutboxEventProcessed.defaultExpectation.params) {
			mmMarkOutboxEventProcessed.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmMarkOutboxEventProcessed.defaultExpectation.params)
		}
	}

	return mmMarkOutboxEventProcessed
}

// ExpectCtxParam1 sets up expected param ctx for Storage.MarkOutboxEventProcessed
func (mmMarkOutboxEventProcessed *mStorageMockMarkOutboxEventProcessed) ExpectCtxParam1(ctx context.Context) *mStorageMockMarkOutboxEventProcessed {
	if mmMarkOutboxEventProcessed.mock.funcMarkOutboxEventProcessed != nil {
		mmMarkOutboxEventProcessed.mock.t.Fatalf("StorageMock.MarkOutboxEventProcessed mock is already set by Set")
	}

	if mmMarkOutboxEventProcessed.defaultExpectation == nil {
		mmMarkOutboxEventProcessed.defaultExpectation = &StorageMockMarkOutboxEventProcessedExpectation{}
	}

	if mmMarkOutboxEventProcessed.defaultExpectation.params != nil {
		mmMarkOutboxEventProcessed.mock.t.Fatalf("StorageMock.MarkOutboxEventProcessed mock is already set by Expect")
	}

	if mmMarkOutboxEventProcessed.defaultExpectation.paramPtrs == nil {
		mmMarkOutboxEventProcessed.defaultExpectation.paramPtrs = &StorageMockMarkOutboxEventProcessedParamPtrs{}
	}
	mmMarkOutboxEventProcessed.defaultExpectation.paramPtrs.ctx = &ctx
	mmMarkOutboxEventProcessed.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmMarkOutboxEventProcessed
}

// ExpectIdParam2 sets up expected param id for Storage.MarkOutboxEventProcessed
func (mmMarkOutboxEventProcessed *mStorageMockMarkOutboxEventProcessed) ExpectIdParam2(id string) *mStorageMockMarkOutboxEventProcessed {
	if mmMarkOutboxEventProcessed.mock.funcMarkOutboxEventProcessed != nil {
		mmMarkOutboxEventProcessed.mock.t.Fatalf("StorageMock.MarkOutboxEventProcessed mock is already set by Set")
	}

	if mmMarkOutboxEventProcessed.defaultExpectation == nil {
		mmMarkOutboxEventProcessed.defaultExpectation = &StorageMockMarkOutboxEventProcessedExpectation{}
	}

	if mmMarkOutboxEventProcessed.defaultExpectation.params != nil {
		mmMarkOutboxEventProcessed.mock.t.Fatalf("StorageMock.MarkOutboxEventProcessed mock is already set by Expect")
	}

	if mmMarkOutboxEventProcessed.defaultExpectation.paramPtrs == nil {
		mmMarkOutboxEventProcessed.defaultExpectation.paramPtrs = &StorageMockMarkOutboxEventProcessedParamPtrs{}
	}
	mmMarkOutboxEventProcessed.defaultExpectation.paramPtrs.id = &id
	mmMarkOutboxEventProcessed.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmMarkOutboxEventProcessed
}

// Inspect accepts an inspector function that has same arguments as the Storage.MarkOutboxEventProcessed
func (mmMarkOutboxEventProcessed *mStorageMockMarkOutboxEventProcessed) Inspect(f func(ctx context.Context, id string)) *mStorageMockMarkOutboxEventProcessed {
	if mmMarkOutboxEventProcessed.mock.inspectFuncMarkOutboxEventProcessed != nil {
		mmMarkOutboxEventProcessed.mock.t.Fatalf("Inspect function is already set for StorageMock.MarkOutboxEventProcessed")
	}

	mmMarkOutboxEventProcessed.mock.inspectFuncMarkOutboxEventProcessed = f

	return mmMarkOutboxEventProcessed
}

// Return sets up results that will be returned by Storage.MarkOutboxEventProcessed
func (mmMarkOutboxEventProcessed *mStorageMockMarkOutboxEventProcessed) Return(err error) *StorageMock {
	if mmMarkOutboxEventProcessed.mock.funcMarkOutboxEventProcessed != nil {
		mmMarkOutboxEventProcessed.mock.t.Fatalf("StorageMock.MarkOutboxEventProcessed mock is already set by Set")
	}

	if mmMarkOutboxEventProcessed.defaultExpectation == nil {
		mmMarkOutboxEventProcessed.defaultExpectation = &StorageMockMarkOutboxEventProcessedExpectation{mock: mmMarkOutboxEventProcessed.mock}
	}
	mmMarkOutboxEventProcessed.defaultExpectation.results = &StorageMockMarkOutboxEventProcessedResults{err}
	mmMarkOutboxEventProcessed.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmMarkOutboxEventProcessed.mock
}

// Set uses given function f to mock the Storage.MarkOutboxEventProcessed method
func (mmMarkOutboxEventProcessed *mStorageMockMarkOutboxEventProcessed) Set(f func(ctx context.Context, id string) (err error)) *StorageMock {
	if mmMarkOutboxEventProcessed.defaultExpectation != nil {
		mmMarkOutboxEventProcessed.mock.t.Fatalf("Default expectation is already set for the Storage.MarkOutboxEventProcessed method")
	}

	if len(mmMarkOutboxEventProcessed.expectations) > 0 {
		mmMarkOutboxEventProcessed.mock.t.Fatalf("Some expectations are already set for the Storage.MarkOutboxEventProcessed method")
	}

	mmMarkOutboxEventProcessed.mock.funcMarkOutboxEventProcessed = f
	mmMarkOutboxEventProcessed.mock.funcMarkOutboxEventProcessedOrigin = minimock.CallerInfo(1)
	return mmMarkOutboxEventProcessed.mock
}

// When sets expectation for the Storage.MarkOutboxEventProcessed which will trigger the result defined by the following
// Then helper
func (mmMarkOutboxEventProcessed *mStorageMockMarkOutboxEventProcessed) When(ctx context.Context, id string) *StorageMockMarkOutboxEventProcessedExpectation {
	if mmMarkOutboxEventProcessed.mock.funcMarkOutboxEventProcessed != nil {
		mmMarkOutboxEventProcessed.mock.t.Fatalf("StorageMock.MarkOutboxEventProcessed mock is already set by Set")
	}

	expectation := &StorageMockMarkOutboxEventProcessedExpectation{
		mock:               mmMarkOutboxEventProcessed.mock,
		params:             &StorageMockMarkOutboxEventProcessedParams{ctx, id},
		expectationOrigins: StorageMockMarkOutboxEventProcessedExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmMarkOutboxEventProcessed.expectations = append(mmMarkOutboxEventProcessed.expectations, expectation)
	return expectation
}

// Then sets up Storage.MarkOutboxEventProcessed return parameters for the expectation previously defined by the When method
func (e *StorageMockMarkOutboxEventProcessedExpectation) Then(err error) *StorageMock {
	e.results = &StorageMockMarkOutboxEventProcessedResults{err}
	return e.mock
}

// Times sets number of times Storage.MarkOutboxEventProcessed should be invoked
func (mmMarkOutboxEventProcessed *mStorageMockMarkOutboxEventProcessed) Times(n uint64) *mStorageMockMarkOutboxEventProcessed {
	if n == 0 {
		mmMarkOutboxEventProcessed.mock.t.Fatalf("Times of StorageMock.MarkOutboxEventProcessed mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmMarkOutboxEventProcessed.expectedInvocations, n)
	mmMarkOutboxEventProcessed.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmMarkOutboxEventProcessed
}

func (mmMarkOutboxEventProcessed *mStorageMockMarkOutboxEventProcessed) invocationsDone() bool {
	if len(mmMarkOutboxEventProcessed.expectations) == 0 && mmMarkOutboxEventProcessed.defaultExpectation == nil && mmMarkOutboxEventProcessed.mock.funcMarkOutboxEventProcessed == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmMarkOutboxEventProcessed.mock.afterMarkOutboxEventProcessedCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmMarkOutboxEventProcessed.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// MarkOutboxEventProcessed implements mm_workers.Storage
func (mmMarkOutboxEventProcessed *StorageMock) MarkOutboxEventProcessed(ctx context.Context, id string) (err error) {
	mm_atomic.AddUint64(&mmMarkOutboxEventProcessed.beforeMarkOutboxEventProcessedCounter, 1)
	defer mm_atomic.AddUint64(&mmMarkOutboxEventProcessed.afterMarkOutboxEventProcessedCounter, 1)

	mmMarkOutboxEventProcessed.t.Helper()

	if mmMarkOutboxEventProcessed.inspectFuncMarkOutboxEventProcessed != nil {
		mmMarkOutboxEventProcessed.inspectFuncMarkOutboxEventProcessed(ctx, id)
	}

	mm_params := StorageMockMarkOutboxEventProcessedParams{ctx, id}

	// Record call args
	mmMarkOutboxEventProcessed.MarkOutboxEventProcessedMock.mutex.Lock()
	mmMarkOutboxEventProcessed.MarkOutboxEventProcessedMock.callArgs = append(mmMarkOutboxEventProcessed.MarkOutboxEventProcessedMock.callArgs, &mm_params)
	mmMarkOutboxEventProcessed.MarkOutboxEventProcessedMock.mutex.Unlock()

	for _, e := range mmMarkOutboxEventProcessed.MarkOutboxEventProcessedMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmMarkOutboxEventProcessed.MarkOutboxEventProcessedMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmMarkOutboxEventProcessed.MarkOutboxEventProcessedMock.defaultExpectation.Counter, 1)
		mm_want := mmMarkOutboxEventProcessed.MarkOutboxEventProcessedMock.defaultExpectation.params
		mm_want_ptrs := mmMarkOutboxEventProcessed.MarkOutboxEventProcessedMock.defaultExpectation.paramPtrs

		mm_got := StorageMockMarkOutboxEventProcessedParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmMarkOutboxEventProcessed.t.Errorf("StorageMock.MarkOutboxEventProcessed got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmMarkOutboxEventProcessed.MarkOutboxEventProcessedMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmMarkOutboxEventProcessed.t.Errorf("StorageMock.MarkOutboxEventProcessed got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmMarkOutboxEventProcessed.MarkOutboxEventProcessedMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmMarkOutboxEventProcessed.t.Errorf("StorageMock.MarkOutboxEventProcessed got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmMarkOutboxEventProcessed.MarkOutboxEventProcessedMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmMarkOutboxEventProcessed.MarkOutboxEventProcessedMock.defaultExpectation.results
		if mm_results == nil {
			mmMarkOutboxEventProcessed.t.Fatal("No results are set for the StorageMock.MarkOutboxEventProcessed")
		}
		return (*mm_results).err
	}
	if mmMarkOutboxEventProcessed.funcMarkOutboxEventProcessed != nil {
		return mmMarkOutboxEventProcessed.funcMarkOutboxEventProcessed(ctx, id)
	}
	mmMarkOutboxEventProcessed.t.Fatalf("Unexpected call to StorageMock.MarkOutboxEventProcessed. %v %v", ctx, id)
	return
}

// MarkOutboxEventProcessedAfterCounter returns a count of finished StorageMock.MarkOutboxEventProcessed invocations
func (mmMarkOutboxEventProcessed *StorageMock) MarkOutboxEventProcessedAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmMarkOutboxEventProcessed.afterMarkOutboxEventProcessedCounter)
}

// MarkOutboxEventProcessedBeforeCounter returns a count of StorageMock.MarkOutboxEventProcessed invocations
func (mmMarkOutboxEventProcessed *StorageMock) MarkOutboxEventProcessedBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmMarkOutboxEventProcessed.beforeMarkOutboxEventProcessedCounter)
}

// Calls returns a list of arguments used in each call to StorageMock.MarkOutboxEventProcessed.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmMarkOutboxEventProcessed *mStorageMockMarkOutboxEventProcessed) Calls() []*StorageMockMarkOutboxEventProcessedParams {
	mmMarkOutboxEventProcessed.mutex.RLock()

	argCopy := make([]*StorageMockMarkOutboxEventProcessedParams, len(mmMarkOutboxEventProcessed.callArgs))
	copy(argCopy, mmMarkOutboxEventProcessed.callArgs)

	mmMarkOutboxEventProcessed.mutex.RUnlock()

	return argCopy
}

// MinimockMarkOutboxEventProcessedDone returns true if the count of the MarkOutboxEventProcessed invocations corresponds
// the number of defined expectations
func (m *StorageMock) MinimockMarkOutboxEventProcessedDone() bool {
	if m.MarkOutboxEventProcessedMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.MarkOutboxEventProcessedMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.MarkOutboxEventProcessedMock.invocationsDone()
}

// MinimockMarkOutboxEventProcessedInspect logs each unmet expectation
func (m *StorageMock) MinimockMarkOutboxEventProcessedInspect() {
	for _, e := range m.MarkOutboxEventProcessedMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageMock.MarkOutboxEventProcessed at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterMarkOutboxEventProcessedCounter := mm_atomic.LoadUint64(&m.afterMarkOutboxEventProcessedCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.MarkOutboxEventProcessedMock.defaultExpectation != nil && afterMarkOutboxEventProcessedCounter < 1 {
		if m.MarkOutboxEventProcessedMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageMock.MarkOutboxEventProcessed at\n%s", m.MarkOutboxEventProcessedMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageMock.MarkOutboxEventProcessed at\n%s with params: %#v", m.MarkOutboxEventProcessedMock.defaultExpectation.expectationOrigins.origin, *m.MarkOutboxEventProcessedMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcMarkOutboxEventProcessed != nil && afterMarkOutboxEventProcessedCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.MarkOutboxEventProcessed at\n%s", m.funcMarkOutboxEventProcessedOrigin)
	}

	if !m.MarkOutboxEventProcessedMock.invocationsDone() && afterMarkOutboxEventProcessedCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageMock.MarkOutboxEventProcessed at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.MarkOutboxEventProcessedMock.expectedInvocations), m.MarkOutboxEventProcessedMock.expectedInvocationsOrigin, afterMarkOutboxEventProcessedCounter)
	}
}

type mStorageMockSaveOutboxEvent struct {
	optional           bool
	mock               *StorageMock
	defaultExpectation *StorageMockSaveOutboxEventExpectation
	expectations       []*StorageMockSaveOutboxEventExpectation

	callArgs []*StorageMockSaveOutboxEventParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageMockSaveOutboxEventExpectation specifies expectation struct of the Storage.SaveOutboxEvent
type StorageMockSaveOutboxEventExpectation struct {
	mock               *StorageMock
	params             *StorageMockSaveOutboxEventParams
	paramPtrs          *StorageMockSaveOutboxEventParamPtrs
	expectationOrigins StorageMockSaveOutboxEventExpectationOrigins
	results            *StorageMockSaveOutboxEventResults
	returnOrigin       string
	Counter            uint64
}

// StorageMockSaveOutboxEventParams contains parameters of the Storage.SaveOutboxEvent
type StorageMockSaveOutboxEventParams struct {
	ctx       context.Context
	eventType string
	payload   any
}

// StorageMockSaveOutboxEventParamPtrs contains pointers to parameters of the Storage.SaveOutboxEvent
type StorageMockSaveOutboxEventParamPtrs struct {
	ctx       *context.Context
	eventType *string
	payload   *any
}

// StorageMockSaveOutboxEventResults contains results of the Storage.SaveOutboxEvent
type StorageMockSaveOutboxEventResults struct {
	err error
}

// StorageMockSaveOutboxEventOrigins contains origins of expectations of the Storage.SaveOutboxEvent
type StorageMockSaveOutboxEventExpectationOrigins struct {
	origin          string
	originCtx       string
	originEventType string
	originPayload   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSaveOutboxEvent *mStorageMockSaveOutboxEvent) Optional() *mStorageMockSaveOutboxEvent {
	mmSaveOutboxEvent.optional = true
	return mmSaveOutboxEvent
}

// Expect sets up expected params for Storage.SaveOutboxEvent
func (mmSaveOutboxEvent *mStorageMockSaveOutboxEvent) Expect(ctx context.Context, eventType string, payload any) *mStorageMockSaveOutboxEvent {
	if mmSaveOutboxEvent.mock.funcSaveOutboxEvent != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("StorageMock.SaveOutboxEvent mock is already set by Set")
	}

	if mmSaveOutboxEvent.defaultExpectation == nil {
		mmSaveOutboxEvent.defaultExpectation = &StorageMockSaveOutboxEventExpectation{}
	}

	if mmSaveOutboxEvent.defaultExpectation.paramPtrs != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("StorageMock.SaveOutboxEvent mock is already set by ExpectParams functions")
	}

	mmSaveOutboxEvent.defaultExpectation.params = &StorageMockSaveOutboxEventParams{ctx, eventType, payload}
	mmSaveOutboxEvent.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSaveOutboxEvent.expectations {
		if minimock.Equal(e.params, mmSaveOutboxEvent.defaultExpectation.params) {
			mmSaveOutboxEvent.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSaveOutboxEvent.defaultExpectation.params)
		}
	}

	return mmSaveOutboxEvent
}

// ExpectCtxParam1 sets up expected param ctx for Storage.SaveOutboxEvent
func (mmSaveOutboxEvent *mStorageMockSaveOutboxEvent) ExpectCtxParam1(ctx context.Context) *mStorageMockSaveOutboxEvent {
	if mmSaveOutboxEvent.mock.funcSaveOutboxEvent != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("StorageMock.SaveOutboxEvent mock is already set by Set")
	}

	if mmSaveOutboxEvent.defaultExpectation == nil {
		mmSaveOutboxEvent.defaultExpectation = &StorageMockSaveOutboxEventExpectation{}
	}

	if mmSaveOutboxEvent.defaultExpectation.params != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("StorageMock.SaveOutboxEvent mock is already set by Expect")
	}

	if mmSaveOutboxEvent.defaultExpectation.paramPtrs == nil {
		mmSaveOutboxEvent.defaultExpectation.paramPtrs = &StorageMockSaveOutboxEventParamPtrs{}
	}
	mmSaveOutboxEvent.defaultExpectation.paramPtrs.ctx = &ctx
	mmSaveOutboxEvent.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSaveOutboxEvent
}

// ExpectEventTypeParam2 sets up expected param eventType for Storage.SaveOutboxEvent
func (mmSaveOutboxEvent *mStorageMockSaveOutboxEvent) ExpectEventTypeParam2(eventType string) *mStorageMockSaveOutboxEvent {
	if mmSaveOutboxEvent.mock.funcSaveOutboxEvent != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("StorageMock.SaveOutboxEvent mock is already set by Set")
	}

	if mmSaveOutboxEvent.defaultExpectation == nil {
		mmSaveOutboxEvent.defaultExpectation = &StorageMockSaveOutboxEventExpectation{}
	}

	if mmSaveOutboxEvent.defaultExpectation.params != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("StorageMock.SaveOutboxEvent mock is already set by Expect")
	}

	if mmSaveOutboxEvent.defaultExpectation.paramPtrs == nil {
		mmSaveOutboxEvent.defaultExpectation.paramPtrs = &StorageMockSaveOutboxEventParamPtrs{}
	}
	mmSaveOutboxEvent.defaultExpectation.paramPtrs.eventType = &eventType
	mmSaveOutboxEvent.defaultExpectation.expectationOrigins.originEventType = minimock.CallerInfo(1)

	return mmSaveOutboxEvent
}

// ExpectPayloadParam3 sets up expected param payload for Storage.SaveOutboxEvent
func (mmSaveOutboxEvent *mStorageMockSaveOutboxEvent) ExpectPayloadParam3(payload any) *mStorageMockSaveOutboxEvent {
	if mmSaveOutboxEvent.mock.funcSaveOutboxEvent != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("StorageMock.SaveOutboxEvent mock is already set by Set")
	}

	if mmSaveOutboxEvent.defaultExpectation == nil {
		mmSaveOutboxEvent.defaultExpectation = &StorageMockSaveOutboxEventExpectation{}
	}

	if mmSaveOutboxEvent.defaultExpectation.params != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("StorageMock.SaveOutboxEvent mock is already set by Expect")
	}

	if mmSaveOutboxEvent.defaultExpectation.paramPtrs == nil {
		mmSaveOutboxEvent.defaultExpectation.paramPtrs = &StorageMockSaveOutboxEventParamPtrs{}
	}
	mmSaveOutboxEvent.defaultExpectation.paramPtrs.payload = &payload
	mmSaveOutboxEvent.defaultExpectation.expectationOrigins.originPayload = minimock.CallerInfo(1)

	return mmSaveOutboxEvent
}

// Inspect accepts an inspector function that has same arguments as the Storage.SaveOutboxEvent
func (mmSaveOutboxEvent *mStorageMockSaveOutboxEvent) Inspect(f func(ctx context.Context, eventType string, payload any)) *mStorageMockSaveOutboxEvent {
	if mmSaveOutboxEvent.mock.inspectFuncSaveOutboxEvent != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("Inspect function is already set for StorageMock.SaveOutboxEvent")
	}

	mmSaveOutboxEvent.mock.inspectFuncSaveOutboxEvent = f

	return mmSaveOutboxEvent
}

// Return sets up results that will be returned by Storage.SaveOutboxEvent
func (mmSaveOutboxEvent *mStorageMockSaveOutboxEvent) Return(err error) *StorageMock {
	if mmSaveOutboxEvent.mock.funcSaveOutboxEvent != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("StorageMock.SaveOutboxEvent mock is already set by Set")
	}

	if mmSaveOutboxEvent.defaultExpectation == nil {
		mmSaveOutboxEvent.defaultExpectation = &StorageMockSaveOutboxEventExpectation{mock: mmSaveOutboxEvent.mock}
	}
	mmSaveOutboxEvent.defaultExpectation.results = &StorageMockSaveOutboxEventResults{err}
	mmSaveOutboxEvent.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSaveOutboxEvent.mock
}

// Set uses given function f to mock the Storage.SaveOutboxEvent method
func (mmSaveOutboxEvent *mStorageMockSaveOutboxEvent) Set(f func(ctx context.Context, eventType string, payload any) (err error)) *StorageMock {
	if mmSaveOutboxEvent.defaultExpectation != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("Default expectation is already set for the Storage.SaveOutboxEvent method")
	}

	if len(mmSaveOutboxEvent.expectations) > 0 {
		mmSaveOutboxEvent.mock.t.Fatalf("Some expectations are already set for the Storage.SaveOutboxEvent method")
	}

	mmSaveOutboxEvent.mock.funcSaveOutboxEvent = f
	mmSaveOutboxEvent.mock.funcSaveOutboxEventOrigin = minimock.CallerInfo(1)
	return mmSaveOutboxEvent.mock
}

// When sets expectation for the Storage.SaveOutboxEvent which will trigger the result defined by the following
// Then helper
func (mmSaveOutboxEvent *mStorageMockSaveOutboxEvent) When(ctx context.Context, eventType string, payload any) *StorageMockSaveOutboxEventExpectation {
	if mmSaveOutboxEvent.mock.funcSaveOutboxEvent != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("StorageMock.SaveOutboxEvent mock is already set by Set")
	}

	expectation := &StorageMockSaveOutboxEventExpectation{
		mock:               mmSaveOutboxEvent.mock,
		params:             &StorageMockSaveOutboxEventParams{ctx, eventType, payload},
		expectationOrigins: StorageMockSaveOutboxEventExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSaveOutboxEvent.expectations = append(mmSaveOutboxEvent.expectations, expectation)
	return expectation
}

// Then sets up Storage.SaveOutboxEvent return parameters for the expectation previously defined by the When method
func (e *StorageMockSaveOutboxEventExpectation) Then(err error) *StorageMock {
	e.results = &StorageMockSaveOutboxEventResults{err}
	return e.mock
}

// Times sets number of times Storage.SaveOutboxEvent should be invoked
func (mmSaveOutboxEvent *mStorageMockSaveOutboxEvent) Times(n uint64) *mStorageMockSaveOutboxEvent {
	if n == 0 {
		mmSaveOutboxEvent.mock.t.Fatalf("Times of StorageMock.SaveOutboxEvent mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSaveOutboxEvent.expectedInvocations, n)
	mmSaveOutboxEvent.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSaveOutboxEvent
}

func (mmSaveOutboxEvent *mStorageMockSaveOutboxEvent) invocationsDone() bool {
	if len(mmSaveOutboxEvent.expectations) == 0 && mmSaveOutboxEvent.defaultExpectation == nil && mmSaveOutboxEvent.mock.funcSaveOutboxEvent == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSaveOutboxEvent.mock.afterSaveOutboxEventCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSaveOutboxEvent.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SaveOutboxEvent implements mm_workers.Storage
func (mmSaveOutboxEvent *StorageMock) SaveOutboxEvent(ctx context.Context, eventType string, payload any) (err error) {
	mm_atomic.AddUint64(&mmSaveOutboxEvent.beforeSaveOutboxEventCounter, 1)
	defer mm_atomic.AddUint64(&mmSaveOutboxEvent.afterSaveOutboxEventCounter, 1)

	mmSaveOutboxEvent.t.Helper()

	if mmSaveOutboxEvent.inspectFuncSaveOutboxEvent != nil {
		mmSaveOutboxEvent.inspectFuncSaveOutboxEvent(ctx, eventType, payload)
	}

	mm_params := StorageMockSaveOutboxEventParams{ctx, eventType, payload}

	// Record call args
	mmSaveOutboxEvent.SaveOutboxEventMock.mutex.Lock()
	mmSaveOutboxEvent.SaveOutboxEventMock.callArgs = append(mmSaveOutboxEvent.SaveOutboxEventMock.callArgs, &mm_params)
	mmSaveOutboxEvent.SaveOutboxEventMock.mutex.Unlock()

	for _, e := range mmSaveOutboxEvent.SaveOutboxEventMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSaveOutboxEvent.SaveOutboxEventMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSaveOutboxEvent.SaveOutboxEventMock.defaultExpectation.Counter, 1)
		mm_want := mmSaveOutboxEvent.SaveOutboxEventMock.defaultExpectation.params
		mm_want_ptrs := mmSaveOutboxEvent.SaveOutboxEventMock.defaultExpectation.paramPtrs

		mm_got := StorageMockSaveOutboxEventParams{ctx, eventType, payload}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSaveOutboxEvent.t.Errorf("StorageMock.SaveOutboxEvent got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveOutboxEvent.SaveOutboxEventMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.eventType != nil && !minimock.Equal(*mm_want_ptrs.eventType, mm_got.eventType) {
				mmSaveOutboxEvent.t.Errorf("StorageMock.SaveOutboxEvent got unexpected parameter eventType, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveOutboxEvent.SaveOutboxEventMock.defaultExpectation.expectationOrigins.originEventType, *mm_want_ptrs.eventType, mm_got.eventType, minimock.Diff(*mm_want_ptrs.eventType, mm_got.eventType))
			}

			if mm_want_ptrs.payload != nil && !minimock.Equal(*mm_want_ptrs.payload, mm_got.payload) {
				mmSaveOutboxEvent.t.Errorf("StorageMock.SaveOutboxEvent got unexpected parameter payload, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveOutboxEvent.SaveOutboxEventMock.defaultExpectation.expectationOrigins.originPayload, *mm_want_ptrs.payload, mm_got.payload, minimock.Diff(*mm_want_ptrs.payload, mm_got.payload))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSaveOutboxEvent.t.Errorf("StorageMock.SaveOutboxEvent got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSaveOutboxEvent.SaveOutboxEventMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSaveOutboxEvent.SaveOutboxEventMock.defaultExpectation.results
		if mm_results == nil {
			mmSaveOutboxEvent.t.Fatal("No results are set for the StorageMock.SaveOutboxEvent")
		}
		return (*mm_results).err
	}
	if mmSaveOutboxEvent.funcSaveOutboxEvent != nil {
		return mmSaveOutboxEvent.funcSaveOutboxEvent(ctx, eventType, payload)
	}
	mmSaveOutboxEvent.t.Fatalf("Unexpected call to StorageMock.SaveOutboxEvent. %v %v %v", ctx, eventType, payload)
	return
}

// SaveOutboxEventAfterCounter returns a count of finished StorageMock.SaveOutboxEvent invocations
func (mmSaveOutboxEvent *StorageMock) SaveOutboxEventAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveOutboxEvent.afterSaveOutboxEventCounter)
}

// SaveOutboxEventBeforeCounter returns a count of StorageMock.SaveOutboxEvent invocations
func (mmSaveOutboxEvent *StorageMock) SaveOutboxEventBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveOutboxEvent.beforeSaveOutboxEventCounter)
}

// Calls returns a list of arguments used in each call to StorageMock.SaveOutboxEvent.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSaveOutboxEvent *mStorageMockSaveOutboxEvent) Calls() []*StorageMockSaveOutboxEventParams {
	mmSaveOutboxEvent.mutex.RLock()

	argCopy := make([]*StorageMockSaveOutboxEventParams, len(mmSaveOutboxEvent.callArgs))
	copy(argCopy, mmSaveOutboxEvent.callArgs)

	mmSaveOutboxEvent.mutex.RUnlock()

	return argCopy
}

// MinimockSaveOutboxEventDone returns true if the count of the SaveOutboxEvent invocations corresponds
// the number of defined expectations
func (m *StorageMock) MinimockSaveOutboxEventDone() bool {
	if m.SaveOutboxEventMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SaveOutboxEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SaveOutboxEventMock.invocationsDone()
}

// MinimockSaveOutboxEventInspect logs each unmet expectation
func (m *StorageMock) MinimockSaveOutboxEventInspect() {
	for _, e := range m.SaveOutboxEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageMock.SaveOutboxEvent at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSaveOutboxEventCounter := mm_atomic.LoadUint64(&m.afterSaveOutboxEventCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SaveOutboxEventMock.defaultExpectation != nil && afterSaveOutboxEventCounter < 1 {
		if m.SaveOutboxEventMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageMock.SaveOutboxEvent at\n%s", m.SaveOutboxEventMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageMock.SaveOutboxEvent at\n%s with params: %#v", m.SaveOutboxEventMock.defaultExpectation.expectationOrigins.origin, *m.SaveOutboxEventMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSaveOutboxEvent != nil && afterSaveOutboxEventCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.SaveOutboxEvent at\n%s", m.funcSaveOutboxEventOrigin)
	}

	if !m.SaveOutboxEventMock.invocationsDone() && afterSaveOutboxEventCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageMock.SaveOutboxEvent at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SaveOutboxEventMock.expectedInvocations), m.SaveOutboxEventMock.expectedInvocationsOrigin, afterSaveOutboxEventCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StorageMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockFetchUnprocessedOutboxEventsInspect()

			m.MinimockMarkOutboxEventFailedInspect()

			m.MinimockMarkOutboxEventProcessedInspect()

			m.MinimockSaveOutboxEventInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StorageMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StorageMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockFetchUnprocessedOutboxEventsDone() &&
		m.MinimockMarkOutboxEventFailedDone() &&
		m.MinimockMarkOutboxEventProcessedDone() &&
		m.MinimockSaveOutboxEventDone()
}
