// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i control-plane/internal/transport/handler.ProcessService -o process_service_mock.go -n ProcessServiceMock -p mocks

import (
	"context"
	"control-plane/internal/model"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ProcessServiceMock implements mm_handler.ProcessService
type ProcessServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcProcessPaymentCallback          func(ctx context.Context, req model.CallbackInput) (err error)
	funcProcessPaymentCallbackOrigin    string
	inspectFuncProcessPaymentCallback   func(ctx context.Context, req model.CallbackInput)
	afterProcessPaymentCallbackCounter  uint64
	beforeProcessPaymentCallbackCounter uint64
	ProcessPaymentCallbackMock          mProcessServiceMockProcessPaymentCallback
}

// NewProcessServiceMock returns a mock for mm_handler.ProcessService
func NewProcessServiceMock(t minimock.Tester) *ProcessServiceMock {
	m := &ProcessServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ProcessPaymentCallbackMock = mProcessServiceMockProcessPaymentCallback{mock: m}
	m.ProcessPaymentCallbackMock.callArgs = []*ProcessServiceMockProcessPaymentCallbackParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mProcessServiceMockProcessPaymentCallback struct {
	optional           bool
	mock               *ProcessServiceMock
	defaultExpectation *ProcessServiceMockProcessPaymentCallbackExpectation
	expectations       []*ProcessServiceMockProcessPaymentCallbackExpectation

	callArgs []*ProcessServiceMockProcessPaymentCallbackParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ProcessServiceMockProcessPaymentCallbackExpectation specifies expectation struct of the ProcessService.ProcessPaymentCallback
type ProcessServiceMockProcessPaymentCallbackExpectation struct {
	mock               *ProcessServiceMock
	params             *ProcessServiceMockProcessPaymentCallbackParams
	paramPtrs          *ProcessServiceMockProcessPaymentCallbackParamPtrs
	expectationOrigins ProcessServiceMockProcessPaymentCallbackExpectationOrigins
	results            *ProcessServiceMockProcessPaymentCallbackResults
	returnOrigin       string
	Counter            uint64
}

// ProcessServiceMockProcessPaymentCallbackParams contains parameters of the ProcessService.ProcessPaymentCallback
type ProcessServiceMockProcessPaymentCallbackParams struct {
	ctx context.Context
	req model.CallbackInput
}

// ProcessServiceMockProcessPaymentCallbackParamPtrs contains pointers to parameters of the ProcessService.ProcessPaymentCallback
type ProcessServiceMockProcessPaymentCallbackParamPtrs struct {
	ctx *context.Context
	req *model.CallbackInput
}

// ProcessServiceMockProcessPaymentCallbackResults contains results of the ProcessService.ProcessPaymentCallback
type ProcessServiceMockProcessPaymentCallbackResults struct {
	err error
}

// ProcessServiceMockProcessPaymentCallbackOrigins contains origins of expectations of the ProcessService.ProcessPaymentCallback
type ProcessServiceMockProcessPaymentCallbackExpectationOrigins struct {
	origin    string
	originCtx string
	originReq string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmProcessPaymentCallback *mProcessServiceMockProcessPaymentCallback) Optional() *mProcessServiceMockProcessPaymentCallback {
	mmProcessPaymentCallback.optional = true
	return mmProcessPaymentCallback
}

// Expect sets up expected params for ProcessService.ProcessPaymentCallback
func (mmProcessPaymentCallback *mProcessServiceMockProcessPaymentCallback) Expect(ctx context.Context, req model.CallbackInput) *mProcessServiceMockProcessPaymentCallback {
	if mmProcessPaymentCallback.mock.funcProcessPaymentCallback != nil {
		mmProcessPaymentCallback.mock.t.Fatalf("ProcessServiceMock.ProcessPaymentCallback mock is already set by Set")
	}

	if mmProcessPaymentCallback.defaultExpectation == nil {
		mmProcessPaymentCallback.defaultExpectation = &ProcessServiceMockProcessPaymentCallbackExpectation{}
	}

	if mmProcessPaymentCallback.defaultExpectation.paramPtrs != nil {
		mmProcessPaymentCallback.mock.t.Fatalf("ProcessServiceMock.ProcessPaymentCallback mock is already set by ExpectParams functions")
	}

	mmProcessPaymentCallback.defaultExpectation.params = &ProcessServiceMockProcessPaymentCallbackParams{ctx, req}
	mmProcessPaymentCallback.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmProcessPaymentCallback.expectations {
		if minimock.Equal(e.params, mmProcessPaymentCallback.defaultExpectation.params) {
			mmProcessPaymentCallback.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmProcessPaymentCallback.defaultExpectation.params)
		}
	}

	return mmProcessPaymentCallback
}

// ExpectCtxParam1 sets up expected param ctx for ProcessService.ProcessPaymentCallback
func (mmProcessPaymentCallback *mProcessServiceMockProcessPaymentCallback) ExpectCtxParam1(ctx context.Context) *mProcessServiceMockProcessPaymentCallback {
	if mmProcessPaymentCallback.mock.funcProcessPaymentCallback != nil {
		mmProcessPaymentCallback.mock.t.Fatalf("ProcessServiceMock.ProcessPaymentCallback mock is already set by Set")
	}

	if mmProcessPaymentCallback.defaultExpectation == nil {
		mmProcessPaymentCallback.defaultExpectation = &ProcessServiceMockProcessPaymentCallbackExpectation{}
	}

	if mmProcessPaymentCallback.defaultExpectation.params != nil {
		mmProcessPaymentCallback.mock.t.Fatalf("ProcessServiceMock.ProcessPaymentCallback mock is already set by Expect")
	}

	if mmProcessPaymentCallback.defaultExpectation.paramPtrs == nil {
		mmProcessPaymentCallback.defaultExpectation.paramPtrs = &ProcessServiceMockProcessPaymentCallbackParamPtrs{}
	}
	mmProcessPaymentCallback.defaultExpectation.paramPtrs.ctx = &ctx
	mmProcessPaymentCallback.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmProcessPaymentCallback
}

// ExpectReqParam2 sets up expected param req for ProcessService.ProcessPaymentCallback
func (mmProcessPaymentCallback *mProcessServiceMockProcessPaymentCallback) ExpectReqParam2(req model.CallbackInput) *mProcessServiceMockProcessPaymentCallback {
	if mmProcessPaymentCallback.mock.funcProcessPaymentCallback != nil {
		mmProcessPaymentCallback.mock.t.Fatalf("ProcessServiceMock.ProcessPaymentCallback mock is already set by Set")
	}

	if mmProcessPaymentCallback.defaultExpectation == nil {
		mmProcessPaymentCallback.defaultExpectation = &ProcessServiceMockProcessPaymentCallbackExpectation{}
	}

	if mmProcessPaymentCallback.defaultExpectation.params != nil {
		mmProcessPaymentCallback.mock.t.Fatalf("ProcessServiceMock.ProcessPaymentCallback mock is already set by Expect")
	}

	if mmProcessPaymentCallback.defaultExpectation.paramPtrs == nil {
		mmProcessPaymentCallback.defaultExpectation.paramPtrs = &ProcessServiceMockProcessPaymentCallbackParamPtrs{}
	}
	mmProcessPaymentCallback.defaultExpectation.paramPtrs.req = &req
	mmProcessPaymentCallback.defaultExpectation.expectationOrigins.originReq = minimock.CallerInfo(1)

	return mmProcessPaymentCallback
}

// Inspect accepts an inspector function that has same arguments as the ProcessService.ProcessPaymentCallback
func (mmProcessPaymentCallback *mProcessServiceMockProcessPaymentCallback) Inspect(f func(ctx context.Context, req model.CallbackInput)) *mProcessServiceMockProcessPaymentCallback {
	if mmProcessPaymentCallback.mock.inspectFuncProcessPaymentCallback != nil {
		mmProcessPaymentCallback.mock.t.Fatalf("Inspect function is already set for ProcessServiceMock.ProcessPaymentCallback")
	}

	mmProcessPaymentCallback.mock.inspectFuncProcessPaymentCallback = f

	return mmProcessPaymentCallback
}

// Return sets up results that will be returned by ProcessService.ProcessPaymentCallback
func (mmProcessPaymentCallback *mProcessServiceMockProcessPaymentCallback) Return(err error) *ProcessServiceMock {
	if mmProcessPaymentCallback.mock.funcProcessPaymentCallback != nil {
		mmProcessPaymentCallback.mock.t.Fatalf("ProcessServiceMock.ProcessPaymentCallback mock is already set by Set")
	}

	if mmProcessPaymentCallback.defaultExpectation == nil {
		mmProcessPaymentCallback.defaultExpectation = &ProcessServiceMockProcessPaymentCallbackExpectation{mock: mmProcessPaymentCallback.mock}
	}
	mmProcessPaymentCallback.defaultExpectation.results = &ProcessServiceMockProcessPaymentCallbackResults{err}
	mmProcessPaymentCallback.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmProcessPaymentCallback.mock
}

// Set uses given function f to mock the ProcessService.ProcessPaymentCallback method
func (mmProcessPaymentCallback *mProcessServiceMockProcessPaymentCallback) Set(f func(ctx context.Context, req model.CallbackInput) (err error)) *ProcessServiceMock {
	if mmProcessPaymentCallback.defaultExpectation != nil {
		mmProcessPaymentCallback.mock.t.Fatalf("Default expectation is already set for the ProcessService.ProcessPaymentCallback method")
	}

	if len(mmProcessPaymentCallback.expectations) > 0 {
		mmProcessPaymentCallback.mock.t.Fatalf("Some expectations are already set for the ProcessService.ProcessPaymentCallback method")
	}

	mmProcessPaymentCallback.mock.funcProcessPaymentCallback = f
	mmProcessPaymentCallback.mock.funcProcessPaymentCallbackOrigin = minimock.CallerInfo(1)
	return mmProcessPaymentCallback.mock
}

// When sets expectation for the ProcessService.ProcessPaymentCallback which will trigger the result defined by the following
// Then helper
func (mmProcessPaymentCallback *mProcessServiceMockProcessPaymentCallback) When(ctx context.Context, req model.CallbackInput) *ProcessServiceMockProcessPaymentCallbackExpectation {
	if mmProcessPaymentCallback.mock.funcProcessPaymentCallback != nil {
		mmProcessPaymentCallback.mock.t.Fatalf("ProcessServiceMock.ProcessPaymentCallback mock is already set by Set")
	}

	expectation := &ProcessServiceMockProcessPaymentCallbackExpectation{
		mock:               mmProcessPaymentCallback.mock,
		params:             &ProcessServiceMockProcessPaymentCallbackParams{ctx, req},
		expectationOrigins: ProcessServiceMockProcessPaymentCallbackExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmProcessPaymentCallback.expectations = append(mmProcessPaymentCallback.expectations, expectation)
	return expectation
}

// Then sets up ProcessService.ProcessPaymentCallback return parameters for the expectation previously defined by the When method
func (e *ProcessServiceMockProcessPaymentCallbackExpectation) Then(err error) *ProcessServiceMock {
	e.results = &ProcessServiceMockProcessPaymentCallbackResults{err}
	return e.mock
}

// Times sets number of times ProcessService.ProcessPaymentCallback should be invoked
func (mmProcessPaymentCallback *mProcessServiceMockProcessPaymentCallback) Times(n uint64) *mProcessServiceMockProcessPaymentCallback {
	if n == 0 {
		mmProcessPaymentCallback.mock.t.Fatalf("Times of ProcessServiceMock.ProcessPaymentCallback mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmProcessPaymentCallback.expectedInvocations, n)
	mmProcessPaymentCallback.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmProcessPaymentCallback
}

func (mmProcessPaymentCallback *mProcessServiceMockProcessPaymentCallback) invocationsDone() bool {
	if len(mmProcessPaymentCallback.expectations) == 0 && mmProcessPaymentCallback.defaultExpectation == nil && mmProcessPaymentCallback.mock.funcProcessPaymentCallback == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmProcessPaymentCallback.mock.afterProcessPaymentCallbackCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmProcessPaymentCallback.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ProcessPaymentCallback implements mm_handler.ProcessService
func (mmProcessPaymentCallback *ProcessServiceMock) ProcessPaymentCallback(ctx context.Context, req model.CallbackInput) (err error) {
	mm_atomic.AddUint64(&mmProcessPaymentCallback.beforeProcessPaymentCallbackCounter, 1)
	defer mm_atomic.AddUint64(&mmProcessPaymentCallback.afterProcessPaymentCallbackCounter, 1)

	mmProcessPaymentCallback.t.Helper()

	if mmProcessPaymentCallback.inspectFuncProcessPaymentCallback != nil {
		mmProcessPaymentCallback.inspectFuncProcessPaymentCallback(ctx, req)
	}

	mm_params := ProcessServiceMockProcessPaymentCallbackParams{ctx, req}

	// Record call args
	mmProcessPaymentCallback.ProcessPaymentCallbackMock.mutex.Lock()
	mmProcessPaymentCallback.ProcessPaymentCallbackMock.callArgs = append(mmProcessPaymentCallback.ProcessPaymentCallbackMock.callArgs, &mm_params)
	mmProcessPaymentCallback.ProcessPaymentCallbackMock.mutex.Unlock()

	for _, e := range mmProcessPaymentCallback.ProcessPaymentCallbackMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmProcessPaymentCallback.ProcessPaymentCallbackMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmProcessPaymentCallback.ProcessPaymentCallbackMock.defaultExpectation.Counter, 1)
		mm_want := mmProcessPaymentCallback.ProcessPaymentCallbackMock.defaultExpectation.params
		mm_want_ptrs := mmProcessPaymentCallback.ProcessPaymentCallbackMock.defaultExpectation.paramPtrs

		mm_got := ProcessServiceMockProcessPaymentCallbackParams{ctx, req}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmProcessPaymentCallback.t.Errorf("ProcessServiceMock.ProcessPaymentCallback got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmProcessPaymentCallback.ProcessPaymentCallbackMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.req != nil && !minimock.Equal(*mm_want_ptrs.req, mm_got.req) {
				mmProcessPaymentCallback.t.Errorf("ProcessServiceMock.ProcessPaymentCallback got unexpected parameter req, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmProcessPaymentCallback.ProcessPaymentCallbackMock.defaultExpectation.expectationOrigins.originReq, *mm_want_ptrs.req, mm_got.req, minimock.Diff(*mm_want_ptrs.req, mm_got.req))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmProcessPaymentCallback.t.Errorf("ProcessServiceMock.ProcessPaymentCallback got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmProcessPaymentCallback.ProcessPaymentCallbackMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmProcessPaymentCallback.ProcessPaymentCallbackMock.defaultExpectation.results
		if mm_results == nil {
			mmProcessPaymentCallback.t.Fatal("No results are set for the ProcessServiceMock.ProcessPaymentCallback")
		}
		return (*mm_results).err
	}
	if mmProcessPaymentCallback.funcProcessPaymentCallback != nil {
		return mmProcessPaymentCallback.funcProcessPaymentCallback(ctx, req)
	}
	mmProcessPaymentCallback.t.Fatalf("Unexpected call to ProcessServiceMock.ProcessPaymentCallback. %v %v", ctx, req)
	return
}

// ProcessPaymentCallbackAfterCounter returns a count of finished ProcessServiceMock.ProcessPaymentCallback invocations
func (mmProcessPaymentCallback *ProcessServiceMock) ProcessPaymentCallbackAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmProcessPaymentCallback.afterProcessPaymentCallbackCounter)
}

// ProcessPaymentCallbackBeforeCounter returns a count of ProcessServiceMock.ProcessPaymentCallback invocations
func (mmProcessPaymentCallback *ProcessServiceMock) ProcessPaymentCallbackBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmProcessPaymentCallback.beforeProcessPaymentCallbackCounter)
}

// Calls returns a list of arguments used in each call to ProcessServiceMock.ProcessPaymentCallback.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmProcessPaymentCallback *mProcessServiceMockProcessPaymentCallback) Calls() []*ProcessServiceMockProcessPaymentCallbackParams {
	mmProcessPaymentCallback.mutex.RLock()

	argCopy := make([]*ProcessServiceMockProcessPaymentCallbackParams, len(mmProcessPaymentCallback.callArgs))
	copy(argCopy, mmProcessPaymentCallback.callArgs)

	mmProcessPaymentCallback.mutex.RUnlock()

	return argCopy
}

// MinimockProcessPaymentCallbackDone returns true if the count of the ProcessPaymentCallback invocations corresponds
// the number of defined expectations
func (m *ProcessServiceMock) MinimockProcessPaymentCallbackDone() bool {
	if m.ProcessPaymentCallbackMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ProcessPaymentCallbackMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ProcessPaymentCallbackMock.invocationsDone()
}

// MinimockProcessPaymentCallbackInspect logs each unmet expectation
func (m *ProcessServiceMock) MinimockProcessPaymentCallbackInspect() {
	for _, e := range m.ProcessPaymentCallbackMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ProcessServiceMock.ProcessPaymentCallback at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterProcessPaymentCallbackCounter := mm_atomic.LoadUint64(&m.afterProcessPaymentCallbackCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ProcessPaymentCallbackMock.defaultExpectation != nil && afterProcessPaymentCallbackCounter < 1 {
		if m.ProcessPaymentCallbackMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ProcessServiceMock.ProcessPaymentCallback at\n%s", m.ProcessPaymentCallbackMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ProcessServiceMock.ProcessPaymentCallback at\n%s with params: %#v", m.ProcessPaymentCallbackMock.defaultExpectation.expectationOrigins.origin, *m.ProcessPaymentCallbackMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcProcessPaymentCallback != nil && afterProcessPaymentCallbackCounter < 1 {
		m.t.Errorf("Expected call to ProcessServiceMock.ProcessPaymentCallback at\n%s", m.funcProcessPaymentCallbackOrigin)
	}

	if !m.ProcessPaymentCallbackMock.invocationsDone() && afterProcessPaymentCallbackCounter > 0 {
		m.t.Errorf("Expected %d calls to ProcessServiceMock.ProcessPaymentCallback at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ProcessPaymentCallbackMock.expectedInvocations), m.ProcessPaymentCallbackMock.expectedInvocationsOrigin, afterProcessPaymentCallbackCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ProcessServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockProcessPaymentCallbackInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ProcessServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ProcessServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockProcessPaymentCallbackDone()
}
