// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.2
// source: api/control/control.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // tech id, every tg & driver_type --> unique_id
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	DriverType    string                 `protobuf:"bytes,3,opt,name=driver_type,json=driverType,proto3" json:"driver_type,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_control_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *User) GetDriverType() string {
	if x != nil {
		return x.DriverType
	}
	return ""
}

func (x *User) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type TaskMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // business idempotency
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`                             // transport idempotency
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMeta) Reset() {
	*x = TaskMeta{}
	mi := &file_api_control_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMeta) ProtoMessage() {}

func (x *TaskMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMeta.ProtoReflect.Descriptor instead.
func (*TaskMeta) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{1}
}

func (x *TaskMeta) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TaskMeta) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_control_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{2}
}

type UserUpsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpsertRequest) Reset() {
	*x = UserUpsertRequest{}
	mi := &file_api_control_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpsertRequest) ProtoMessage() {}

func (x *UserUpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpsertRequest.ProtoReflect.Descriptor instead.
func (*UserUpsertRequest) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{3}
}

func (x *UserUpsertRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserRemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DriverType    string                 `protobuf:"bytes,2,opt,name=driver_type,json=driverType,proto3" json:"driver_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRemoveRequest) Reset() {
	*x = UserRemoveRequest{}
	mi := &file_api_control_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRemoveRequest) ProtoMessage() {}

func (x *UserRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRemoveRequest.ProtoReflect.Descriptor instead.
func (*UserRemoveRequest) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{4}
}

func (x *UserRemoveRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRemoveRequest) GetDriverType() string {
	if x != nil {
		return x.DriverType
	}
	return ""
}

type StatsAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsAllRequest) Reset() {
	*x = StatsAllRequest{}
	mi := &file_api_control_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsAllRequest) ProtoMessage() {}

func (x *StatsAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsAllRequest.ProtoReflect.Descriptor instead.
func (*StatsAllRequest) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{5}
}

type StatsUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsUserRequest) Reset() {
	*x = StatsUserRequest{}
	mi := &file_api_control_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsUserRequest) ProtoMessage() {}

func (x *StatsUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsUserRequest.ProtoReflect.Descriptor instead.
func (*StatsUserRequest) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{6}
}

func (x *StatsUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Meta  *TaskMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Task_Upsert
	//	*Task_Remove
	//	*Task_StatsAll
	//	*Task_StatsUser
	Body          isTask_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_control_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{7}
}

func (x *Task) GetMeta() *TaskMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Task) GetBody() isTask_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Task) GetUpsert() *UserUpsertRequest {
	if x != nil {
		if x, ok := x.Body.(*Task_Upsert); ok {
			return x.Upsert
		}
	}
	return nil
}

func (x *Task) GetRemove() *UserRemoveRequest {
	if x != nil {
		if x, ok := x.Body.(*Task_Remove); ok {
			return x.Remove
		}
	}
	return nil
}

func (x *Task) GetStatsAll() *StatsAllRequest {
	if x != nil {
		if x, ok := x.Body.(*Task_StatsAll); ok {
			return x.StatsAll
		}
	}
	return nil
}

func (x *Task) GetStatsUser() *StatsUserRequest {
	if x != nil {
		if x, ok := x.Body.(*Task_StatsUser); ok {
			return x.StatsUser
		}
	}
	return nil
}

type isTask_Body interface {
	isTask_Body()
}

type Task_Upsert struct {
	Upsert *UserUpsertRequest `protobuf:"bytes,2,opt,name=upsert,proto3,oneof"`
}

type Task_Remove struct {
	Remove *UserRemoveRequest `protobuf:"bytes,3,opt,name=remove,proto3,oneof"`
}

type Task_StatsAll struct {
	StatsAll *StatsAllRequest `protobuf:"bytes,4,opt,name=stats_all,json=statsAll,proto3,oneof"`
}

type Task_StatsUser struct {
	StatsUser *StatsUserRequest `protobuf:"bytes,5,opt,name=stats_user,json=statsUser,proto3,oneof"`
}

func (*Task_Upsert) isTask_Body() {}

func (*Task_Remove) isTask_Body() {}

func (*Task_StatsAll) isTask_Body() {}

func (*Task_StatsUser) isTask_Body() {}

type ControlToAgent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ControlToAgent_Welcome
	//	*ControlToAgent_Task
	Msg           isControlToAgent_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlToAgent) Reset() {
	*x = ControlToAgent{}
	mi := &file_api_control_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlToAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlToAgent) ProtoMessage() {}

func (x *ControlToAgent) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlToAgent.ProtoReflect.Descriptor instead.
func (*ControlToAgent) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{8}
}

func (x *ControlToAgent) GetMsg() isControlToAgent_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ControlToAgent) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Msg.(*ControlToAgent_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ControlToAgent) GetTask() *Task {
	if x != nil {
		if x, ok := x.Msg.(*ControlToAgent_Task); ok {
			return x.Task
		}
	}
	return nil
}

type isControlToAgent_Msg interface {
	isControlToAgent_Msg()
}

type ControlToAgent_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ControlToAgent_Task struct {
	Task *Task `protobuf:"bytes,2,opt,name=task,proto3,oneof"`
}

func (*ControlToAgent_Welcome) isControlToAgent_Msg() {}

func (*ControlToAgent_Task) isControlToAgent_Msg() {}

type UserUpsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creds         *UserCreds             `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpsertResponse) Reset() {
	*x = UserUpsertResponse{}
	mi := &file_api_control_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpsertResponse) ProtoMessage() {}

func (x *UserUpsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpsertResponse.ProtoReflect.Descriptor instead.
func (*UserUpsertResponse) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{9}
}

func (x *UserUpsertResponse) GetCreds() *UserCreds {
	if x != nil {
		return x.Creds
	}
	return nil
}

type UserRemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRemoveResponse) Reset() {
	*x = UserRemoveResponse{}
	mi := &file_api_control_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRemoveResponse) ProtoMessage() {}

func (x *UserRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRemoveResponse.ProtoReflect.Descriptor instead.
func (*UserRemoveResponse) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{10}
}

type StatsAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserStat            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalBytesRx  uint64                 `protobuf:"varint,2,opt,name=total_bytes_rx,json=totalBytesRx,proto3" json:"total_bytes_rx,omitempty"`
	TotalBytesTx  uint64                 `protobuf:"varint,3,opt,name=total_bytes_tx,json=totalBytesTx,proto3" json:"total_bytes_tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsAllResponse) Reset() {
	*x = StatsAllResponse{}
	mi := &file_api_control_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsAllResponse) ProtoMessage() {}

func (x *StatsAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsAllResponse.ProtoReflect.Descriptor instead.
func (*StatsAllResponse) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{11}
}

func (x *StatsAllResponse) GetUsers() []*UserStat {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *StatsAllResponse) GetTotalBytesRx() uint64 {
	if x != nil {
		return x.TotalBytesRx
	}
	return 0
}

func (x *StatsAllResponse) GetTotalBytesTx() uint64 {
	if x != nil {
		return x.TotalBytesTx
	}
	return 0
}

type StatsUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stat          *UserStat              `protobuf:"bytes,1,opt,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsUserResponse) Reset() {
	*x = StatsUserResponse{}
	mi := &file_api_control_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsUserResponse) ProtoMessage() {}

func (x *StatsUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsUserResponse.ProtoReflect.Descriptor instead.
func (*StatsUserResponse) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{12}
}

func (x *StatsUserResponse) GetStat() *UserStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_api_control_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{13}
}

func (x *Error) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UserStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BytesRx       uint64                 `protobuf:"varint,2,opt,name=bytes_rx,json=bytesRx,proto3" json:"bytes_rx,omitempty"`
	BytesTx       uint64                 `protobuf:"varint,3,opt,name=bytes_tx,json=bytesTx,proto3" json:"bytes_tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStat) Reset() {
	*x = UserStat{}
	mi := &file_api_control_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStat) ProtoMessage() {}

func (x *UserStat) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStat.ProtoReflect.Descriptor instead.
func (*UserStat) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{14}
}

func (x *UserStat) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserStat) GetBytesRx() uint64 {
	if x != nil {
		return x.BytesRx
	}
	return 0
}

func (x *UserStat) GetBytesTx() uint64 {
	if x != nil {
		return x.BytesTx
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	UptimeSeconds uint32                 `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_api_control_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{15}
}

func (x *Heartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Heartbeat) GetUptimeSeconds() uint32 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Meta  *TaskMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Response_Upsert
	//	*Response_Remove
	//	*Response_StatsAll
	//	*Response_StatsUser
	//	*Response_Error
	Body          isResponse_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_api_control_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{16}
}

func (x *Response) GetMeta() *TaskMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Response) GetBody() isResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Response) GetUpsert() *UserUpsertResponse {
	if x != nil {
		if x, ok := x.Body.(*Response_Upsert); ok {
			return x.Upsert
		}
	}
	return nil
}

func (x *Response) GetRemove() *UserRemoveResponse {
	if x != nil {
		if x, ok := x.Body.(*Response_Remove); ok {
			return x.Remove
		}
	}
	return nil
}

func (x *Response) GetStatsAll() *StatsAllResponse {
	if x != nil {
		if x, ok := x.Body.(*Response_StatsAll); ok {
			return x.StatsAll
		}
	}
	return nil
}

func (x *Response) GetStatsUser() *StatsUserResponse {
	if x != nil {
		if x, ok := x.Body.(*Response_StatsUser); ok {
			return x.StatsUser
		}
	}
	return nil
}

func (x *Response) GetError() *Error {
	if x != nil {
		if x, ok := x.Body.(*Response_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isResponse_Body interface {
	isResponse_Body()
}

type Response_Upsert struct {
	Upsert *UserUpsertResponse `protobuf:"bytes,2,opt,name=upsert,proto3,oneof"`
}

type Response_Remove struct {
	Remove *UserRemoveResponse `protobuf:"bytes,3,opt,name=remove,proto3,oneof"`
}

type Response_StatsAll struct {
	StatsAll *StatsAllResponse `protobuf:"bytes,4,opt,name=stats_all,json=statsAll,proto3,oneof"`
}

type Response_StatsUser struct {
	StatsUser *StatsUserResponse `protobuf:"bytes,5,opt,name=stats_user,json=statsUser,proto3,oneof"`
}

type Response_Error struct {
	Error *Error `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

func (*Response_Upsert) isResponse_Body() {}

func (*Response_Remove) isResponse_Body() {}

func (*Response_StatsAll) isResponse_Body() {}

func (*Response_StatsUser) isResponse_Body() {}

func (*Response_Error) isResponse_Body() {}

type AgentToControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentToControl_Hello
	//	*AgentToControl_Resp
	//	*AgentToControl_Hb
	Msg           isAgentToControl_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentToControl) Reset() {
	*x = AgentToControl{}
	mi := &file_api_control_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentToControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentToControl) ProtoMessage() {}

func (x *AgentToControl) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentToControl.ProtoReflect.Descriptor instead.
func (*AgentToControl) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{17}
}

func (x *AgentToControl) GetMsg() isAgentToControl_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentToControl) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Msg.(*AgentToControl_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentToControl) GetResp() *Response {
	if x != nil {
		if x, ok := x.Msg.(*AgentToControl_Resp); ok {
			return x.Resp
		}
	}
	return nil
}

func (x *AgentToControl) GetHb() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*AgentToControl_Hb); ok {
			return x.Hb
		}
	}
	return nil
}

type isAgentToControl_Msg interface {
	isAgentToControl_Msg()
}

type AgentToControl_Hello struct {
	Hello *AgentHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentToControl_Resp struct {
	Resp *Response `protobuf:"bytes,2,opt,name=resp,proto3,oneof"`
}

type AgentToControl_Hb struct {
	Hb *Heartbeat `protobuf:"bytes,3,opt,name=hb,proto3,oneof"`
}

func (*AgentToControl_Hello) isAgentToControl_Msg() {}

func (*AgentToControl_Resp) isAgentToControl_Msg() {}

func (*AgentToControl_Hb) isAgentToControl_Msg() {}

type AgentHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	DriverTypes   []string               `protobuf:"bytes,5,rep,name=driver_types,json=driverTypes,proto3" json:"driver_types,omitempty"` // xray, wg and other
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_api_control_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{18}
}

func (x *AgentHello) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentHello) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *AgentHello) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AgentHello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentHello) GetDriverTypes() []string {
	if x != nil {
		return x.DriverTypes
	}
	return nil
}

type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_api_control_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{19}
}

func (x *Welcome) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Welcome) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserCreds struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	UserId      string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AgentId     string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	DriverType  string                 `protobuf:"bytes,3,opt,name=driver_type,json=driverType,proto3" json:"driver_type,omitempty"`
	GeneratedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	// Types that are valid to be assigned to Config:
	//
	//	*UserCreds_Vless
	//	*UserCreds_Wireguard
	Config        isUserCreds_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreds) Reset() {
	*x = UserCreds{}
	mi := &file_api_control_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreds) ProtoMessage() {}

func (x *UserCreds) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreds.ProtoReflect.Descriptor instead.
func (*UserCreds) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{20}
}

func (x *UserCreds) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserCreds) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UserCreds) GetDriverType() string {
	if x != nil {
		return x.DriverType
	}
	return ""
}

func (x *UserCreds) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *UserCreds) GetConfig() isUserCreds_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UserCreds) GetVless() *VlessCreds {
	if x != nil {
		if x, ok := x.Config.(*UserCreds_Vless); ok {
			return x.Vless
		}
	}
	return nil
}

func (x *UserCreds) GetWireguard() *WireGuardCreds {
	if x != nil {
		if x, ok := x.Config.(*UserCreds_Wireguard); ok {
			return x.Wireguard
		}
	}
	return nil
}

type isUserCreds_Config interface {
	isUserCreds_Config()
}

type UserCreds_Vless struct {
	Vless *VlessCreds `protobuf:"bytes,10,opt,name=vless,proto3,oneof"`
}

type UserCreds_Wireguard struct {
	Wireguard *WireGuardCreds `protobuf:"bytes,11,opt,name=wireguard,proto3,oneof"`
}

func (*UserCreds_Vless) isUserCreds_Config() {}

func (*UserCreds_Wireguard) isUserCreds_Config() {}

// Vless + reality
type VlessCreds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Security      string                 `protobuf:"bytes,4,opt,name=security,proto3" json:"security,omitempty"`
	Sni           string                 `protobuf:"bytes,5,opt,name=sni,proto3" json:"sni,omitempty"`
	Alpn          string                 `protobuf:"bytes,6,opt,name=alpn,proto3" json:"alpn,omitempty"`
	Path          string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	Network       string                 `protobuf:"bytes,8,opt,name=network,proto3" json:"network,omitempty"`
	Flow          string                 `protobuf:"bytes,9,opt,name=flow,proto3" json:"flow,omitempty"`
	Uri           string                 `protobuf:"bytes,10,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VlessCreds) Reset() {
	*x = VlessCreds{}
	mi := &file_api_control_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlessCreds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlessCreds) ProtoMessage() {}

func (x *VlessCreds) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlessCreds.ProtoReflect.Descriptor instead.
func (*VlessCreds) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{21}
}

func (x *VlessCreds) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *VlessCreds) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *VlessCreds) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *VlessCreds) GetSecurity() string {
	if x != nil {
		return x.Security
	}
	return ""
}

func (x *VlessCreds) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *VlessCreds) GetAlpn() string {
	if x != nil {
		return x.Alpn
	}
	return ""
}

func (x *VlessCreds) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *VlessCreds) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *VlessCreds) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *VlessCreds) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

// WireGuard.
type WireGuardCreds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey    string                 `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PeerPublicKey string                 `protobuf:"bytes,3,opt,name=peer_public_key,json=peerPublicKey,proto3" json:"peer_public_key,omitempty"`
	Endpoint      string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	AllowedIps    []string               `protobuf:"bytes,6,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	Dns           []string               `protobuf:"bytes,7,rep,name=dns,proto3" json:"dns,omitempty"`
	Mtu           uint32                 `protobuf:"varint,8,opt,name=mtu,proto3" json:"mtu,omitempty"`
	PresharedKey  string                 `protobuf:"bytes,9,opt,name=preshared_key,json=presharedKey,proto3" json:"preshared_key,omitempty"`
	Config        string                 `protobuf:"bytes,10,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireGuardCreds) Reset() {
	*x = WireGuardCreds{}
	mi := &file_api_control_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireGuardCreds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuardCreds) ProtoMessage() {}

func (x *WireGuardCreds) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuardCreds.ProtoReflect.Descriptor instead.
func (*WireGuardCreds) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{22}
}

func (x *WireGuardCreds) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *WireGuardCreds) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *WireGuardCreds) GetPeerPublicKey() string {
	if x != nil {
		return x.PeerPublicKey
	}
	return ""
}

func (x *WireGuardCreds) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *WireGuardCreds) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WireGuardCreds) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *WireGuardCreds) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

func (x *WireGuardCreds) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *WireGuardCreds) GetPresharedKey() string {
	if x != nil {
		return x.PresharedKey
	}
	return ""
}

func (x *WireGuardCreds) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

var File_api_control_control_proto protoreflect.FileDescriptor

var file_api_control_control_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x76, 0x70, 0x6e,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x91, 0x01, 0x0a,
	0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73,
	0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74,
	0x22, 0x3b, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x22, 0x07, 0x0a,
	0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x3d, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70,
	0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x70, 0x6e, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x4d, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x74, 0x73, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2b, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0xb9, 0x02, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x2c, 0x0a,
	0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x76, 0x70,
	0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x3b, 0x0a, 0x06, 0x75,
	0x70, 0x73, 0x65, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x76, 0x70,
	0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x06, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x12, 0x3b, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x61,
	0x6c, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x08, 0x73, 0x74, 0x61,
	0x74, 0x73, 0x41, 0x6c, 0x6c, 0x12, 0x41, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x76, 0x70, 0x6e, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x09, 0x73,
	0x74, 0x61, 0x74, 0x73, 0x55, 0x73, 0x65, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x22, 0x78, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x54, 0x6f, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x12, 0x33, 0x0a, 0x07, 0x77, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x07,
	0x77, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x00, 0x52, 0x04, 0x74,
	0x61, 0x73, 0x6b, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x45, 0x0a, 0x12, 0x55, 0x73,
	0x65, 0x72, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2f, 0x0a, 0x05, 0x63, 0x72, 0x65, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x73, 0x52, 0x05, 0x63, 0x72, 0x65, 0x64,
	0x73, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x8e, 0x01, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x05,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x76, 0x70,
	0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x24, 0x0a, 0x0e,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x72, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x52, 0x78, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x5f, 0x74, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x54, 0x78, 0x22, 0x41, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a,
	0x04, 0x73, 0x74, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x76, 0x70,
	0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x52, 0x04, 0x73, 0x74, 0x61, 0x74, 0x22, 0x1d, 0x0a, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x59, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x72, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x62, 0x79, 0x74, 0x65, 0x73, 0x52, 0x78, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x79,
	0x74, 0x65, 0x73, 0x5f, 0x74, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x62, 0x79,
	0x74, 0x65, 0x73, 0x54, 0x78, 0x22, 0x4d, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65,
	0x61, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x25, 0x0a,
	0x0e, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x22, 0xf0, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2c, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12,
	0x3c, 0x0a, 0x06, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x06, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x12, 0x3c, 0x0a,
	0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x3f, 0x0a, 0x09, 0x73,
	0x74, 0x61, 0x74, 0x73, 0x5f, 0x61, 0x6c, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x73, 0x41, 0x6c, 0x6c, 0x12, 0x42, 0x0a, 0x0a,
	0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x73, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x2d, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42,
	0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0xa8, 0x01, 0x0a, 0x0e, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x54, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x32, 0x0a, 0x05, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x76, 0x70, 0x6e, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x2e,
	0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x76,
	0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x12, 0x2b,
	0x0a, 0x02, 0x68, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x70, 0x6e,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x62, 0x65, 0x61, 0x74, 0x48, 0x00, 0x52, 0x02, 0x68, 0x62, 0x42, 0x05, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x9d, 0x01, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x21, 0x0a, 0x0c, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x73, 0x22, 0x3e, 0x0a, 0x07, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x9d, 0x02, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x73,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x32, 0x0a, 0x05, 0x76, 0x6c, 0x65, 0x73, 0x73, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x6c, 0x65, 0x73, 0x73, 0x43, 0x72, 0x65, 0x64, 0x73, 0x48,
	0x00, 0x52, 0x05, 0x76, 0x6c, 0x65, 0x73, 0x73, 0x12, 0x3e, 0x0a, 0x09, 0x77, 0x69, 0x72, 0x65,
	0x67, 0x75, 0x61, 0x72, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x76, 0x70,
	0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x69, 0x72,
	0x65, 0x47, 0x75, 0x61, 0x72, 0x64, 0x43, 0x72, 0x65, 0x64, 0x73, 0x48, 0x00, 0x52, 0x09, 0x77,
	0x69, 0x72, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x22, 0xde, 0x01, 0x0a, 0x0a, 0x56, 0x6c, 0x65, 0x73, 0x73, 0x43, 0x72, 0x65, 0x64,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6e, 0x69,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6e, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x6c, 0x70, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x6c, 0x70, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x6c, 0x6f, 0x77, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x6c, 0x6f,
	0x77, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x69, 0x22, 0xb0, 0x02, 0x0a, 0x0e, 0x57, 0x69, 0x72, 0x65, 0x47, 0x75, 0x61, 0x72,
	0x64, 0x43, 0x72, 0x65, 0x64, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x0f, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x70, 0x65, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x1a,
	0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f,
	0x69, 0x70, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x49, 0x70, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x03, 0x64, 0x6e, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x74, 0x75, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x74, 0x75, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x65,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x70, 0x72, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x32, 0x60, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x12, 0x50, 0x0a, 0x0a, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x12, 0x1e, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x1a, 0x1e, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x54, 0x6f, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x28, 0x01, 0x30, 0x01, 0x42, 0x1f, 0x5a, 0x1d, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x3b,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_control_control_proto_rawDescOnce sync.Once
	file_api_control_control_proto_rawDescData = file_api_control_control_proto_rawDesc
)

func file_api_control_control_proto_rawDescGZIP() []byte {
	file_api_control_control_proto_rawDescOnce.Do(func() {
		file_api_control_control_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_control_control_proto_rawDescData)
	})
	return file_api_control_control_proto_rawDescData
}

var file_api_control_control_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_control_control_proto_goTypes = []any{
	(*User)(nil),                  // 0: vpn.control.v1.User
	(*TaskMeta)(nil),              // 1: vpn.control.v1.TaskMeta
	(*Empty)(nil),                 // 2: vpn.control.v1.Empty
	(*UserUpsertRequest)(nil),     // 3: vpn.control.v1.UserUpsertRequest
	(*UserRemoveRequest)(nil),     // 4: vpn.control.v1.UserRemoveRequest
	(*StatsAllRequest)(nil),       // 5: vpn.control.v1.StatsAllRequest
	(*StatsUserRequest)(nil),      // 6: vpn.control.v1.StatsUserRequest
	(*Task)(nil),                  // 7: vpn.control.v1.Task
	(*ControlToAgent)(nil),        // 8: vpn.control.v1.ControlToAgent
	(*UserUpsertResponse)(nil),    // 9: vpn.control.v1.UserUpsertResponse
	(*UserRemoveResponse)(nil),    // 10: vpn.control.v1.UserRemoveResponse
	(*StatsAllResponse)(nil),      // 11: vpn.control.v1.StatsAllResponse
	(*StatsUserResponse)(nil),     // 12: vpn.control.v1.StatsUserResponse
	(*Error)(nil),                 // 13: vpn.control.v1.Error
	(*UserStat)(nil),              // 14: vpn.control.v1.UserStat
	(*Heartbeat)(nil),             // 15: vpn.control.v1.Heartbeat
	(*Response)(nil),              // 16: vpn.control.v1.Response
	(*AgentToControl)(nil),        // 17: vpn.control.v1.AgentToControl
	(*AgentHello)(nil),            // 18: vpn.control.v1.AgentHello
	(*Welcome)(nil),               // 19: vpn.control.v1.Welcome
	(*UserCreds)(nil),             // 20: vpn.control.v1.UserCreds
	(*VlessCreds)(nil),            // 21: vpn.control.v1.VlessCreds
	(*WireGuardCreds)(nil),        // 22: vpn.control.v1.WireGuardCreds
	(*timestamppb.Timestamp)(nil), // 23: google.protobuf.Timestamp
}
var file_api_control_control_proto_depIdxs = []int32{
	23, // 0: vpn.control.v1.User.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 1: vpn.control.v1.UserUpsertRequest.user:type_name -> vpn.control.v1.User
	1,  // 2: vpn.control.v1.Task.meta:type_name -> vpn.control.v1.TaskMeta
	3,  // 3: vpn.control.v1.Task.upsert:type_name -> vpn.control.v1.UserUpsertRequest
	4,  // 4: vpn.control.v1.Task.remove:type_name -> vpn.control.v1.UserRemoveRequest
	5,  // 5: vpn.control.v1.Task.stats_all:type_name -> vpn.control.v1.StatsAllRequest
	6,  // 6: vpn.control.v1.Task.stats_user:type_name -> vpn.control.v1.StatsUserRequest
	19, // 7: vpn.control.v1.ControlToAgent.welcome:type_name -> vpn.control.v1.Welcome
	7,  // 8: vpn.control.v1.ControlToAgent.task:type_name -> vpn.control.v1.Task
	20, // 9: vpn.control.v1.UserUpsertResponse.creds:type_name -> vpn.control.v1.UserCreds
	14, // 10: vpn.control.v1.StatsAllResponse.users:type_name -> vpn.control.v1.UserStat
	14, // 11: vpn.control.v1.StatsUserResponse.stat:type_name -> vpn.control.v1.UserStat
	1,  // 12: vpn.control.v1.Response.meta:type_name -> vpn.control.v1.TaskMeta
	9,  // 13: vpn.control.v1.Response.upsert:type_name -> vpn.control.v1.UserUpsertResponse
	10, // 14: vpn.control.v1.Response.remove:type_name -> vpn.control.v1.UserRemoveResponse
	11, // 15: vpn.control.v1.Response.stats_all:type_name -> vpn.control.v1.StatsAllResponse
	12, // 16: vpn.control.v1.Response.stats_user:type_name -> vpn.control.v1.StatsUserResponse
	13, // 17: vpn.control.v1.Response.error:type_name -> vpn.control.v1.Error
	18, // 18: vpn.control.v1.AgentToControl.hello:type_name -> vpn.control.v1.AgentHello
	16, // 19: vpn.control.v1.AgentToControl.resp:type_name -> vpn.control.v1.Response
	15, // 20: vpn.control.v1.AgentToControl.hb:type_name -> vpn.control.v1.Heartbeat
	23, // 21: vpn.control.v1.UserCreds.generated_at:type_name -> google.protobuf.Timestamp
	21, // 22: vpn.control.v1.UserCreds.vless:type_name -> vpn.control.v1.VlessCreds
	22, // 23: vpn.control.v1.UserCreds.wireguard:type_name -> vpn.control.v1.WireGuardCreds
	17, // 24: vpn.control.v1.ControlPlane.Workstream:input_type -> vpn.control.v1.AgentToControl
	8,  // 25: vpn.control.v1.ControlPlane.Workstream:output_type -> vpn.control.v1.ControlToAgent
	25, // [25:26] is the sub-list for method output_type
	24, // [24:25] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_api_control_control_proto_init() }
func file_api_control_control_proto_init() {
	if File_api_control_control_proto != nil {
		return
	}
	file_api_control_control_proto_msgTypes[7].OneofWrappers = []any{
		(*Task_Upsert)(nil),
		(*Task_Remove)(nil),
		(*Task_StatsAll)(nil),
		(*Task_StatsUser)(nil),
	}
	file_api_control_control_proto_msgTypes[8].OneofWrappers = []any{
		(*ControlToAgent_Welcome)(nil),
		(*ControlToAgent_Task)(nil),
	}
	file_api_control_control_proto_msgTypes[16].OneofWrappers = []any{
		(*Response_Upsert)(nil),
		(*Response_Remove)(nil),
		(*Response_StatsAll)(nil),
		(*Response_StatsUser)(nil),
		(*Response_Error)(nil),
	}
	file_api_control_control_proto_msgTypes[17].OneofWrappers = []any{
		(*AgentToControl_Hello)(nil),
		(*AgentToControl_Resp)(nil),
		(*AgentToControl_Hb)(nil),
	}
	file_api_control_control_proto_msgTypes[20].OneofWrappers = []any{
		(*UserCreds_Vless)(nil),
		(*UserCreds_Wireguard)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_control_control_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_control_control_proto_goTypes,
		DependencyIndexes: file_api_control_control_proto_depIdxs,
		MessageInfos:      file_api_control_control_proto_msgTypes,
	}.Build()
	File_api_control_control_proto = out.File
	file_api_control_control_proto_rawDesc = nil
	file_api_control_control_proto_goTypes = nil
	file_api_control_control_proto_depIdxs = nil
}
