// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.2
// source: api/control/control.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	DriverTypes   []string               `protobuf:"bytes,4,rep,name=driver_types,json=driverTypes,proto3" json:"driver_types,omitempty"` // xray
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_api_control_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{0}
}

func (x *AgentHello) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentHello) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *AgentHello) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AgentHello) GetDriverTypes() []string {
	if x != nil {
		return x.DriverTypes
	}
	return nil
}

type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_api_control_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{1}
}

func (x *Welcome) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Welcome) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ControlToAgent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ControlToAgent_Welcome
	//	*ControlToAgent_Task
	Message       isControlToAgent_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlToAgent) Reset() {
	*x = ControlToAgent{}
	mi := &file_api_control_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlToAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlToAgent) ProtoMessage() {}

func (x *ControlToAgent) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlToAgent.ProtoReflect.Descriptor instead.
func (*ControlToAgent) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{2}
}

func (x *ControlToAgent) GetMessage() isControlToAgent_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ControlToAgent) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Message.(*ControlToAgent_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ControlToAgent) GetTask() *Task {
	if x != nil {
		if x, ok := x.Message.(*ControlToAgent_Task); ok {
			return x.Task
		}
	}
	return nil
}

type isControlToAgent_Message interface {
	isControlToAgent_Message()
}

type ControlToAgent_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ControlToAgent_Task struct {
	Task *Task `protobuf:"bytes,2,opt,name=task,proto3,oneof"`
}

func (*ControlToAgent_Welcome) isControlToAgent_Message() {}

func (*ControlToAgent_Task) isControlToAgent_Message() {}

type Task struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // idempotency
	// Types that are valid to be assigned to Body:
	//
	//	*Task_Upsert
	//	*Task_Remove
	Body          isTask_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_control_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{3}
}

func (x *Task) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Task) GetBody() isTask_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Task) GetUpsert() *UserUpsertRequest {
	if x != nil {
		if x, ok := x.Body.(*Task_Upsert); ok {
			return x.Upsert
		}
	}
	return nil
}

func (x *Task) GetRemove() *UserRemoveRequest {
	if x != nil {
		if x, ok := x.Body.(*Task_Remove); ok {
			return x.Remove
		}
	}
	return nil
}

type isTask_Body interface {
	isTask_Body()
}

type Task_Upsert struct {
	Upsert *UserUpsertRequest `protobuf:"bytes,2,opt,name=upsert,proto3,oneof"`
}

type Task_Remove struct {
	Remove *UserRemoveRequest `protobuf:"bytes,3,opt,name=remove,proto3,oneof"`
}

func (*Task_Upsert) isTask_Body() {}

func (*Task_Remove) isTask_Body() {}

type UserUpsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpsertRequest) Reset() {
	*x = UserUpsertRequest{}
	mi := &file_api_control_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpsertRequest) ProtoMessage() {}

func (x *UserUpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpsertRequest.ProtoReflect.Descriptor instead.
func (*UserUpsertRequest) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{4}
}

func (x *UserUpsertRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserRemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRemoveRequest) Reset() {
	*x = UserRemoveRequest{}
	mi := &file_api_control_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRemoveRequest) ProtoMessage() {}

func (x *UserRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRemoveRequest.ProtoReflect.Descriptor instead.
func (*UserRemoveRequest) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{5}
}

func (x *UserRemoveRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type AgentToControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentToControl_Hello
	//	*AgentToControl_Resp
	//	*AgentToControl_Stats
	Msg           isAgentToControl_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentToControl) Reset() {
	*x = AgentToControl{}
	mi := &file_api_control_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentToControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentToControl) ProtoMessage() {}

func (x *AgentToControl) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentToControl.ProtoReflect.Descriptor instead.
func (*AgentToControl) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{6}
}

func (x *AgentToControl) GetMsg() isAgentToControl_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentToControl) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Msg.(*AgentToControl_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentToControl) GetResp() *Response {
	if x != nil {
		if x, ok := x.Msg.(*AgentToControl_Resp); ok {
			return x.Resp
		}
	}
	return nil
}

func (x *AgentToControl) GetStats() *Stats {
	if x != nil {
		if x, ok := x.Msg.(*AgentToControl_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

type isAgentToControl_Msg interface {
	isAgentToControl_Msg()
}

type AgentToControl_Hello struct {
	Hello *AgentHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentToControl_Resp struct {
	Resp *Response `protobuf:"bytes,2,opt,name=resp,proto3,oneof"`
}

type AgentToControl_Stats struct {
	Stats *Stats `protobuf:"bytes,3,opt,name=stats,proto3,oneof"`
}

func (*AgentToControl_Hello) isAgentToControl_Msg() {}

func (*AgentToControl_Resp) isAgentToControl_Msg() {}

func (*AgentToControl_Stats) isAgentToControl_Msg() {}

type Response struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // idempotency
	// Types that are valid to be assigned to Body:
	//
	//	*Response_Upsert
	//	*Response_Remove
	//	*Response_Error
	Body          isResponse_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_api_control_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{7}
}

func (x *Response) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Response) GetBody() isResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Response) GetUpsert() *UserUpsertResponse {
	if x != nil {
		if x, ok := x.Body.(*Response_Upsert); ok {
			return x.Upsert
		}
	}
	return nil
}

func (x *Response) GetRemove() *UserRemoveResponse {
	if x != nil {
		if x, ok := x.Body.(*Response_Remove); ok {
			return x.Remove
		}
	}
	return nil
}

func (x *Response) GetError() string {
	if x != nil {
		if x, ok := x.Body.(*Response_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isResponse_Body interface {
	isResponse_Body()
}

type Response_Upsert struct {
	Upsert *UserUpsertResponse `protobuf:"bytes,2,opt,name=upsert,proto3,oneof"`
}

type Response_Remove struct {
	Remove *UserRemoveResponse `protobuf:"bytes,3,opt,name=remove,proto3,oneof"`
}

type Response_Error struct {
	Error string `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*Response_Upsert) isResponse_Body() {}

func (*Response_Remove) isResponse_Body() {}

func (*Response_Error) isResponse_Body() {}

type UserUpsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creds         *UserCreds             `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpsertResponse) Reset() {
	*x = UserUpsertResponse{}
	mi := &file_api_control_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpsertResponse) ProtoMessage() {}

func (x *UserUpsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpsertResponse.ProtoReflect.Descriptor instead.
func (*UserUpsertResponse) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{8}
}

func (x *UserUpsertResponse) GetCreds() *UserCreds {
	if x != nil {
		return x.Creds
	}
	return nil
}

type UserRemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRemoveResponse) Reset() {
	*x = UserRemoveResponse{}
	mi := &file_api_control_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRemoveResponse) ProtoMessage() {}

func (x *UserRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRemoveResponse.ProtoReflect.Descriptor instead.
func (*UserRemoveResponse) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{9}
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	UptimeSeconds uint32                 `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	WindowEnd     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"` // конец окна агрегации
	Users         []*UserUsage           `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_api_control_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{10}
}

func (x *Stats) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Stats) GetUptimeSeconds() uint32 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Stats) GetWindowEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowEnd
	}
	return nil
}

func (x *Stats) GetUsers() []*UserUsage {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserUsage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Дельта за окно. Если в окне юзер не передавал данных
	// и devices_count == 0 — агент НЕ включает его в users.
	BytesUp       uint64 `protobuf:"varint,2,opt,name=bytes_up,json=bytesUp,proto3" json:"bytes_up,omitempty"`
	BytesDown     uint64 `protobuf:"varint,3,opt,name=bytes_down,json=bytesDown,proto3" json:"bytes_down,omitempty"`
	IpCount       uint32 `protobuf:"varint,4,opt,name=ip_count,json=ipCount,proto3" json:"ip_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUsage) Reset() {
	*x = UserUsage{}
	mi := &file_api_control_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUsage) ProtoMessage() {}

func (x *UserUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUsage.ProtoReflect.Descriptor instead.
func (*UserUsage) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{11}
}

func (x *UserUsage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserUsage) GetBytesUp() uint64 {
	if x != nil {
		return x.BytesUp
	}
	return 0
}

func (x *UserUsage) GetBytesDown() uint64 {
	if x != nil {
		return x.BytesDown
	}
	return 0
}

func (x *UserUsage) GetIpCount() uint32 {
	if x != nil {
		return x.IpCount
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DriverType    string                 `protobuf:"bytes,2,opt,name=driver_type,json=driverType,proto3" json:"driver_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_control_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{12}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetDriverType() string {
	if x != nil {
		return x.DriverType
	}
	return ""
}

type UserCreds struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	UserId      string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AgentId     string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	DriverType  string                 `protobuf:"bytes,3,opt,name=driver_type,json=driverType,proto3" json:"driver_type,omitempty"`
	GeneratedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	// Types that are valid to be assigned to Config:
	//
	//	*UserCreds_Vless
	Config        isUserCreds_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreds) Reset() {
	*x = UserCreds{}
	mi := &file_api_control_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreds) ProtoMessage() {}

func (x *UserCreds) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreds.ProtoReflect.Descriptor instead.
func (*UserCreds) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{13}
}

func (x *UserCreds) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserCreds) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UserCreds) GetDriverType() string {
	if x != nil {
		return x.DriverType
	}
	return ""
}

func (x *UserCreds) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *UserCreds) GetConfig() isUserCreds_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UserCreds) GetVless() *VlessCreds {
	if x != nil {
		if x, ok := x.Config.(*UserCreds_Vless); ok {
			return x.Vless
		}
	}
	return nil
}

type isUserCreds_Config interface {
	isUserCreds_Config()
}

type UserCreds_Vless struct {
	Vless *VlessCreds `protobuf:"bytes,5,opt,name=vless,proto3,oneof"`
}

func (*UserCreds_Vless) isUserCreds_Config() {}

// Vless + reality
type VlessCreds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VlessCreds) Reset() {
	*x = VlessCreds{}
	mi := &file_api_control_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlessCreds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlessCreds) ProtoMessage() {}

func (x *VlessCreds) ProtoReflect() protoreflect.Message {
	mi := &file_api_control_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlessCreds.ProtoReflect.Descriptor instead.
func (*VlessCreds) Descriptor() ([]byte, []int) {
	return file_api_control_control_proto_rawDescGZIP(), []int{14}
}

func (x *VlessCreds) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

var File_api_control_control_proto protoreflect.FileDescriptor

var file_api_control_control_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x76, 0x70, 0x6e,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x01, 0x0a,
	0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12,
	0x21, 0x0a, 0x0c, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x73, 0x22, 0x3e, 0x0a, 0x07, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x7c, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x54, 0x6f, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x07, 0x77, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x48, 0x00,
	0x52, 0x07, 0x77, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x61, 0x73,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x48, 0x00, 0x52,
	0x04, 0x74, 0x61, 0x73, 0x6b, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0xa7, 0x01, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x3b, 0x0a, 0x06, 0x75, 0x70, 0x73, 0x65,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70,
	0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x75,
	0x70, 0x73, 0x65, 0x72, 0x74, 0x12, 0x3b, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x3d, 0x0a, 0x11, 0x55, 0x73,
	0x65, 0x72, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x28, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x3d, 0x0a, 0x11, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76,
	0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0xaa, 0x01, 0x0a, 0x0e, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x54, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x32, 0x0a, 0x05, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x76, 0x70, 0x6e,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12,
	0x2e, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x12,
	0x2d, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x42, 0x05,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xc5, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x3c, 0x0a, 0x06, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e,
	0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x06, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x12,
	0x3c, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x16, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x45, 0x0a,
	0x12, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x63, 0x72, 0x65, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x73, 0x52, 0x05, 0x63,
	0x72, 0x65, 0x64, 0x73, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xb5, 0x01, 0x0a, 0x05, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x25, 0x0a, 0x0e, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x53,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77,
	0x5f, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x45, 0x6e,
	0x64, 0x12, 0x2f, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x55, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x22, 0x79, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x5f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x55, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x64, 0x6f, 0x77,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x62, 0x79, 0x74, 0x65, 0x73, 0x44, 0x6f,
	0x77, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x70, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x69, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x40, 0x0a,
	0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x22,
	0xdd, 0x01, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x73, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x32, 0x0a, 0x05, 0x76, 0x6c, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76,
	0x31, 0x2e, 0x56, 0x6c, 0x65, 0x73, 0x73, 0x43, 0x72, 0x65, 0x64, 0x73, 0x48, 0x00, 0x52, 0x05,
	0x76, 0x6c, 0x65, 0x73, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22,
	0x1e, 0x0a, 0x0a, 0x56, 0x6c, 0x65, 0x73, 0x73, 0x43, 0x72, 0x65, 0x64, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x32,
	0x60, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x12,
	0x50, 0x0a, 0x0a, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1e, 0x2e,
	0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x1a, 0x1e, 0x2e,
	0x76, 0x70, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x54, 0x6f, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x1f, 0x5a, 0x1d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x3b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_control_control_proto_rawDescOnce sync.Once
	file_api_control_control_proto_rawDescData = file_api_control_control_proto_rawDesc
)

func file_api_control_control_proto_rawDescGZIP() []byte {
	file_api_control_control_proto_rawDescOnce.Do(func() {
		file_api_control_control_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_control_control_proto_rawDescData)
	})
	return file_api_control_control_proto_rawDescData
}

var file_api_control_control_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_control_control_proto_goTypes = []any{
	(*AgentHello)(nil),            // 0: vpn.control.v1.AgentHello
	(*Welcome)(nil),               // 1: vpn.control.v1.Welcome
	(*ControlToAgent)(nil),        // 2: vpn.control.v1.ControlToAgent
	(*Task)(nil),                  // 3: vpn.control.v1.Task
	(*UserUpsertRequest)(nil),     // 4: vpn.control.v1.UserUpsertRequest
	(*UserRemoveRequest)(nil),     // 5: vpn.control.v1.UserRemoveRequest
	(*AgentToControl)(nil),        // 6: vpn.control.v1.AgentToControl
	(*Response)(nil),              // 7: vpn.control.v1.Response
	(*UserUpsertResponse)(nil),    // 8: vpn.control.v1.UserUpsertResponse
	(*UserRemoveResponse)(nil),    // 9: vpn.control.v1.UserRemoveResponse
	(*Stats)(nil),                 // 10: vpn.control.v1.Stats
	(*UserUsage)(nil),             // 11: vpn.control.v1.UserUsage
	(*User)(nil),                  // 12: vpn.control.v1.User
	(*UserCreds)(nil),             // 13: vpn.control.v1.UserCreds
	(*VlessCreds)(nil),            // 14: vpn.control.v1.VlessCreds
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_api_control_control_proto_depIdxs = []int32{
	1,  // 0: vpn.control.v1.ControlToAgent.welcome:type_name -> vpn.control.v1.Welcome
	3,  // 1: vpn.control.v1.ControlToAgent.task:type_name -> vpn.control.v1.Task
	4,  // 2: vpn.control.v1.Task.upsert:type_name -> vpn.control.v1.UserUpsertRequest
	5,  // 3: vpn.control.v1.Task.remove:type_name -> vpn.control.v1.UserRemoveRequest
	12, // 4: vpn.control.v1.UserUpsertRequest.user:type_name -> vpn.control.v1.User
	12, // 5: vpn.control.v1.UserRemoveRequest.user:type_name -> vpn.control.v1.User
	0,  // 6: vpn.control.v1.AgentToControl.hello:type_name -> vpn.control.v1.AgentHello
	7,  // 7: vpn.control.v1.AgentToControl.resp:type_name -> vpn.control.v1.Response
	10, // 8: vpn.control.v1.AgentToControl.stats:type_name -> vpn.control.v1.Stats
	8,  // 9: vpn.control.v1.Response.upsert:type_name -> vpn.control.v1.UserUpsertResponse
	9,  // 10: vpn.control.v1.Response.remove:type_name -> vpn.control.v1.UserRemoveResponse
	13, // 11: vpn.control.v1.UserUpsertResponse.creds:type_name -> vpn.control.v1.UserCreds
	15, // 12: vpn.control.v1.Stats.window_end:type_name -> google.protobuf.Timestamp
	11, // 13: vpn.control.v1.Stats.users:type_name -> vpn.control.v1.UserUsage
	15, // 14: vpn.control.v1.UserCreds.generated_at:type_name -> google.protobuf.Timestamp
	14, // 15: vpn.control.v1.UserCreds.vless:type_name -> vpn.control.v1.VlessCreds
	6,  // 16: vpn.control.v1.ControlPlane.Workstream:input_type -> vpn.control.v1.AgentToControl
	2,  // 17: vpn.control.v1.ControlPlane.Workstream:output_type -> vpn.control.v1.ControlToAgent
	17, // [17:18] is the sub-list for method output_type
	16, // [16:17] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_control_control_proto_init() }
func file_api_control_control_proto_init() {
	if File_api_control_control_proto != nil {
		return
	}
	file_api_control_control_proto_msgTypes[2].OneofWrappers = []any{
		(*ControlToAgent_Welcome)(nil),
		(*ControlToAgent_Task)(nil),
	}
	file_api_control_control_proto_msgTypes[3].OneofWrappers = []any{
		(*Task_Upsert)(nil),
		(*Task_Remove)(nil),
	}
	file_api_control_control_proto_msgTypes[6].OneofWrappers = []any{
		(*AgentToControl_Hello)(nil),
		(*AgentToControl_Resp)(nil),
		(*AgentToControl_Stats)(nil),
	}
	file_api_control_control_proto_msgTypes[7].OneofWrappers = []any{
		(*Response_Upsert)(nil),
		(*Response_Remove)(nil),
		(*Response_Error)(nil),
	}
	file_api_control_control_proto_msgTypes[13].OneofWrappers = []any{
		(*UserCreds_Vless)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_control_control_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_control_control_proto_goTypes,
		DependencyIndexes: file_api_control_control_proto_depIdxs,
		MessageInfos:      file_api_control_control_proto_msgTypes,
	}.Build()
	File_api_control_control_proto = out.File
	file_api_control_control_proto_rawDesc = nil
	file_api_control_control_proto_goTypes = nil
	file_api_control_control_proto_depIdxs = nil
}
