syntax = "proto3";

package vpn.control.v1;
option go_package = "control/api/control;controlpb";


import "google/protobuf/timestamp.proto";

service ControlPlane {
  // Agent first opened stream and send AgentHello,
  // Server response welcome, and only after this start send tasks
  rpc Workstream(stream AgentToControl) returns (stream ControlToAgent);
}

// Handshake

message AgentHello {
  string agent_id = 1;
  string instance_id = 2;
  string region = 3;
  repeated string driver_types = 4; // xray
}

message Welcome {
  string agent_id = 1;
  string message = 2;
}


// Control-plane --> agent

message ControlToAgent {
  oneof message {
    Welcome welcome = 1;
    Task task = 2;
  }
}

message Task {
  string request_id = 1; // idempotency

  oneof body {
    UserUpsertRequest  upsert = 2;
    UserRemoveRequest  remove = 3;
  }
}

message UserUpsertRequest {User user = 1;}
message UserRemoveRequest {User user = 1;}


// Agent --> Control-plane

message AgentToControl {
  oneof msg {
    AgentHello hello = 1;
    Response resp = 2;
    Stats stats = 3;
  }
}

message Response {
  string request_id = 1; // idempotency

  oneof body {
    UserUpsertResponse  upsert = 2;
    UserRemoveResponse  remove = 3;

    string error = 4;
  }
}

message UserUpsertResponse {UserCreds creds = 1;}
message UserRemoveResponse {}

message Stats {
  string  agent_id = 1;
  uint32  uptime_seconds = 2;

  google.protobuf.Timestamp window_end = 3;  // конец окна агрегации
  repeated UserUsage users = 4;
}

message UserUsage {
  string user_id = 1;

  // Дельта за окно. Если в окне юзер не передавал данных
  // и devices_count == 0 — агент НЕ включает его в users.
  uint64 bytes_up = 2;
  uint64 bytes_down = 3;
  uint32 ip_count = 4;
}

// General Types

message User {
  string user_id = 1;
  string driver_type = 2;
}

message UserCreds {
  string user_id = 1;
  string agent_id = 2;
  string driver_type = 3;
  google.protobuf.Timestamp generated_at = 4;

  oneof config {
    VlessCreds     vless = 5;
  }
}

// Vless + reality
message VlessCreds {
  string uri = 1;
}
