// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i control-plane/internal/service.ProcessStorage -o process_storage_mock.go -n ProcessStorageMock -p mocks

import (
	"context"
	"control-plane/internal/model"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ProcessStorageMock implements mm_service.ProcessStorage
type ProcessStorageMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateSubscription          func(ctx context.Context, sub *model.Subscription) (err error)
	funcCreateSubscriptionOrigin    string
	inspectFuncCreateSubscription   func(ctx context.Context, sub *model.Subscription)
	afterCreateSubscriptionCounter  uint64
	beforeCreateSubscriptionCounter uint64
	CreateSubscriptionMock          mProcessStorageMockCreateSubscription

	funcGetInvoiceByProviderOrder          func(ctx context.Context, providerName string, providerOrderID string) (ip1 *model.Invoice, err error)
	funcGetInvoiceByProviderOrderOrigin    string
	inspectFuncGetInvoiceByProviderOrder   func(ctx context.Context, providerName string, providerOrderID string)
	afterGetInvoiceByProviderOrderCounter  uint64
	beforeGetInvoiceByProviderOrderCounter uint64
	GetInvoiceByProviderOrderMock          mProcessStorageMockGetInvoiceByProviderOrder

	funcGetPlanByID          func(ctx context.Context, planID string) (pp1 *model.Plan, err error)
	funcGetPlanByIDOrigin    string
	inspectFuncGetPlanByID   func(ctx context.Context, planID string)
	afterGetPlanByIDCounter  uint64
	beforeGetPlanByIDCounter uint64
	GetPlanByIDMock          mProcessStorageMockGetPlanByID

	funcUpdateInvoice          func(ctx context.Context, invoice *model.Invoice) (err error)
	funcUpdateInvoiceOrigin    string
	inspectFuncUpdateInvoice   func(ctx context.Context, invoice *model.Invoice)
	afterUpdateInvoiceCounter  uint64
	beforeUpdateInvoiceCounter uint64
	UpdateInvoiceMock          mProcessStorageMockUpdateInvoice

	funcWithTx          func(ctx context.Context, fn func(ctx context.Context) error) (err error)
	funcWithTxOrigin    string
	inspectFuncWithTx   func(ctx context.Context, fn func(ctx context.Context) error)
	afterWithTxCounter  uint64
	beforeWithTxCounter uint64
	WithTxMock          mProcessStorageMockWithTx
}

// NewProcessStorageMock returns a mock for mm_service.ProcessStorage
func NewProcessStorageMock(t minimock.Tester) *ProcessStorageMock {
	m := &ProcessStorageMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateSubscriptionMock = mProcessStorageMockCreateSubscription{mock: m}
	m.CreateSubscriptionMock.callArgs = []*ProcessStorageMockCreateSubscriptionParams{}

	m.GetInvoiceByProviderOrderMock = mProcessStorageMockGetInvoiceByProviderOrder{mock: m}
	m.GetInvoiceByProviderOrderMock.callArgs = []*ProcessStorageMockGetInvoiceByProviderOrderParams{}

	m.GetPlanByIDMock = mProcessStorageMockGetPlanByID{mock: m}
	m.GetPlanByIDMock.callArgs = []*ProcessStorageMockGetPlanByIDParams{}

	m.UpdateInvoiceMock = mProcessStorageMockUpdateInvoice{mock: m}
	m.UpdateInvoiceMock.callArgs = []*ProcessStorageMockUpdateInvoiceParams{}

	m.WithTxMock = mProcessStorageMockWithTx{mock: m}
	m.WithTxMock.callArgs = []*ProcessStorageMockWithTxParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mProcessStorageMockCreateSubscription struct {
	optional           bool
	mock               *ProcessStorageMock
	defaultExpectation *ProcessStorageMockCreateSubscriptionExpectation
	expectations       []*ProcessStorageMockCreateSubscriptionExpectation

	callArgs []*ProcessStorageMockCreateSubscriptionParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ProcessStorageMockCreateSubscriptionExpectation specifies expectation struct of the ProcessStorage.CreateSubscription
type ProcessStorageMockCreateSubscriptionExpectation struct {
	mock               *ProcessStorageMock
	params             *ProcessStorageMockCreateSubscriptionParams
	paramPtrs          *ProcessStorageMockCreateSubscriptionParamPtrs
	expectationOrigins ProcessStorageMockCreateSubscriptionExpectationOrigins
	results            *ProcessStorageMockCreateSubscriptionResults
	returnOrigin       string
	Counter            uint64
}

// ProcessStorageMockCreateSubscriptionParams contains parameters of the ProcessStorage.CreateSubscription
type ProcessStorageMockCreateSubscriptionParams struct {
	ctx context.Context
	sub *model.Subscription
}

// ProcessStorageMockCreateSubscriptionParamPtrs contains pointers to parameters of the ProcessStorage.CreateSubscription
type ProcessStorageMockCreateSubscriptionParamPtrs struct {
	ctx *context.Context
	sub **model.Subscription
}

// ProcessStorageMockCreateSubscriptionResults contains results of the ProcessStorage.CreateSubscription
type ProcessStorageMockCreateSubscriptionResults struct {
	err error
}

// ProcessStorageMockCreateSubscriptionOrigins contains origins of expectations of the ProcessStorage.CreateSubscription
type ProcessStorageMockCreateSubscriptionExpectationOrigins struct {
	origin    string
	originCtx string
	originSub string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateSubscription *mProcessStorageMockCreateSubscription) Optional() *mProcessStorageMockCreateSubscription {
	mmCreateSubscription.optional = true
	return mmCreateSubscription
}

// Expect sets up expected params for ProcessStorage.CreateSubscription
func (mmCreateSubscription *mProcessStorageMockCreateSubscription) Expect(ctx context.Context, sub *model.Subscription) *mProcessStorageMockCreateSubscription {
	if mmCreateSubscription.mock.funcCreateSubscription != nil {
		mmCreateSubscription.mock.t.Fatalf("ProcessStorageMock.CreateSubscription mock is already set by Set")
	}

	if mmCreateSubscription.defaultExpectation == nil {
		mmCreateSubscription.defaultExpectation = &ProcessStorageMockCreateSubscriptionExpectation{}
	}

	if mmCreateSubscription.defaultExpectation.paramPtrs != nil {
		mmCreateSubscription.mock.t.Fatalf("ProcessStorageMock.CreateSubscription mock is already set by ExpectParams functions")
	}

	mmCreateSubscription.defaultExpectation.params = &ProcessStorageMockCreateSubscriptionParams{ctx, sub}
	mmCreateSubscription.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateSubscription.expectations {
		if minimock.Equal(e.params, mmCreateSubscription.defaultExpectation.params) {
			mmCreateSubscription.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateSubscription.defaultExpectation.params)
		}
	}

	return mmCreateSubscription
}

// ExpectCtxParam1 sets up expected param ctx for ProcessStorage.CreateSubscription
func (mmCreateSubscription *mProcessStorageMockCreateSubscription) ExpectCtxParam1(ctx context.Context) *mProcessStorageMockCreateSubscription {
	if mmCreateSubscription.mock.funcCreateSubscription != nil {
		mmCreateSubscription.mock.t.Fatalf("ProcessStorageMock.CreateSubscription mock is already set by Set")
	}

	if mmCreateSubscription.defaultExpectation == nil {
		mmCreateSubscription.defaultExpectation = &ProcessStorageMockCreateSubscriptionExpectation{}
	}

	if mmCreateSubscription.defaultExpectation.params != nil {
		mmCreateSubscription.mock.t.Fatalf("ProcessStorageMock.CreateSubscription mock is already set by Expect")
	}

	if mmCreateSubscription.defaultExpectation.paramPtrs == nil {
		mmCreateSubscription.defaultExpectation.paramPtrs = &ProcessStorageMockCreateSubscriptionParamPtrs{}
	}
	mmCreateSubscription.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateSubscription.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateSubscription
}

// ExpectSubParam2 sets up expected param sub for ProcessStorage.CreateSubscription
func (mmCreateSubscription *mProcessStorageMockCreateSubscription) ExpectSubParam2(sub *model.Subscription) *mProcessStorageMockCreateSubscription {
	if mmCreateSubscription.mock.funcCreateSubscription != nil {
		mmCreateSubscription.mock.t.Fatalf("ProcessStorageMock.CreateSubscription mock is already set by Set")
	}

	if mmCreateSubscription.defaultExpectation == nil {
		mmCreateSubscription.defaultExpectation = &ProcessStorageMockCreateSubscriptionExpectation{}
	}

	if mmCreateSubscription.defaultExpectation.params != nil {
		mmCreateSubscription.mock.t.Fatalf("ProcessStorageMock.CreateSubscription mock is already set by Expect")
	}

	if mmCreateSubscription.defaultExpectation.paramPtrs == nil {
		mmCreateSubscription.defaultExpectation.paramPtrs = &ProcessStorageMockCreateSubscriptionParamPtrs{}
	}
	mmCreateSubscription.defaultExpectation.paramPtrs.sub = &sub
	mmCreateSubscription.defaultExpectation.expectationOrigins.originSub = minimock.CallerInfo(1)

	return mmCreateSubscription
}

// Inspect accepts an inspector function that has same arguments as the ProcessStorage.CreateSubscription
func (mmCreateSubscription *mProcessStorageMockCreateSubscription) Inspect(f func(ctx context.Context, sub *model.Subscription)) *mProcessStorageMockCreateSubscription {
	if mmCreateSubscription.mock.inspectFuncCreateSubscription != nil {
		mmCreateSubscription.mock.t.Fatalf("Inspect function is already set for ProcessStorageMock.CreateSubscription")
	}

	mmCreateSubscription.mock.inspectFuncCreateSubscription = f

	return mmCreateSubscription
}

// Return sets up results that will be returned by ProcessStorage.CreateSubscription
func (mmCreateSubscription *mProcessStorageMockCreateSubscription) Return(err error) *ProcessStorageMock {
	if mmCreateSubscription.mock.funcCreateSubscription != nil {
		mmCreateSubscription.mock.t.Fatalf("ProcessStorageMock.CreateSubscription mock is already set by Set")
	}

	if mmCreateSubscription.defaultExpectation == nil {
		mmCreateSubscription.defaultExpectation = &ProcessStorageMockCreateSubscriptionExpectation{mock: mmCreateSubscription.mock}
	}
	mmCreateSubscription.defaultExpectation.results = &ProcessStorageMockCreateSubscriptionResults{err}
	mmCreateSubscription.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateSubscription.mock
}

// Set uses given function f to mock the ProcessStorage.CreateSubscription method
func (mmCreateSubscription *mProcessStorageMockCreateSubscription) Set(f func(ctx context.Context, sub *model.Subscription) (err error)) *ProcessStorageMock {
	if mmCreateSubscription.defaultExpectation != nil {
		mmCreateSubscription.mock.t.Fatalf("Default expectation is already set for the ProcessStorage.CreateSubscription method")
	}

	if len(mmCreateSubscription.expectations) > 0 {
		mmCreateSubscription.mock.t.Fatalf("Some expectations are already set for the ProcessStorage.CreateSubscription method")
	}

	mmCreateSubscription.mock.funcCreateSubscription = f
	mmCreateSubscription.mock.funcCreateSubscriptionOrigin = minimock.CallerInfo(1)
	return mmCreateSubscription.mock
}

// When sets expectation for the ProcessStorage.CreateSubscription which will trigger the result defined by the following
// Then helper
func (mmCreateSubscription *mProcessStorageMockCreateSubscription) When(ctx context.Context, sub *model.Subscription) *ProcessStorageMockCreateSubscriptionExpectation {
	if mmCreateSubscription.mock.funcCreateSubscription != nil {
		mmCreateSubscription.mock.t.Fatalf("ProcessStorageMock.CreateSubscription mock is already set by Set")
	}

	expectation := &ProcessStorageMockCreateSubscriptionExpectation{
		mock:               mmCreateSubscription.mock,
		params:             &ProcessStorageMockCreateSubscriptionParams{ctx, sub},
		expectationOrigins: ProcessStorageMockCreateSubscriptionExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateSubscription.expectations = append(mmCreateSubscription.expectations, expectation)
	return expectation
}

// Then sets up ProcessStorage.CreateSubscription return parameters for the expectation previously defined by the When method
func (e *ProcessStorageMockCreateSubscriptionExpectation) Then(err error) *ProcessStorageMock {
	e.results = &ProcessStorageMockCreateSubscriptionResults{err}
	return e.mock
}

// Times sets number of times ProcessStorage.CreateSubscription should be invoked
func (mmCreateSubscription *mProcessStorageMockCreateSubscription) Times(n uint64) *mProcessStorageMockCreateSubscription {
	if n == 0 {
		mmCreateSubscription.mock.t.Fatalf("Times of ProcessStorageMock.CreateSubscription mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateSubscription.expectedInvocations, n)
	mmCreateSubscription.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateSubscription
}

func (mmCreateSubscription *mProcessStorageMockCreateSubscription) invocationsDone() bool {
	if len(mmCreateSubscription.expectations) == 0 && mmCreateSubscription.defaultExpectation == nil && mmCreateSubscription.mock.funcCreateSubscription == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateSubscription.mock.afterCreateSubscriptionCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateSubscription.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateSubscription implements mm_service.ProcessStorage
func (mmCreateSubscription *ProcessStorageMock) CreateSubscription(ctx context.Context, sub *model.Subscription) (err error) {
	mm_atomic.AddUint64(&mmCreateSubscription.beforeCreateSubscriptionCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateSubscription.afterCreateSubscriptionCounter, 1)

	mmCreateSubscription.t.Helper()

	if mmCreateSubscription.inspectFuncCreateSubscription != nil {
		mmCreateSubscription.inspectFuncCreateSubscription(ctx, sub)
	}

	mm_params := ProcessStorageMockCreateSubscriptionParams{ctx, sub}

	// Record call args
	mmCreateSubscription.CreateSubscriptionMock.mutex.Lock()
	mmCreateSubscription.CreateSubscriptionMock.callArgs = append(mmCreateSubscription.CreateSubscriptionMock.callArgs, &mm_params)
	mmCreateSubscription.CreateSubscriptionMock.mutex.Unlock()

	for _, e := range mmCreateSubscription.CreateSubscriptionMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmCreateSubscription.CreateSubscriptionMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateSubscription.CreateSubscriptionMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateSubscription.CreateSubscriptionMock.defaultExpectation.params
		mm_want_ptrs := mmCreateSubscription.CreateSubscriptionMock.defaultExpectation.paramPtrs

		mm_got := ProcessStorageMockCreateSubscriptionParams{ctx, sub}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateSubscription.t.Errorf("ProcessStorageMock.CreateSubscription got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateSubscription.CreateSubscriptionMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.sub != nil && !minimock.Equal(*mm_want_ptrs.sub, mm_got.sub) {
				mmCreateSubscription.t.Errorf("ProcessStorageMock.CreateSubscription got unexpected parameter sub, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateSubscription.CreateSubscriptionMock.defaultExpectation.expectationOrigins.originSub, *mm_want_ptrs.sub, mm_got.sub, minimock.Diff(*mm_want_ptrs.sub, mm_got.sub))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateSubscription.t.Errorf("ProcessStorageMock.CreateSubscription got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateSubscription.CreateSubscriptionMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateSubscription.CreateSubscriptionMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateSubscription.t.Fatal("No results are set for the ProcessStorageMock.CreateSubscription")
		}
		return (*mm_results).err
	}
	if mmCreateSubscription.funcCreateSubscription != nil {
		return mmCreateSubscription.funcCreateSubscription(ctx, sub)
	}
	mmCreateSubscription.t.Fatalf("Unexpected call to ProcessStorageMock.CreateSubscription. %v %v", ctx, sub)
	return
}

// CreateSubscriptionAfterCounter returns a count of finished ProcessStorageMock.CreateSubscription invocations
func (mmCreateSubscription *ProcessStorageMock) CreateSubscriptionAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateSubscription.afterCreateSubscriptionCounter)
}

// CreateSubscriptionBeforeCounter returns a count of ProcessStorageMock.CreateSubscription invocations
func (mmCreateSubscription *ProcessStorageMock) CreateSubscriptionBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateSubscription.beforeCreateSubscriptionCounter)
}

// Calls returns a list of arguments used in each call to ProcessStorageMock.CreateSubscription.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateSubscription *mProcessStorageMockCreateSubscription) Calls() []*ProcessStorageMockCreateSubscriptionParams {
	mmCreateSubscription.mutex.RLock()

	argCopy := make([]*ProcessStorageMockCreateSubscriptionParams, len(mmCreateSubscription.callArgs))
	copy(argCopy, mmCreateSubscription.callArgs)

	mmCreateSubscription.mutex.RUnlock()

	return argCopy
}

// MinimockCreateSubscriptionDone returns true if the count of the CreateSubscription invocations corresponds
// the number of defined expectations
func (m *ProcessStorageMock) MinimockCreateSubscriptionDone() bool {
	if m.CreateSubscriptionMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateSubscriptionMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateSubscriptionMock.invocationsDone()
}

// MinimockCreateSubscriptionInspect logs each unmet expectation
func (m *ProcessStorageMock) MinimockCreateSubscriptionInspect() {
	for _, e := range m.CreateSubscriptionMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ProcessStorageMock.CreateSubscription at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateSubscriptionCounter := mm_atomic.LoadUint64(&m.afterCreateSubscriptionCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateSubscriptionMock.defaultExpectation != nil && afterCreateSubscriptionCounter < 1 {
		if m.CreateSubscriptionMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ProcessStorageMock.CreateSubscription at\n%s", m.CreateSubscriptionMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ProcessStorageMock.CreateSubscription at\n%s with params: %#v", m.CreateSubscriptionMock.defaultExpectation.expectationOrigins.origin, *m.CreateSubscriptionMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateSubscription != nil && afterCreateSubscriptionCounter < 1 {
		m.t.Errorf("Expected call to ProcessStorageMock.CreateSubscription at\n%s", m.funcCreateSubscriptionOrigin)
	}

	if !m.CreateSubscriptionMock.invocationsDone() && afterCreateSubscriptionCounter > 0 {
		m.t.Errorf("Expected %d calls to ProcessStorageMock.CreateSubscription at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateSubscriptionMock.expectedInvocations), m.CreateSubscriptionMock.expectedInvocationsOrigin, afterCreateSubscriptionCounter)
	}
}

type mProcessStorageMockGetInvoiceByProviderOrder struct {
	optional           bool
	mock               *ProcessStorageMock
	defaultExpectation *ProcessStorageMockGetInvoiceByProviderOrderExpectation
	expectations       []*ProcessStorageMockGetInvoiceByProviderOrderExpectation

	callArgs []*ProcessStorageMockGetInvoiceByProviderOrderParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ProcessStorageMockGetInvoiceByProviderOrderExpectation specifies expectation struct of the ProcessStorage.GetInvoiceByProviderOrder
type ProcessStorageMockGetInvoiceByProviderOrderExpectation struct {
	mock               *ProcessStorageMock
	params             *ProcessStorageMockGetInvoiceByProviderOrderParams
	paramPtrs          *ProcessStorageMockGetInvoiceByProviderOrderParamPtrs
	expectationOrigins ProcessStorageMockGetInvoiceByProviderOrderExpectationOrigins
	results            *ProcessStorageMockGetInvoiceByProviderOrderResults
	returnOrigin       string
	Counter            uint64
}

// ProcessStorageMockGetInvoiceByProviderOrderParams contains parameters of the ProcessStorage.GetInvoiceByProviderOrder
type ProcessStorageMockGetInvoiceByProviderOrderParams struct {
	ctx             context.Context
	providerName    string
	providerOrderID string
}

// ProcessStorageMockGetInvoiceByProviderOrderParamPtrs contains pointers to parameters of the ProcessStorage.GetInvoiceByProviderOrder
type ProcessStorageMockGetInvoiceByProviderOrderParamPtrs struct {
	ctx             *context.Context
	providerName    *string
	providerOrderID *string
}

// ProcessStorageMockGetInvoiceByProviderOrderResults contains results of the ProcessStorage.GetInvoiceByProviderOrder
type ProcessStorageMockGetInvoiceByProviderOrderResults struct {
	ip1 *model.Invoice
	err error
}

// ProcessStorageMockGetInvoiceByProviderOrderOrigins contains origins of expectations of the ProcessStorage.GetInvoiceByProviderOrder
type ProcessStorageMockGetInvoiceByProviderOrderExpectationOrigins struct {
	origin                string
	originCtx             string
	originProviderName    string
	originProviderOrderID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetInvoiceByProviderOrder *mProcessStorageMockGetInvoiceByProviderOrder) Optional() *mProcessStorageMockGetInvoiceByProviderOrder {
	mmGetInvoiceByProviderOrder.optional = true
	return mmGetInvoiceByProviderOrder
}

// Expect sets up expected params for ProcessStorage.GetInvoiceByProviderOrder
func (mmGetInvoiceByProviderOrder *mProcessStorageMockGetInvoiceByProviderOrder) Expect(ctx context.Context, providerName string, providerOrderID string) *mProcessStorageMockGetInvoiceByProviderOrder {
	if mmGetInvoiceByProviderOrder.mock.funcGetInvoiceByProviderOrder != nil {
		mmGetInvoiceByProviderOrder.mock.t.Fatalf("ProcessStorageMock.GetInvoiceByProviderOrder mock is already set by Set")
	}

	if mmGetInvoiceByProviderOrder.defaultExpectation == nil {
		mmGetInvoiceByProviderOrder.defaultExpectation = &ProcessStorageMockGetInvoiceByProviderOrderExpectation{}
	}

	if mmGetInvoiceByProviderOrder.defaultExpectation.paramPtrs != nil {
		mmGetInvoiceByProviderOrder.mock.t.Fatalf("ProcessStorageMock.GetInvoiceByProviderOrder mock is already set by ExpectParams functions")
	}

	mmGetInvoiceByProviderOrder.defaultExpectation.params = &ProcessStorageMockGetInvoiceByProviderOrderParams{ctx, providerName, providerOrderID}
	mmGetInvoiceByProviderOrder.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetInvoiceByProviderOrder.expectations {
		if minimock.Equal(e.params, mmGetInvoiceByProviderOrder.defaultExpectation.params) {
			mmGetInvoiceByProviderOrder.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetInvoiceByProviderOrder.defaultExpectation.params)
		}
	}

	return mmGetInvoiceByProviderOrder
}

// ExpectCtxParam1 sets up expected param ctx for ProcessStorage.GetInvoiceByProviderOrder
func (mmGetInvoiceByProviderOrder *mProcessStorageMockGetInvoiceByProviderOrder) ExpectCtxParam1(ctx context.Context) *mProcessStorageMockGetInvoiceByProviderOrder {
	if mmGetInvoiceByProviderOrder.mock.funcGetInvoiceByProviderOrder != nil {
		mmGetInvoiceByProviderOrder.mock.t.Fatalf("ProcessStorageMock.GetInvoiceByProviderOrder mock is already set by Set")
	}

	if mmGetInvoiceByProviderOrder.defaultExpectation == nil {
		mmGetInvoiceByProviderOrder.defaultExpectation = &ProcessStorageMockGetInvoiceByProviderOrderExpectation{}
	}

	if mmGetInvoiceByProviderOrder.defaultExpectation.params != nil {
		mmGetInvoiceByProviderOrder.mock.t.Fatalf("ProcessStorageMock.GetInvoiceByProviderOrder mock is already set by Expect")
	}

	if mmGetInvoiceByProviderOrder.defaultExpectation.paramPtrs == nil {
		mmGetInvoiceByProviderOrder.defaultExpectation.paramPtrs = &ProcessStorageMockGetInvoiceByProviderOrderParamPtrs{}
	}
	mmGetInvoiceByProviderOrder.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetInvoiceByProviderOrder.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetInvoiceByProviderOrder
}

// ExpectProviderNameParam2 sets up expected param providerName for ProcessStorage.GetInvoiceByProviderOrder
func (mmGetInvoiceByProviderOrder *mProcessStorageMockGetInvoiceByProviderOrder) ExpectProviderNameParam2(providerName string) *mProcessStorageMockGetInvoiceByProviderOrder {
	if mmGetInvoiceByProviderOrder.mock.funcGetInvoiceByProviderOrder != nil {
		mmGetInvoiceByProviderOrder.mock.t.Fatalf("ProcessStorageMock.GetInvoiceByProviderOrder mock is already set by Set")
	}

	if mmGetInvoiceByProviderOrder.defaultExpectation == nil {
		mmGetInvoiceByProviderOrder.defaultExpectation = &ProcessStorageMockGetInvoiceByProviderOrderExpectation{}
	}

	if mmGetInvoiceByProviderOrder.defaultExpectation.params != nil {
		mmGetInvoiceByProviderOrder.mock.t.Fatalf("ProcessStorageMock.GetInvoiceByProviderOrder mock is already set by Expect")
	}

	if mmGetInvoiceByProviderOrder.defaultExpectation.paramPtrs == nil {
		mmGetInvoiceByProviderOrder.defaultExpectation.paramPtrs = &ProcessStorageMockGetInvoiceByProviderOrderParamPtrs{}
	}
	mmGetInvoiceByProviderOrder.defaultExpectation.paramPtrs.providerName = &providerName
	mmGetInvoiceByProviderOrder.defaultExpectation.expectationOrigins.originProviderName = minimock.CallerInfo(1)

	return mmGetInvoiceByProviderOrder
}

// ExpectProviderOrderIDParam3 sets up expected param providerOrderID for ProcessStorage.GetInvoiceByProviderOrder
func (mmGetInvoiceByProviderOrder *mProcessStorageMockGetInvoiceByProviderOrder) ExpectProviderOrderIDParam3(providerOrderID string) *mProcessStorageMockGetInvoiceByProviderOrder {
	if mmGetInvoiceByProviderOrder.mock.funcGetInvoiceByProviderOrder != nil {
		mmGetInvoiceByProviderOrder.mock.t.Fatalf("ProcessStorageMock.GetInvoiceByProviderOrder mock is already set by Set")
	}

	if mmGetInvoiceByProviderOrder.defaultExpectation == nil {
		mmGetInvoiceByProviderOrder.defaultExpectation = &ProcessStorageMockGetInvoiceByProviderOrderExpectation{}
	}

	if mmGetInvoiceByProviderOrder.defaultExpectation.params != nil {
		mmGetInvoiceByProviderOrder.mock.t.Fatalf("ProcessStorageMock.GetInvoiceByProviderOrder mock is already set by Expect")
	}

	if mmGetInvoiceByProviderOrder.defaultExpectation.paramPtrs == nil {
		mmGetInvoiceByProviderOrder.defaultExpectation.paramPtrs = &ProcessStorageMockGetInvoiceByProviderOrderParamPtrs{}
	}
	mmGetInvoiceByProviderOrder.defaultExpectation.paramPtrs.providerOrderID = &providerOrderID
	mmGetInvoiceByProviderOrder.defaultExpectation.expectationOrigins.originProviderOrderID = minimock.CallerInfo(1)

	return mmGetInvoiceByProviderOrder
}

// Inspect accepts an inspector function that has same arguments as the ProcessStorage.GetInvoiceByProviderOrder
func (mmGetInvoiceByProviderOrder *mProcessStorageMockGetInvoiceByProviderOrder) Inspect(f func(ctx context.Context, providerName string, providerOrderID string)) *mProcessStorageMockGetInvoiceByProviderOrder {
	if mmGetInvoiceByProviderOrder.mock.inspectFuncGetInvoiceByProviderOrder != nil {
		mmGetInvoiceByProviderOrder.mock.t.Fatalf("Inspect function is already set for ProcessStorageMock.GetInvoiceByProviderOrder")
	}

	mmGetInvoiceByProviderOrder.mock.inspectFuncGetInvoiceByProviderOrder = f

	return mmGetInvoiceByProviderOrder
}

// Return sets up results that will be returned by ProcessStorage.GetInvoiceByProviderOrder
func (mmGetInvoiceByProviderOrder *mProcessStorageMockGetInvoiceByProviderOrder) Return(ip1 *model.Invoice, err error) *ProcessStorageMock {
	if mmGetInvoiceByProviderOrder.mock.funcGetInvoiceByProviderOrder != nil {
		mmGetInvoiceByProviderOrder.mock.t.Fatalf("ProcessStorageMock.GetInvoiceByProviderOrder mock is already set by Set")
	}

	if mmGetInvoiceByProviderOrder.defaultExpectation == nil {
		mmGetInvoiceByProviderOrder.defaultExpectation = &ProcessStorageMockGetInvoiceByProviderOrderExpectation{mock: mmGetInvoiceByProviderOrder.mock}
	}
	mmGetInvoiceByProviderOrder.defaultExpectation.results = &ProcessStorageMockGetInvoiceByProviderOrderResults{ip1, err}
	mmGetInvoiceByProviderOrder.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetInvoiceByProviderOrder.mock
}

// Set uses given function f to mock the ProcessStorage.GetInvoiceByProviderOrder method
func (mmGetInvoiceByProviderOrder *mProcessStorageMockGetInvoiceByProviderOrder) Set(f func(ctx context.Context, providerName string, providerOrderID string) (ip1 *model.Invoice, err error)) *ProcessStorageMock {
	if mmGetInvoiceByProviderOrder.defaultExpectation != nil {
		mmGetInvoiceByProviderOrder.mock.t.Fatalf("Default expectation is already set for the ProcessStorage.GetInvoiceByProviderOrder method")
	}

	if len(mmGetInvoiceByProviderOrder.expectations) > 0 {
		mmGetInvoiceByProviderOrder.mock.t.Fatalf("Some expectations are already set for the ProcessStorage.GetInvoiceByProviderOrder method")
	}

	mmGetInvoiceByProviderOrder.mock.funcGetInvoiceByProviderOrder = f
	mmGetInvoiceByProviderOrder.mock.funcGetInvoiceByProviderOrderOrigin = minimock.CallerInfo(1)
	return mmGetInvoiceByProviderOrder.mock
}

// When sets expectation for the ProcessStorage.GetInvoiceByProviderOrder which will trigger the result defined by the following
// Then helper
func (mmGetInvoiceByProviderOrder *mProcessStorageMockGetInvoiceByProviderOrder) When(ctx context.Context, providerName string, providerOrderID string) *ProcessStorageMockGetInvoiceByProviderOrderExpectation {
	if mmGetInvoiceByProviderOrder.mock.funcGetInvoiceByProviderOrder != nil {
		mmGetInvoiceByProviderOrder.mock.t.Fatalf("ProcessStorageMock.GetInvoiceByProviderOrder mock is already set by Set")
	}

	expectation := &ProcessStorageMockGetInvoiceByProviderOrderExpectation{
		mock:               mmGetInvoiceByProviderOrder.mock,
		params:             &ProcessStorageMockGetInvoiceByProviderOrderParams{ctx, providerName, providerOrderID},
		expectationOrigins: ProcessStorageMockGetInvoiceByProviderOrderExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetInvoiceByProviderOrder.expectations = append(mmGetInvoiceByProviderOrder.expectations, expectation)
	return expectation
}

// Then sets up ProcessStorage.GetInvoiceByProviderOrder return parameters for the expectation previously defined by the When method
func (e *ProcessStorageMockGetInvoiceByProviderOrderExpectation) Then(ip1 *model.Invoice, err error) *ProcessStorageMock {
	e.results = &ProcessStorageMockGetInvoiceByProviderOrderResults{ip1, err}
	return e.mock
}

// Times sets number of times ProcessStorage.GetInvoiceByProviderOrder should be invoked
func (mmGetInvoiceByProviderOrder *mProcessStorageMockGetInvoiceByProviderOrder) Times(n uint64) *mProcessStorageMockGetInvoiceByProviderOrder {
	if n == 0 {
		mmGetInvoiceByProviderOrder.mock.t.Fatalf("Times of ProcessStorageMock.GetInvoiceByProviderOrder mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetInvoiceByProviderOrder.expectedInvocations, n)
	mmGetInvoiceByProviderOrder.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetInvoiceByProviderOrder
}

func (mmGetInvoiceByProviderOrder *mProcessStorageMockGetInvoiceByProviderOrder) invocationsDone() bool {
	if len(mmGetInvoiceByProviderOrder.expectations) == 0 && mmGetInvoiceByProviderOrder.defaultExpectation == nil && mmGetInvoiceByProviderOrder.mock.funcGetInvoiceByProviderOrder == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetInvoiceByProviderOrder.mock.afterGetInvoiceByProviderOrderCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetInvoiceByProviderOrder.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetInvoiceByProviderOrder implements mm_service.ProcessStorage
func (mmGetInvoiceByProviderOrder *ProcessStorageMock) GetInvoiceByProviderOrder(ctx context.Context, providerName string, providerOrderID string) (ip1 *model.Invoice, err error) {
	mm_atomic.AddUint64(&mmGetInvoiceByProviderOrder.beforeGetInvoiceByProviderOrderCounter, 1)
	defer mm_atomic.AddUint64(&mmGetInvoiceByProviderOrder.afterGetInvoiceByProviderOrderCounter, 1)

	mmGetInvoiceByProviderOrder.t.Helper()

	if mmGetInvoiceByProviderOrder.inspectFuncGetInvoiceByProviderOrder != nil {
		mmGetInvoiceByProviderOrder.inspectFuncGetInvoiceByProviderOrder(ctx, providerName, providerOrderID)
	}

	mm_params := ProcessStorageMockGetInvoiceByProviderOrderParams{ctx, providerName, providerOrderID}

	// Record call args
	mmGetInvoiceByProviderOrder.GetInvoiceByProviderOrderMock.mutex.Lock()
	mmGetInvoiceByProviderOrder.GetInvoiceByProviderOrderMock.callArgs = append(mmGetInvoiceByProviderOrder.GetInvoiceByProviderOrderMock.callArgs, &mm_params)
	mmGetInvoiceByProviderOrder.GetInvoiceByProviderOrderMock.mutex.Unlock()

	for _, e := range mmGetInvoiceByProviderOrder.GetInvoiceByProviderOrderMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ip1, e.results.err
		}
	}

	if mmGetInvoiceByProviderOrder.GetInvoiceByProviderOrderMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetInvoiceByProviderOrder.GetInvoiceByProviderOrderMock.defaultExpectation.Counter, 1)
		mm_want := mmGetInvoiceByProviderOrder.GetInvoiceByProviderOrderMock.defaultExpectation.params
		mm_want_ptrs := mmGetInvoiceByProviderOrder.GetInvoiceByProviderOrderMock.defaultExpectation.paramPtrs

		mm_got := ProcessStorageMockGetInvoiceByProviderOrderParams{ctx, providerName, providerOrderID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetInvoiceByProviderOrder.t.Errorf("ProcessStorageMock.GetInvoiceByProviderOrder got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetInvoiceByProviderOrder.GetInvoiceByProviderOrderMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.providerName != nil && !minimock.Equal(*mm_want_ptrs.providerName, mm_got.providerName) {
				mmGetInvoiceByProviderOrder.t.Errorf("ProcessStorageMock.GetInvoiceByProviderOrder got unexpected parameter providerName, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetInvoiceByProviderOrder.GetInvoiceByProviderOrderMock.defaultExpectation.expectationOrigins.originProviderName, *mm_want_ptrs.providerName, mm_got.providerName, minimock.Diff(*mm_want_ptrs.providerName, mm_got.providerName))
			}

			if mm_want_ptrs.providerOrderID != nil && !minimock.Equal(*mm_want_ptrs.providerOrderID, mm_got.providerOrderID) {
				mmGetInvoiceByProviderOrder.t.Errorf("ProcessStorageMock.GetInvoiceByProviderOrder got unexpected parameter providerOrderID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetInvoiceByProviderOrder.GetInvoiceByProviderOrderMock.defaultExpectation.expectationOrigins.originProviderOrderID, *mm_want_ptrs.providerOrderID, mm_got.providerOrderID, minimock.Diff(*mm_want_ptrs.providerOrderID, mm_got.providerOrderID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetInvoiceByProviderOrder.t.Errorf("ProcessStorageMock.GetInvoiceByProviderOrder got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetInvoiceByProviderOrder.GetInvoiceByProviderOrderMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetInvoiceByProviderOrder.GetInvoiceByProviderOrderMock.defaultExpectation.results
		if mm_results == nil {
			mmGetInvoiceByProviderOrder.t.Fatal("No results are set for the ProcessStorageMock.GetInvoiceByProviderOrder")
		}
		return (*mm_results).ip1, (*mm_results).err
	}
	if mmGetInvoiceByProviderOrder.funcGetInvoiceByProviderOrder != nil {
		return mmGetInvoiceByProviderOrder.funcGetInvoiceByProviderOrder(ctx, providerName, providerOrderID)
	}
	mmGetInvoiceByProviderOrder.t.Fatalf("Unexpected call to ProcessStorageMock.GetInvoiceByProviderOrder. %v %v %v", ctx, providerName, providerOrderID)
	return
}

// GetInvoiceByProviderOrderAfterCounter returns a count of finished ProcessStorageMock.GetInvoiceByProviderOrder invocations
func (mmGetInvoiceByProviderOrder *ProcessStorageMock) GetInvoiceByProviderOrderAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetInvoiceByProviderOrder.afterGetInvoiceByProviderOrderCounter)
}

// GetInvoiceByProviderOrderBeforeCounter returns a count of ProcessStorageMock.GetInvoiceByProviderOrder invocations
func (mmGetInvoiceByProviderOrder *ProcessStorageMock) GetInvoiceByProviderOrderBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetInvoiceByProviderOrder.beforeGetInvoiceByProviderOrderCounter)
}

// Calls returns a list of arguments used in each call to ProcessStorageMock.GetInvoiceByProviderOrder.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetInvoiceByProviderOrder *mProcessStorageMockGetInvoiceByProviderOrder) Calls() []*ProcessStorageMockGetInvoiceByProviderOrderParams {
	mmGetInvoiceByProviderOrder.mutex.RLock()

	argCopy := make([]*ProcessStorageMockGetInvoiceByProviderOrderParams, len(mmGetInvoiceByProviderOrder.callArgs))
	copy(argCopy, mmGetInvoiceByProviderOrder.callArgs)

	mmGetInvoiceByProviderOrder.mutex.RUnlock()

	return argCopy
}

// MinimockGetInvoiceByProviderOrderDone returns true if the count of the GetInvoiceByProviderOrder invocations corresponds
// the number of defined expectations
func (m *ProcessStorageMock) MinimockGetInvoiceByProviderOrderDone() bool {
	if m.GetInvoiceByProviderOrderMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetInvoiceByProviderOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetInvoiceByProviderOrderMock.invocationsDone()
}

// MinimockGetInvoiceByProviderOrderInspect logs each unmet expectation
func (m *ProcessStorageMock) MinimockGetInvoiceByProviderOrderInspect() {
	for _, e := range m.GetInvoiceByProviderOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ProcessStorageMock.GetInvoiceByProviderOrder at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetInvoiceByProviderOrderCounter := mm_atomic.LoadUint64(&m.afterGetInvoiceByProviderOrderCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetInvoiceByProviderOrderMock.defaultExpectation != nil && afterGetInvoiceByProviderOrderCounter < 1 {
		if m.GetInvoiceByProviderOrderMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ProcessStorageMock.GetInvoiceByProviderOrder at\n%s", m.GetInvoiceByProviderOrderMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ProcessStorageMock.GetInvoiceByProviderOrder at\n%s with params: %#v", m.GetInvoiceByProviderOrderMock.defaultExpectation.expectationOrigins.origin, *m.GetInvoiceByProviderOrderMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetInvoiceByProviderOrder != nil && afterGetInvoiceByProviderOrderCounter < 1 {
		m.t.Errorf("Expected call to ProcessStorageMock.GetInvoiceByProviderOrder at\n%s", m.funcGetInvoiceByProviderOrderOrigin)
	}

	if !m.GetInvoiceByProviderOrderMock.invocationsDone() && afterGetInvoiceByProviderOrderCounter > 0 {
		m.t.Errorf("Expected %d calls to ProcessStorageMock.GetInvoiceByProviderOrder at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetInvoiceByProviderOrderMock.expectedInvocations), m.GetInvoiceByProviderOrderMock.expectedInvocationsOrigin, afterGetInvoiceByProviderOrderCounter)
	}
}

type mProcessStorageMockGetPlanByID struct {
	optional           bool
	mock               *ProcessStorageMock
	defaultExpectation *ProcessStorageMockGetPlanByIDExpectation
	expectations       []*ProcessStorageMockGetPlanByIDExpectation

	callArgs []*ProcessStorageMockGetPlanByIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ProcessStorageMockGetPlanByIDExpectation specifies expectation struct of the ProcessStorage.GetPlanByID
type ProcessStorageMockGetPlanByIDExpectation struct {
	mock               *ProcessStorageMock
	params             *ProcessStorageMockGetPlanByIDParams
	paramPtrs          *ProcessStorageMockGetPlanByIDParamPtrs
	expectationOrigins ProcessStorageMockGetPlanByIDExpectationOrigins
	results            *ProcessStorageMockGetPlanByIDResults
	returnOrigin       string
	Counter            uint64
}

// ProcessStorageMockGetPlanByIDParams contains parameters of the ProcessStorage.GetPlanByID
type ProcessStorageMockGetPlanByIDParams struct {
	ctx    context.Context
	planID string
}

// ProcessStorageMockGetPlanByIDParamPtrs contains pointers to parameters of the ProcessStorage.GetPlanByID
type ProcessStorageMockGetPlanByIDParamPtrs struct {
	ctx    *context.Context
	planID *string
}

// ProcessStorageMockGetPlanByIDResults contains results of the ProcessStorage.GetPlanByID
type ProcessStorageMockGetPlanByIDResults struct {
	pp1 *model.Plan
	err error
}

// ProcessStorageMockGetPlanByIDOrigins contains origins of expectations of the ProcessStorage.GetPlanByID
type ProcessStorageMockGetPlanByIDExpectationOrigins struct {
	origin       string
	originCtx    string
	originPlanID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetPlanByID *mProcessStorageMockGetPlanByID) Optional() *mProcessStorageMockGetPlanByID {
	mmGetPlanByID.optional = true
	return mmGetPlanByID
}

// Expect sets up expected params for ProcessStorage.GetPlanByID
func (mmGetPlanByID *mProcessStorageMockGetPlanByID) Expect(ctx context.Context, planID string) *mProcessStorageMockGetPlanByID {
	if mmGetPlanByID.mock.funcGetPlanByID != nil {
		mmGetPlanByID.mock.t.Fatalf("ProcessStorageMock.GetPlanByID mock is already set by Set")
	}

	if mmGetPlanByID.defaultExpectation == nil {
		mmGetPlanByID.defaultExpectation = &ProcessStorageMockGetPlanByIDExpectation{}
	}

	if mmGetPlanByID.defaultExpectation.paramPtrs != nil {
		mmGetPlanByID.mock.t.Fatalf("ProcessStorageMock.GetPlanByID mock is already set by ExpectParams functions")
	}

	mmGetPlanByID.defaultExpectation.params = &ProcessStorageMockGetPlanByIDParams{ctx, planID}
	mmGetPlanByID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetPlanByID.expectations {
		if minimock.Equal(e.params, mmGetPlanByID.defaultExpectation.params) {
			mmGetPlanByID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetPlanByID.defaultExpectation.params)
		}
	}

	return mmGetPlanByID
}

// ExpectCtxParam1 sets up expected param ctx for ProcessStorage.GetPlanByID
func (mmGetPlanByID *mProcessStorageMockGetPlanByID) ExpectCtxParam1(ctx context.Context) *mProcessStorageMockGetPlanByID {
	if mmGetPlanByID.mock.funcGetPlanByID != nil {
		mmGetPlanByID.mock.t.Fatalf("ProcessStorageMock.GetPlanByID mock is already set by Set")
	}

	if mmGetPlanByID.defaultExpectation == nil {
		mmGetPlanByID.defaultExpectation = &ProcessStorageMockGetPlanByIDExpectation{}
	}

	if mmGetPlanByID.defaultExpectation.params != nil {
		mmGetPlanByID.mock.t.Fatalf("ProcessStorageMock.GetPlanByID mock is already set by Expect")
	}

	if mmGetPlanByID.defaultExpectation.paramPtrs == nil {
		mmGetPlanByID.defaultExpectation.paramPtrs = &ProcessStorageMockGetPlanByIDParamPtrs{}
	}
	mmGetPlanByID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetPlanByID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetPlanByID
}

// ExpectPlanIDParam2 sets up expected param planID for ProcessStorage.GetPlanByID
func (mmGetPlanByID *mProcessStorageMockGetPlanByID) ExpectPlanIDParam2(planID string) *mProcessStorageMockGetPlanByID {
	if mmGetPlanByID.mock.funcGetPlanByID != nil {
		mmGetPlanByID.mock.t.Fatalf("ProcessStorageMock.GetPlanByID mock is already set by Set")
	}

	if mmGetPlanByID.defaultExpectation == nil {
		mmGetPlanByID.defaultExpectation = &ProcessStorageMockGetPlanByIDExpectation{}
	}

	if mmGetPlanByID.defaultExpectation.params != nil {
		mmGetPlanByID.mock.t.Fatalf("ProcessStorageMock.GetPlanByID mock is already set by Expect")
	}

	if mmGetPlanByID.defaultExpectation.paramPtrs == nil {
		mmGetPlanByID.defaultExpectation.paramPtrs = &ProcessStorageMockGetPlanByIDParamPtrs{}
	}
	mmGetPlanByID.defaultExpectation.paramPtrs.planID = &planID
	mmGetPlanByID.defaultExpectation.expectationOrigins.originPlanID = minimock.CallerInfo(1)

	return mmGetPlanByID
}

// Inspect accepts an inspector function that has same arguments as the ProcessStorage.GetPlanByID
func (mmGetPlanByID *mProcessStorageMockGetPlanByID) Inspect(f func(ctx context.Context, planID string)) *mProcessStorageMockGetPlanByID {
	if mmGetPlanByID.mock.inspectFuncGetPlanByID != nil {
		mmGetPlanByID.mock.t.Fatalf("Inspect function is already set for ProcessStorageMock.GetPlanByID")
	}

	mmGetPlanByID.mock.inspectFuncGetPlanByID = f

	return mmGetPlanByID
}

// Return sets up results that will be returned by ProcessStorage.GetPlanByID
func (mmGetPlanByID *mProcessStorageMockGetPlanByID) Return(pp1 *model.Plan, err error) *ProcessStorageMock {
	if mmGetPlanByID.mock.funcGetPlanByID != nil {
		mmGetPlanByID.mock.t.Fatalf("ProcessStorageMock.GetPlanByID mock is already set by Set")
	}

	if mmGetPlanByID.defaultExpectation == nil {
		mmGetPlanByID.defaultExpectation = &ProcessStorageMockGetPlanByIDExpectation{mock: mmGetPlanByID.mock}
	}
	mmGetPlanByID.defaultExpectation.results = &ProcessStorageMockGetPlanByIDResults{pp1, err}
	mmGetPlanByID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetPlanByID.mock
}

// Set uses given function f to mock the ProcessStorage.GetPlanByID method
func (mmGetPlanByID *mProcessStorageMockGetPlanByID) Set(f func(ctx context.Context, planID string) (pp1 *model.Plan, err error)) *ProcessStorageMock {
	if mmGetPlanByID.defaultExpectation != nil {
		mmGetPlanByID.mock.t.Fatalf("Default expectation is already set for the ProcessStorage.GetPlanByID method")
	}

	if len(mmGetPlanByID.expectations) > 0 {
		mmGetPlanByID.mock.t.Fatalf("Some expectations are already set for the ProcessStorage.GetPlanByID method")
	}

	mmGetPlanByID.mock.funcGetPlanByID = f
	mmGetPlanByID.mock.funcGetPlanByIDOrigin = minimock.CallerInfo(1)
	return mmGetPlanByID.mock
}

// When sets expectation for the ProcessStorage.GetPlanByID which will trigger the result defined by the following
// Then helper
func (mmGetPlanByID *mProcessStorageMockGetPlanByID) When(ctx context.Context, planID string) *ProcessStorageMockGetPlanByIDExpectation {
	if mmGetPlanByID.mock.funcGetPlanByID != nil {
		mmGetPlanByID.mock.t.Fatalf("ProcessStorageMock.GetPlanByID mock is already set by Set")
	}

	expectation := &ProcessStorageMockGetPlanByIDExpectation{
		mock:               mmGetPlanByID.mock,
		params:             &ProcessStorageMockGetPlanByIDParams{ctx, planID},
		expectationOrigins: ProcessStorageMockGetPlanByIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetPlanByID.expectations = append(mmGetPlanByID.expectations, expectation)
	return expectation
}

// Then sets up ProcessStorage.GetPlanByID return parameters for the expectation previously defined by the When method
func (e *ProcessStorageMockGetPlanByIDExpectation) Then(pp1 *model.Plan, err error) *ProcessStorageMock {
	e.results = &ProcessStorageMockGetPlanByIDResults{pp1, err}
	return e.mock
}

// Times sets number of times ProcessStorage.GetPlanByID should be invoked
func (mmGetPlanByID *mProcessStorageMockGetPlanByID) Times(n uint64) *mProcessStorageMockGetPlanByID {
	if n == 0 {
		mmGetPlanByID.mock.t.Fatalf("Times of ProcessStorageMock.GetPlanByID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetPlanByID.expectedInvocations, n)
	mmGetPlanByID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetPlanByID
}

func (mmGetPlanByID *mProcessStorageMockGetPlanByID) invocationsDone() bool {
	if len(mmGetPlanByID.expectations) == 0 && mmGetPlanByID.defaultExpectation == nil && mmGetPlanByID.mock.funcGetPlanByID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetPlanByID.mock.afterGetPlanByIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetPlanByID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetPlanByID implements mm_service.ProcessStorage
func (mmGetPlanByID *ProcessStorageMock) GetPlanByID(ctx context.Context, planID string) (pp1 *model.Plan, err error) {
	mm_atomic.AddUint64(&mmGetPlanByID.beforeGetPlanByIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetPlanByID.afterGetPlanByIDCounter, 1)

	mmGetPlanByID.t.Helper()

	if mmGetPlanByID.inspectFuncGetPlanByID != nil {
		mmGetPlanByID.inspectFuncGetPlanByID(ctx, planID)
	}

	mm_params := ProcessStorageMockGetPlanByIDParams{ctx, planID}

	// Record call args
	mmGetPlanByID.GetPlanByIDMock.mutex.Lock()
	mmGetPlanByID.GetPlanByIDMock.callArgs = append(mmGetPlanByID.GetPlanByIDMock.callArgs, &mm_params)
	mmGetPlanByID.GetPlanByIDMock.mutex.Unlock()

	for _, e := range mmGetPlanByID.GetPlanByIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.pp1, e.results.err
		}
	}

	if mmGetPlanByID.GetPlanByIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetPlanByID.GetPlanByIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetPlanByID.GetPlanByIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetPlanByID.GetPlanByIDMock.defaultExpectation.paramPtrs

		mm_got := ProcessStorageMockGetPlanByIDParams{ctx, planID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetPlanByID.t.Errorf("ProcessStorageMock.GetPlanByID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetPlanByID.GetPlanByIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.planID != nil && !minimock.Equal(*mm_want_ptrs.planID, mm_got.planID) {
				mmGetPlanByID.t.Errorf("ProcessStorageMock.GetPlanByID got unexpected parameter planID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetPlanByID.GetPlanByIDMock.defaultExpectation.expectationOrigins.originPlanID, *mm_want_ptrs.planID, mm_got.planID, minimock.Diff(*mm_want_ptrs.planID, mm_got.planID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetPlanByID.t.Errorf("ProcessStorageMock.GetPlanByID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetPlanByID.GetPlanByIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetPlanByID.GetPlanByIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetPlanByID.t.Fatal("No results are set for the ProcessStorageMock.GetPlanByID")
		}
		return (*mm_results).pp1, (*mm_results).err
	}
	if mmGetPlanByID.funcGetPlanByID != nil {
		return mmGetPlanByID.funcGetPlanByID(ctx, planID)
	}
	mmGetPlanByID.t.Fatalf("Unexpected call to ProcessStorageMock.GetPlanByID. %v %v", ctx, planID)
	return
}

// GetPlanByIDAfterCounter returns a count of finished ProcessStorageMock.GetPlanByID invocations
func (mmGetPlanByID *ProcessStorageMock) GetPlanByIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetPlanByID.afterGetPlanByIDCounter)
}

// GetPlanByIDBeforeCounter returns a count of ProcessStorageMock.GetPlanByID invocations
func (mmGetPlanByID *ProcessStorageMock) GetPlanByIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetPlanByID.beforeGetPlanByIDCounter)
}

// Calls returns a list of arguments used in each call to ProcessStorageMock.GetPlanByID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetPlanByID *mProcessStorageMockGetPlanByID) Calls() []*ProcessStorageMockGetPlanByIDParams {
	mmGetPlanByID.mutex.RLock()

	argCopy := make([]*ProcessStorageMockGetPlanByIDParams, len(mmGetPlanByID.callArgs))
	copy(argCopy, mmGetPlanByID.callArgs)

	mmGetPlanByID.mutex.RUnlock()

	return argCopy
}

// MinimockGetPlanByIDDone returns true if the count of the GetPlanByID invocations corresponds
// the number of defined expectations
func (m *ProcessStorageMock) MinimockGetPlanByIDDone() bool {
	if m.GetPlanByIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetPlanByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetPlanByIDMock.invocationsDone()
}

// MinimockGetPlanByIDInspect logs each unmet expectation
func (m *ProcessStorageMock) MinimockGetPlanByIDInspect() {
	for _, e := range m.GetPlanByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ProcessStorageMock.GetPlanByID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetPlanByIDCounter := mm_atomic.LoadUint64(&m.afterGetPlanByIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetPlanByIDMock.defaultExpectation != nil && afterGetPlanByIDCounter < 1 {
		if m.GetPlanByIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ProcessStorageMock.GetPlanByID at\n%s", m.GetPlanByIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ProcessStorageMock.GetPlanByID at\n%s with params: %#v", m.GetPlanByIDMock.defaultExpectation.expectationOrigins.origin, *m.GetPlanByIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetPlanByID != nil && afterGetPlanByIDCounter < 1 {
		m.t.Errorf("Expected call to ProcessStorageMock.GetPlanByID at\n%s", m.funcGetPlanByIDOrigin)
	}

	if !m.GetPlanByIDMock.invocationsDone() && afterGetPlanByIDCounter > 0 {
		m.t.Errorf("Expected %d calls to ProcessStorageMock.GetPlanByID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetPlanByIDMock.expectedInvocations), m.GetPlanByIDMock.expectedInvocationsOrigin, afterGetPlanByIDCounter)
	}
}

type mProcessStorageMockUpdateInvoice struct {
	optional           bool
	mock               *ProcessStorageMock
	defaultExpectation *ProcessStorageMockUpdateInvoiceExpectation
	expectations       []*ProcessStorageMockUpdateInvoiceExpectation

	callArgs []*ProcessStorageMockUpdateInvoiceParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ProcessStorageMockUpdateInvoiceExpectation specifies expectation struct of the ProcessStorage.UpdateInvoice
type ProcessStorageMockUpdateInvoiceExpectation struct {
	mock               *ProcessStorageMock
	params             *ProcessStorageMockUpdateInvoiceParams
	paramPtrs          *ProcessStorageMockUpdateInvoiceParamPtrs
	expectationOrigins ProcessStorageMockUpdateInvoiceExpectationOrigins
	results            *ProcessStorageMockUpdateInvoiceResults
	returnOrigin       string
	Counter            uint64
}

// ProcessStorageMockUpdateInvoiceParams contains parameters of the ProcessStorage.UpdateInvoice
type ProcessStorageMockUpdateInvoiceParams struct {
	ctx     context.Context
	invoice *model.Invoice
}

// ProcessStorageMockUpdateInvoiceParamPtrs contains pointers to parameters of the ProcessStorage.UpdateInvoice
type ProcessStorageMockUpdateInvoiceParamPtrs struct {
	ctx     *context.Context
	invoice **model.Invoice
}

// ProcessStorageMockUpdateInvoiceResults contains results of the ProcessStorage.UpdateInvoice
type ProcessStorageMockUpdateInvoiceResults struct {
	err error
}

// ProcessStorageMockUpdateInvoiceOrigins contains origins of expectations of the ProcessStorage.UpdateInvoice
type ProcessStorageMockUpdateInvoiceExpectationOrigins struct {
	origin        string
	originCtx     string
	originInvoice string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdateInvoice *mProcessStorageMockUpdateInvoice) Optional() *mProcessStorageMockUpdateInvoice {
	mmUpdateInvoice.optional = true
	return mmUpdateInvoice
}

// Expect sets up expected params for ProcessStorage.UpdateInvoice
func (mmUpdateInvoice *mProcessStorageMockUpdateInvoice) Expect(ctx context.Context, invoice *model.Invoice) *mProcessStorageMockUpdateInvoice {
	if mmUpdateInvoice.mock.funcUpdateInvoice != nil {
		mmUpdateInvoice.mock.t.Fatalf("ProcessStorageMock.UpdateInvoice mock is already set by Set")
	}

	if mmUpdateInvoice.defaultExpectation == nil {
		mmUpdateInvoice.defaultExpectation = &ProcessStorageMockUpdateInvoiceExpectation{}
	}

	if mmUpdateInvoice.defaultExpectation.paramPtrs != nil {
		mmUpdateInvoice.mock.t.Fatalf("ProcessStorageMock.UpdateInvoice mock is already set by ExpectParams functions")
	}

	mmUpdateInvoice.defaultExpectation.params = &ProcessStorageMockUpdateInvoiceParams{ctx, invoice}
	mmUpdateInvoice.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpdateInvoice.expectations {
		if minimock.Equal(e.params, mmUpdateInvoice.defaultExpectation.params) {
			mmUpdateInvoice.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdateInvoice.defaultExpectation.params)
		}
	}

	return mmUpdateInvoice
}

// ExpectCtxParam1 sets up expected param ctx for ProcessStorage.UpdateInvoice
func (mmUpdateInvoice *mProcessStorageMockUpdateInvoice) ExpectCtxParam1(ctx context.Context) *mProcessStorageMockUpdateInvoice {
	if mmUpdateInvoice.mock.funcUpdateInvoice != nil {
		mmUpdateInvoice.mock.t.Fatalf("ProcessStorageMock.UpdateInvoice mock is already set by Set")
	}

	if mmUpdateInvoice.defaultExpectation == nil {
		mmUpdateInvoice.defaultExpectation = &ProcessStorageMockUpdateInvoiceExpectation{}
	}

	if mmUpdateInvoice.defaultExpectation.params != nil {
		mmUpdateInvoice.mock.t.Fatalf("ProcessStorageMock.UpdateInvoice mock is already set by Expect")
	}

	if mmUpdateInvoice.defaultExpectation.paramPtrs == nil {
		mmUpdateInvoice.defaultExpectation.paramPtrs = &ProcessStorageMockUpdateInvoiceParamPtrs{}
	}
	mmUpdateInvoice.defaultExpectation.paramPtrs.ctx = &ctx
	mmUpdateInvoice.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUpdateInvoice
}

// ExpectInvoiceParam2 sets up expected param invoice for ProcessStorage.UpdateInvoice
func (mmUpdateInvoice *mProcessStorageMockUpdateInvoice) ExpectInvoiceParam2(invoice *model.Invoice) *mProcessStorageMockUpdateInvoice {
	if mmUpdateInvoice.mock.funcUpdateInvoice != nil {
		mmUpdateInvoice.mock.t.Fatalf("ProcessStorageMock.UpdateInvoice mock is already set by Set")
	}

	if mmUpdateInvoice.defaultExpectation == nil {
		mmUpdateInvoice.defaultExpectation = &ProcessStorageMockUpdateInvoiceExpectation{}
	}

	if mmUpdateInvoice.defaultExpectation.params != nil {
		mmUpdateInvoice.mock.t.Fatalf("ProcessStorageMock.UpdateInvoice mock is already set by Expect")
	}

	if mmUpdateInvoice.defaultExpectation.paramPtrs == nil {
		mmUpdateInvoice.defaultExpectation.paramPtrs = &ProcessStorageMockUpdateInvoiceParamPtrs{}
	}
	mmUpdateInvoice.defaultExpectation.paramPtrs.invoice = &invoice
	mmUpdateInvoice.defaultExpectation.expectationOrigins.originInvoice = minimock.CallerInfo(1)

	return mmUpdateInvoice
}

// Inspect accepts an inspector function that has same arguments as the ProcessStorage.UpdateInvoice
func (mmUpdateInvoice *mProcessStorageMockUpdateInvoice) Inspect(f func(ctx context.Context, invoice *model.Invoice)) *mProcessStorageMockUpdateInvoice {
	if mmUpdateInvoice.mock.inspectFuncUpdateInvoice != nil {
		mmUpdateInvoice.mock.t.Fatalf("Inspect function is already set for ProcessStorageMock.UpdateInvoice")
	}

	mmUpdateInvoice.mock.inspectFuncUpdateInvoice = f

	return mmUpdateInvoice
}

// Return sets up results that will be returned by ProcessStorage.UpdateInvoice
func (mmUpdateInvoice *mProcessStorageMockUpdateInvoice) Return(err error) *ProcessStorageMock {
	if mmUpdateInvoice.mock.funcUpdateInvoice != nil {
		mmUpdateInvoice.mock.t.Fatalf("ProcessStorageMock.UpdateInvoice mock is already set by Set")
	}

	if mmUpdateInvoice.defaultExpectation == nil {
		mmUpdateInvoice.defaultExpectation = &ProcessStorageMockUpdateInvoiceExpectation{mock: mmUpdateInvoice.mock}
	}
	mmUpdateInvoice.defaultExpectation.results = &ProcessStorageMockUpdateInvoiceResults{err}
	mmUpdateInvoice.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdateInvoice.mock
}

// Set uses given function f to mock the ProcessStorage.UpdateInvoice method
func (mmUpdateInvoice *mProcessStorageMockUpdateInvoice) Set(f func(ctx context.Context, invoice *model.Invoice) (err error)) *ProcessStorageMock {
	if mmUpdateInvoice.defaultExpectation != nil {
		mmUpdateInvoice.mock.t.Fatalf("Default expectation is already set for the ProcessStorage.UpdateInvoice method")
	}

	if len(mmUpdateInvoice.expectations) > 0 {
		mmUpdateInvoice.mock.t.Fatalf("Some expectations are already set for the ProcessStorage.UpdateInvoice method")
	}

	mmUpdateInvoice.mock.funcUpdateInvoice = f
	mmUpdateInvoice.mock.funcUpdateInvoiceOrigin = minimock.CallerInfo(1)
	return mmUpdateInvoice.mock
}

// When sets expectation for the ProcessStorage.UpdateInvoice which will trigger the result defined by the following
// Then helper
func (mmUpdateInvoice *mProcessStorageMockUpdateInvoice) When(ctx context.Context, invoice *model.Invoice) *ProcessStorageMockUpdateInvoiceExpectation {
	if mmUpdateInvoice.mock.funcUpdateInvoice != nil {
		mmUpdateInvoice.mock.t.Fatalf("ProcessStorageMock.UpdateInvoice mock is already set by Set")
	}

	expectation := &ProcessStorageMockUpdateInvoiceExpectation{
		mock:               mmUpdateInvoice.mock,
		params:             &ProcessStorageMockUpdateInvoiceParams{ctx, invoice},
		expectationOrigins: ProcessStorageMockUpdateInvoiceExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpdateInvoice.expectations = append(mmUpdateInvoice.expectations, expectation)
	return expectation
}

// Then sets up ProcessStorage.UpdateInvoice return parameters for the expectation previously defined by the When method
func (e *ProcessStorageMockUpdateInvoiceExpectation) Then(err error) *ProcessStorageMock {
	e.results = &ProcessStorageMockUpdateInvoiceResults{err}
	return e.mock
}

// Times sets number of times ProcessStorage.UpdateInvoice should be invoked
func (mmUpdateInvoice *mProcessStorageMockUpdateInvoice) Times(n uint64) *mProcessStorageMockUpdateInvoice {
	if n == 0 {
		mmUpdateInvoice.mock.t.Fatalf("Times of ProcessStorageMock.UpdateInvoice mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdateInvoice.expectedInvocations, n)
	mmUpdateInvoice.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdateInvoice
}

func (mmUpdateInvoice *mProcessStorageMockUpdateInvoice) invocationsDone() bool {
	if len(mmUpdateInvoice.expectations) == 0 && mmUpdateInvoice.defaultExpectation == nil && mmUpdateInvoice.mock.funcUpdateInvoice == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdateInvoice.mock.afterUpdateInvoiceCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdateInvoice.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// UpdateInvoice implements mm_service.ProcessStorage
func (mmUpdateInvoice *ProcessStorageMock) UpdateInvoice(ctx context.Context, invoice *model.Invoice) (err error) {
	mm_atomic.AddUint64(&mmUpdateInvoice.beforeUpdateInvoiceCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdateInvoice.afterUpdateInvoiceCounter, 1)

	mmUpdateInvoice.t.Helper()

	if mmUpdateInvoice.inspectFuncUpdateInvoice != nil {
		mmUpdateInvoice.inspectFuncUpdateInvoice(ctx, invoice)
	}

	mm_params := ProcessStorageMockUpdateInvoiceParams{ctx, invoice}

	// Record call args
	mmUpdateInvoice.UpdateInvoiceMock.mutex.Lock()
	mmUpdateInvoice.UpdateInvoiceMock.callArgs = append(mmUpdateInvoice.UpdateInvoiceMock.callArgs, &mm_params)
	mmUpdateInvoice.UpdateInvoiceMock.mutex.Unlock()

	for _, e := range mmUpdateInvoice.UpdateInvoiceMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmUpdateInvoice.UpdateInvoiceMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdateInvoice.UpdateInvoiceMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdateInvoice.UpdateInvoiceMock.defaultExpectation.params
		mm_want_ptrs := mmUpdateInvoice.UpdateInvoiceMock.defaultExpectation.paramPtrs

		mm_got := ProcessStorageMockUpdateInvoiceParams{ctx, invoice}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUpdateInvoice.t.Errorf("ProcessStorageMock.UpdateInvoice got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateInvoice.UpdateInvoiceMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.invoice != nil && !minimock.Equal(*mm_want_ptrs.invoice, mm_got.invoice) {
				mmUpdateInvoice.t.Errorf("ProcessStorageMock.UpdateInvoice got unexpected parameter invoice, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateInvoice.UpdateInvoiceMock.defaultExpectation.expectationOrigins.originInvoice, *mm_want_ptrs.invoice, mm_got.invoice, minimock.Diff(*mm_want_ptrs.invoice, mm_got.invoice))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdateInvoice.t.Errorf("ProcessStorageMock.UpdateInvoice got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpdateInvoice.UpdateInvoiceMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdateInvoice.UpdateInvoiceMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdateInvoice.t.Fatal("No results are set for the ProcessStorageMock.UpdateInvoice")
		}
		return (*mm_results).err
	}
	if mmUpdateInvoice.funcUpdateInvoice != nil {
		return mmUpdateInvoice.funcUpdateInvoice(ctx, invoice)
	}
	mmUpdateInvoice.t.Fatalf("Unexpected call to ProcessStorageMock.UpdateInvoice. %v %v", ctx, invoice)
	return
}

// UpdateInvoiceAfterCounter returns a count of finished ProcessStorageMock.UpdateInvoice invocations
func (mmUpdateInvoice *ProcessStorageMock) UpdateInvoiceAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateInvoice.afterUpdateInvoiceCounter)
}

// UpdateInvoiceBeforeCounter returns a count of ProcessStorageMock.UpdateInvoice invocations
func (mmUpdateInvoice *ProcessStorageMock) UpdateInvoiceBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateInvoice.beforeUpdateInvoiceCounter)
}

// Calls returns a list of arguments used in each call to ProcessStorageMock.UpdateInvoice.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdateInvoice *mProcessStorageMockUpdateInvoice) Calls() []*ProcessStorageMockUpdateInvoiceParams {
	mmUpdateInvoice.mutex.RLock()

	argCopy := make([]*ProcessStorageMockUpdateInvoiceParams, len(mmUpdateInvoice.callArgs))
	copy(argCopy, mmUpdateInvoice.callArgs)

	mmUpdateInvoice.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateInvoiceDone returns true if the count of the UpdateInvoice invocations corresponds
// the number of defined expectations
func (m *ProcessStorageMock) MinimockUpdateInvoiceDone() bool {
	if m.UpdateInvoiceMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateInvoiceMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateInvoiceMock.invocationsDone()
}

// MinimockUpdateInvoiceInspect logs each unmet expectation
func (m *ProcessStorageMock) MinimockUpdateInvoiceInspect() {
	for _, e := range m.UpdateInvoiceMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ProcessStorageMock.UpdateInvoice at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpdateInvoiceCounter := mm_atomic.LoadUint64(&m.afterUpdateInvoiceCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateInvoiceMock.defaultExpectation != nil && afterUpdateInvoiceCounter < 1 {
		if m.UpdateInvoiceMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ProcessStorageMock.UpdateInvoice at\n%s", m.UpdateInvoiceMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ProcessStorageMock.UpdateInvoice at\n%s with params: %#v", m.UpdateInvoiceMock.defaultExpectation.expectationOrigins.origin, *m.UpdateInvoiceMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateInvoice != nil && afterUpdateInvoiceCounter < 1 {
		m.t.Errorf("Expected call to ProcessStorageMock.UpdateInvoice at\n%s", m.funcUpdateInvoiceOrigin)
	}

	if !m.UpdateInvoiceMock.invocationsDone() && afterUpdateInvoiceCounter > 0 {
		m.t.Errorf("Expected %d calls to ProcessStorageMock.UpdateInvoice at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateInvoiceMock.expectedInvocations), m.UpdateInvoiceMock.expectedInvocationsOrigin, afterUpdateInvoiceCounter)
	}
}

type mProcessStorageMockWithTx struct {
	optional           bool
	mock               *ProcessStorageMock
	defaultExpectation *ProcessStorageMockWithTxExpectation
	expectations       []*ProcessStorageMockWithTxExpectation

	callArgs []*ProcessStorageMockWithTxParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ProcessStorageMockWithTxExpectation specifies expectation struct of the ProcessStorage.WithTx
type ProcessStorageMockWithTxExpectation struct {
	mock               *ProcessStorageMock
	params             *ProcessStorageMockWithTxParams
	paramPtrs          *ProcessStorageMockWithTxParamPtrs
	expectationOrigins ProcessStorageMockWithTxExpectationOrigins
	results            *ProcessStorageMockWithTxResults
	returnOrigin       string
	Counter            uint64
}

// ProcessStorageMockWithTxParams contains parameters of the ProcessStorage.WithTx
type ProcessStorageMockWithTxParams struct {
	ctx context.Context
	fn  func(ctx context.Context) error
}

// ProcessStorageMockWithTxParamPtrs contains pointers to parameters of the ProcessStorage.WithTx
type ProcessStorageMockWithTxParamPtrs struct {
	ctx *context.Context
	fn  *func(ctx context.Context) error
}

// ProcessStorageMockWithTxResults contains results of the ProcessStorage.WithTx
type ProcessStorageMockWithTxResults struct {
	err error
}

// ProcessStorageMockWithTxOrigins contains origins of expectations of the ProcessStorage.WithTx
type ProcessStorageMockWithTxExpectationOrigins struct {
	origin    string
	originCtx string
	originFn  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmWithTx *mProcessStorageMockWithTx) Optional() *mProcessStorageMockWithTx {
	mmWithTx.optional = true
	return mmWithTx
}

// Expect sets up expected params for ProcessStorage.WithTx
func (mmWithTx *mProcessStorageMockWithTx) Expect(ctx context.Context, fn func(ctx context.Context) error) *mProcessStorageMockWithTx {
	if mmWithTx.mock.funcWithTx != nil {
		mmWithTx.mock.t.Fatalf("ProcessStorageMock.WithTx mock is already set by Set")
	}

	if mmWithTx.defaultExpectation == nil {
		mmWithTx.defaultExpectation = &ProcessStorageMockWithTxExpectation{}
	}

	if mmWithTx.defaultExpectation.paramPtrs != nil {
		mmWithTx.mock.t.Fatalf("ProcessStorageMock.WithTx mock is already set by ExpectParams functions")
	}

	mmWithTx.defaultExpectation.params = &ProcessStorageMockWithTxParams{ctx, fn}
	mmWithTx.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmWithTx.expectations {
		if minimock.Equal(e.params, mmWithTx.defaultExpectation.params) {
			mmWithTx.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmWithTx.defaultExpectation.params)
		}
	}

	return mmWithTx
}

// ExpectCtxParam1 sets up expected param ctx for ProcessStorage.WithTx
func (mmWithTx *mProcessStorageMockWithTx) ExpectCtxParam1(ctx context.Context) *mProcessStorageMockWithTx {
	if mmWithTx.mock.funcWithTx != nil {
		mmWithTx.mock.t.Fatalf("ProcessStorageMock.WithTx mock is already set by Set")
	}

	if mmWithTx.defaultExpectation == nil {
		mmWithTx.defaultExpectation = &ProcessStorageMockWithTxExpectation{}
	}

	if mmWithTx.defaultExpectation.params != nil {
		mmWithTx.mock.t.Fatalf("ProcessStorageMock.WithTx mock is already set by Expect")
	}

	if mmWithTx.defaultExpectation.paramPtrs == nil {
		mmWithTx.defaultExpectation.paramPtrs = &ProcessStorageMockWithTxParamPtrs{}
	}
	mmWithTx.defaultExpectation.paramPtrs.ctx = &ctx
	mmWithTx.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmWithTx
}

// ExpectFnParam2 sets up expected param fn for ProcessStorage.WithTx
func (mmWithTx *mProcessStorageMockWithTx) ExpectFnParam2(fn func(ctx context.Context) error) *mProcessStorageMockWithTx {
	if mmWithTx.mock.funcWithTx != nil {
		mmWithTx.mock.t.Fatalf("ProcessStorageMock.WithTx mock is already set by Set")
	}

	if mmWithTx.defaultExpectation == nil {
		mmWithTx.defaultExpectation = &ProcessStorageMockWithTxExpectation{}
	}

	if mmWithTx.defaultExpectation.params != nil {
		mmWithTx.mock.t.Fatalf("ProcessStorageMock.WithTx mock is already set by Expect")
	}

	if mmWithTx.defaultExpectation.paramPtrs == nil {
		mmWithTx.defaultExpectation.paramPtrs = &ProcessStorageMockWithTxParamPtrs{}
	}
	mmWithTx.defaultExpectation.paramPtrs.fn = &fn
	mmWithTx.defaultExpectation.expectationOrigins.originFn = minimock.CallerInfo(1)

	return mmWithTx
}

// Inspect accepts an inspector function that has same arguments as the ProcessStorage.WithTx
func (mmWithTx *mProcessStorageMockWithTx) Inspect(f func(ctx context.Context, fn func(ctx context.Context) error)) *mProcessStorageMockWithTx {
	if mmWithTx.mock.inspectFuncWithTx != nil {
		mmWithTx.mock.t.Fatalf("Inspect function is already set for ProcessStorageMock.WithTx")
	}

	mmWithTx.mock.inspectFuncWithTx = f

	return mmWithTx
}

// Return sets up results that will be returned by ProcessStorage.WithTx
func (mmWithTx *mProcessStorageMockWithTx) Return(err error) *ProcessStorageMock {
	if mmWithTx.mock.funcWithTx != nil {
		mmWithTx.mock.t.Fatalf("ProcessStorageMock.WithTx mock is already set by Set")
	}

	if mmWithTx.defaultExpectation == nil {
		mmWithTx.defaultExpectation = &ProcessStorageMockWithTxExpectation{mock: mmWithTx.mock}
	}
	mmWithTx.defaultExpectation.results = &ProcessStorageMockWithTxResults{err}
	mmWithTx.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmWithTx.mock
}

// Set uses given function f to mock the ProcessStorage.WithTx method
func (mmWithTx *mProcessStorageMockWithTx) Set(f func(ctx context.Context, fn func(ctx context.Context) error) (err error)) *ProcessStorageMock {
	if mmWithTx.defaultExpectation != nil {
		mmWithTx.mock.t.Fatalf("Default expectation is already set for the ProcessStorage.WithTx method")
	}

	if len(mmWithTx.expectations) > 0 {
		mmWithTx.mock.t.Fatalf("Some expectations are already set for the ProcessStorage.WithTx method")
	}

	mmWithTx.mock.funcWithTx = f
	mmWithTx.mock.funcWithTxOrigin = minimock.CallerInfo(1)
	return mmWithTx.mock
}

// When sets expectation for the ProcessStorage.WithTx which will trigger the result defined by the following
// Then helper
func (mmWithTx *mProcessStorageMockWithTx) When(ctx context.Context, fn func(ctx context.Context) error) *ProcessStorageMockWithTxExpectation {
	if mmWithTx.mock.funcWithTx != nil {
		mmWithTx.mock.t.Fatalf("ProcessStorageMock.WithTx mock is already set by Set")
	}

	expectation := &ProcessStorageMockWithTxExpectation{
		mock:               mmWithTx.mock,
		params:             &ProcessStorageMockWithTxParams{ctx, fn},
		expectationOrigins: ProcessStorageMockWithTxExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmWithTx.expectations = append(mmWithTx.expectations, expectation)
	return expectation
}

// Then sets up ProcessStorage.WithTx return parameters for the expectation previously defined by the When method
func (e *ProcessStorageMockWithTxExpectation) Then(err error) *ProcessStorageMock {
	e.results = &ProcessStorageMockWithTxResults{err}
	return e.mock
}

// Times sets number of times ProcessStorage.WithTx should be invoked
func (mmWithTx *mProcessStorageMockWithTx) Times(n uint64) *mProcessStorageMockWithTx {
	if n == 0 {
		mmWithTx.mock.t.Fatalf("Times of ProcessStorageMock.WithTx mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmWithTx.expectedInvocations, n)
	mmWithTx.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmWithTx
}

func (mmWithTx *mProcessStorageMockWithTx) invocationsDone() bool {
	if len(mmWithTx.expectations) == 0 && mmWithTx.defaultExpectation == nil && mmWithTx.mock.funcWithTx == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmWithTx.mock.afterWithTxCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmWithTx.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// WithTx implements mm_service.ProcessStorage
func (mmWithTx *ProcessStorageMock) WithTx(ctx context.Context, fn func(ctx context.Context) error) (err error) {
	mm_atomic.AddUint64(&mmWithTx.beforeWithTxCounter, 1)
	defer mm_atomic.AddUint64(&mmWithTx.afterWithTxCounter, 1)

	mmWithTx.t.Helper()

	if mmWithTx.inspectFuncWithTx != nil {
		mmWithTx.inspectFuncWithTx(ctx, fn)
	}

	mm_params := ProcessStorageMockWithTxParams{ctx, fn}

	// Record call args
	mmWithTx.WithTxMock.mutex.Lock()
	mmWithTx.WithTxMock.callArgs = append(mmWithTx.WithTxMock.callArgs, &mm_params)
	mmWithTx.WithTxMock.mutex.Unlock()

	for _, e := range mmWithTx.WithTxMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmWithTx.WithTxMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmWithTx.WithTxMock.defaultExpectation.Counter, 1)
		mm_want := mmWithTx.WithTxMock.defaultExpectation.params
		mm_want_ptrs := mmWithTx.WithTxMock.defaultExpectation.paramPtrs

		mm_got := ProcessStorageMockWithTxParams{ctx, fn}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmWithTx.t.Errorf("ProcessStorageMock.WithTx got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmWithTx.WithTxMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.fn != nil && !minimock.Equal(*mm_want_ptrs.fn, mm_got.fn) {
				mmWithTx.t.Errorf("ProcessStorageMock.WithTx got unexpected parameter fn, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmWithTx.WithTxMock.defaultExpectation.expectationOrigins.originFn, *mm_want_ptrs.fn, mm_got.fn, minimock.Diff(*mm_want_ptrs.fn, mm_got.fn))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmWithTx.t.Errorf("ProcessStorageMock.WithTx got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmWithTx.WithTxMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmWithTx.WithTxMock.defaultExpectation.results
		if mm_results == nil {
			mmWithTx.t.Fatal("No results are set for the ProcessStorageMock.WithTx")
		}
		return (*mm_results).err
	}
	if mmWithTx.funcWithTx != nil {
		return mmWithTx.funcWithTx(ctx, fn)
	}
	mmWithTx.t.Fatalf("Unexpected call to ProcessStorageMock.WithTx. %v %v", ctx, fn)
	return
}

// WithTxAfterCounter returns a count of finished ProcessStorageMock.WithTx invocations
func (mmWithTx *ProcessStorageMock) WithTxAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWithTx.afterWithTxCounter)
}

// WithTxBeforeCounter returns a count of ProcessStorageMock.WithTx invocations
func (mmWithTx *ProcessStorageMock) WithTxBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWithTx.beforeWithTxCounter)
}

// Calls returns a list of arguments used in each call to ProcessStorageMock.WithTx.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmWithTx *mProcessStorageMockWithTx) Calls() []*ProcessStorageMockWithTxParams {
	mmWithTx.mutex.RLock()

	argCopy := make([]*ProcessStorageMockWithTxParams, len(mmWithTx.callArgs))
	copy(argCopy, mmWithTx.callArgs)

	mmWithTx.mutex.RUnlock()

	return argCopy
}

// MinimockWithTxDone returns true if the count of the WithTx invocations corresponds
// the number of defined expectations
func (m *ProcessStorageMock) MinimockWithTxDone() bool {
	if m.WithTxMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.WithTxMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.WithTxMock.invocationsDone()
}

// MinimockWithTxInspect logs each unmet expectation
func (m *ProcessStorageMock) MinimockWithTxInspect() {
	for _, e := range m.WithTxMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ProcessStorageMock.WithTx at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterWithTxCounter := mm_atomic.LoadUint64(&m.afterWithTxCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.WithTxMock.defaultExpectation != nil && afterWithTxCounter < 1 {
		if m.WithTxMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ProcessStorageMock.WithTx at\n%s", m.WithTxMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ProcessStorageMock.WithTx at\n%s with params: %#v", m.WithTxMock.defaultExpectation.expectationOrigins.origin, *m.WithTxMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcWithTx != nil && afterWithTxCounter < 1 {
		m.t.Errorf("Expected call to ProcessStorageMock.WithTx at\n%s", m.funcWithTxOrigin)
	}

	if !m.WithTxMock.invocationsDone() && afterWithTxCounter > 0 {
		m.t.Errorf("Expected %d calls to ProcessStorageMock.WithTx at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.WithTxMock.expectedInvocations), m.WithTxMock.expectedInvocationsOrigin, afterWithTxCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ProcessStorageMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateSubscriptionInspect()

			m.MinimockGetInvoiceByProviderOrderInspect()

			m.MinimockGetPlanByIDInspect()

			m.MinimockUpdateInvoiceInspect()

			m.MinimockWithTxInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ProcessStorageMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ProcessStorageMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateSubscriptionDone() &&
		m.MinimockGetInvoiceByProviderOrderDone() &&
		m.MinimockGetPlanByIDDone() &&
		m.MinimockUpdateInvoiceDone() &&
		m.MinimockWithTxDone()
}
