// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i control-plane/internal/service.ShopPayment -o shop_payment_mock.go -n ShopPaymentMock -p mocks

import (
	"context"
	"control-plane/internal/model"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ShopPaymentMock implements mm_service.ShopPayment
type ShopPaymentMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreatePaymentOrder          func(ctx context.Context, input model.CreateOrderInput) (c2 model.CreateOrderOutput, err error)
	funcCreatePaymentOrderOrigin    string
	inspectFuncCreatePaymentOrder   func(ctx context.Context, input model.CreateOrderInput)
	afterCreatePaymentOrderCounter  uint64
	beforeCreatePaymentOrderCounter uint64
	CreatePaymentOrderMock          mShopPaymentMockCreatePaymentOrder

	funcVerifyCallback          func(input model.CallbackInput) (c1 model.CallbackOutput, err error)
	funcVerifyCallbackOrigin    string
	inspectFuncVerifyCallback   func(input model.CallbackInput)
	afterVerifyCallbackCounter  uint64
	beforeVerifyCallbackCounter uint64
	VerifyCallbackMock          mShopPaymentMockVerifyCallback
}

// NewShopPaymentMock returns a mock for mm_service.ShopPayment
func NewShopPaymentMock(t minimock.Tester) *ShopPaymentMock {
	m := &ShopPaymentMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreatePaymentOrderMock = mShopPaymentMockCreatePaymentOrder{mock: m}
	m.CreatePaymentOrderMock.callArgs = []*ShopPaymentMockCreatePaymentOrderParams{}

	m.VerifyCallbackMock = mShopPaymentMockVerifyCallback{mock: m}
	m.VerifyCallbackMock.callArgs = []*ShopPaymentMockVerifyCallbackParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mShopPaymentMockCreatePaymentOrder struct {
	optional           bool
	mock               *ShopPaymentMock
	defaultExpectation *ShopPaymentMockCreatePaymentOrderExpectation
	expectations       []*ShopPaymentMockCreatePaymentOrderExpectation

	callArgs []*ShopPaymentMockCreatePaymentOrderParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ShopPaymentMockCreatePaymentOrderExpectation specifies expectation struct of the ShopPayment.CreatePaymentOrder
type ShopPaymentMockCreatePaymentOrderExpectation struct {
	mock               *ShopPaymentMock
	params             *ShopPaymentMockCreatePaymentOrderParams
	paramPtrs          *ShopPaymentMockCreatePaymentOrderParamPtrs
	expectationOrigins ShopPaymentMockCreatePaymentOrderExpectationOrigins
	results            *ShopPaymentMockCreatePaymentOrderResults
	returnOrigin       string
	Counter            uint64
}

// ShopPaymentMockCreatePaymentOrderParams contains parameters of the ShopPayment.CreatePaymentOrder
type ShopPaymentMockCreatePaymentOrderParams struct {
	ctx   context.Context
	input model.CreateOrderInput
}

// ShopPaymentMockCreatePaymentOrderParamPtrs contains pointers to parameters of the ShopPayment.CreatePaymentOrder
type ShopPaymentMockCreatePaymentOrderParamPtrs struct {
	ctx   *context.Context
	input *model.CreateOrderInput
}

// ShopPaymentMockCreatePaymentOrderResults contains results of the ShopPayment.CreatePaymentOrder
type ShopPaymentMockCreatePaymentOrderResults struct {
	c2  model.CreateOrderOutput
	err error
}

// ShopPaymentMockCreatePaymentOrderOrigins contains origins of expectations of the ShopPayment.CreatePaymentOrder
type ShopPaymentMockCreatePaymentOrderExpectationOrigins struct {
	origin      string
	originCtx   string
	originInput string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreatePaymentOrder *mShopPaymentMockCreatePaymentOrder) Optional() *mShopPaymentMockCreatePaymentOrder {
	mmCreatePaymentOrder.optional = true
	return mmCreatePaymentOrder
}

// Expect sets up expected params for ShopPayment.CreatePaymentOrder
func (mmCreatePaymentOrder *mShopPaymentMockCreatePaymentOrder) Expect(ctx context.Context, input model.CreateOrderInput) *mShopPaymentMockCreatePaymentOrder {
	if mmCreatePaymentOrder.mock.funcCreatePaymentOrder != nil {
		mmCreatePaymentOrder.mock.t.Fatalf("ShopPaymentMock.CreatePaymentOrder mock is already set by Set")
	}

	if mmCreatePaymentOrder.defaultExpectation == nil {
		mmCreatePaymentOrder.defaultExpectation = &ShopPaymentMockCreatePaymentOrderExpectation{}
	}

	if mmCreatePaymentOrder.defaultExpectation.paramPtrs != nil {
		mmCreatePaymentOrder.mock.t.Fatalf("ShopPaymentMock.CreatePaymentOrder mock is already set by ExpectParams functions")
	}

	mmCreatePaymentOrder.defaultExpectation.params = &ShopPaymentMockCreatePaymentOrderParams{ctx, input}
	mmCreatePaymentOrder.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreatePaymentOrder.expectations {
		if minimock.Equal(e.params, mmCreatePaymentOrder.defaultExpectation.params) {
			mmCreatePaymentOrder.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreatePaymentOrder.defaultExpectation.params)
		}
	}

	return mmCreatePaymentOrder
}

// ExpectCtxParam1 sets up expected param ctx for ShopPayment.CreatePaymentOrder
func (mmCreatePaymentOrder *mShopPaymentMockCreatePaymentOrder) ExpectCtxParam1(ctx context.Context) *mShopPaymentMockCreatePaymentOrder {
	if mmCreatePaymentOrder.mock.funcCreatePaymentOrder != nil {
		mmCreatePaymentOrder.mock.t.Fatalf("ShopPaymentMock.CreatePaymentOrder mock is already set by Set")
	}

	if mmCreatePaymentOrder.defaultExpectation == nil {
		mmCreatePaymentOrder.defaultExpectation = &ShopPaymentMockCreatePaymentOrderExpectation{}
	}

	if mmCreatePaymentOrder.defaultExpectation.params != nil {
		mmCreatePaymentOrder.mock.t.Fatalf("ShopPaymentMock.CreatePaymentOrder mock is already set by Expect")
	}

	if mmCreatePaymentOrder.defaultExpectation.paramPtrs == nil {
		mmCreatePaymentOrder.defaultExpectation.paramPtrs = &ShopPaymentMockCreatePaymentOrderParamPtrs{}
	}
	mmCreatePaymentOrder.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreatePaymentOrder.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreatePaymentOrder
}

// ExpectInputParam2 sets up expected param input for ShopPayment.CreatePaymentOrder
func (mmCreatePaymentOrder *mShopPaymentMockCreatePaymentOrder) ExpectInputParam2(input model.CreateOrderInput) *mShopPaymentMockCreatePaymentOrder {
	if mmCreatePaymentOrder.mock.funcCreatePaymentOrder != nil {
		mmCreatePaymentOrder.mock.t.Fatalf("ShopPaymentMock.CreatePaymentOrder mock is already set by Set")
	}

	if mmCreatePaymentOrder.defaultExpectation == nil {
		mmCreatePaymentOrder.defaultExpectation = &ShopPaymentMockCreatePaymentOrderExpectation{}
	}

	if mmCreatePaymentOrder.defaultExpectation.params != nil {
		mmCreatePaymentOrder.mock.t.Fatalf("ShopPaymentMock.CreatePaymentOrder mock is already set by Expect")
	}

	if mmCreatePaymentOrder.defaultExpectation.paramPtrs == nil {
		mmCreatePaymentOrder.defaultExpectation.paramPtrs = &ShopPaymentMockCreatePaymentOrderParamPtrs{}
	}
	mmCreatePaymentOrder.defaultExpectation.paramPtrs.input = &input
	mmCreatePaymentOrder.defaultExpectation.expectationOrigins.originInput = minimock.CallerInfo(1)

	return mmCreatePaymentOrder
}

// Inspect accepts an inspector function that has same arguments as the ShopPayment.CreatePaymentOrder
func (mmCreatePaymentOrder *mShopPaymentMockCreatePaymentOrder) Inspect(f func(ctx context.Context, input model.CreateOrderInput)) *mShopPaymentMockCreatePaymentOrder {
	if mmCreatePaymentOrder.mock.inspectFuncCreatePaymentOrder != nil {
		mmCreatePaymentOrder.mock.t.Fatalf("Inspect function is already set for ShopPaymentMock.CreatePaymentOrder")
	}

	mmCreatePaymentOrder.mock.inspectFuncCreatePaymentOrder = f

	return mmCreatePaymentOrder
}

// Return sets up results that will be returned by ShopPayment.CreatePaymentOrder
func (mmCreatePaymentOrder *mShopPaymentMockCreatePaymentOrder) Return(c2 model.CreateOrderOutput, err error) *ShopPaymentMock {
	if mmCreatePaymentOrder.mock.funcCreatePaymentOrder != nil {
		mmCreatePaymentOrder.mock.t.Fatalf("ShopPaymentMock.CreatePaymentOrder mock is already set by Set")
	}

	if mmCreatePaymentOrder.defaultExpectation == nil {
		mmCreatePaymentOrder.defaultExpectation = &ShopPaymentMockCreatePaymentOrderExpectation{mock: mmCreatePaymentOrder.mock}
	}
	mmCreatePaymentOrder.defaultExpectation.results = &ShopPaymentMockCreatePaymentOrderResults{c2, err}
	mmCreatePaymentOrder.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreatePaymentOrder.mock
}

// Set uses given function f to mock the ShopPayment.CreatePaymentOrder method
func (mmCreatePaymentOrder *mShopPaymentMockCreatePaymentOrder) Set(f func(ctx context.Context, input model.CreateOrderInput) (c2 model.CreateOrderOutput, err error)) *ShopPaymentMock {
	if mmCreatePaymentOrder.defaultExpectation != nil {
		mmCreatePaymentOrder.mock.t.Fatalf("Default expectation is already set for the ShopPayment.CreatePaymentOrder method")
	}

	if len(mmCreatePaymentOrder.expectations) > 0 {
		mmCreatePaymentOrder.mock.t.Fatalf("Some expectations are already set for the ShopPayment.CreatePaymentOrder method")
	}

	mmCreatePaymentOrder.mock.funcCreatePaymentOrder = f
	mmCreatePaymentOrder.mock.funcCreatePaymentOrderOrigin = minimock.CallerInfo(1)
	return mmCreatePaymentOrder.mock
}

// When sets expectation for the ShopPayment.CreatePaymentOrder which will trigger the result defined by the following
// Then helper
func (mmCreatePaymentOrder *mShopPaymentMockCreatePaymentOrder) When(ctx context.Context, input model.CreateOrderInput) *ShopPaymentMockCreatePaymentOrderExpectation {
	if mmCreatePaymentOrder.mock.funcCreatePaymentOrder != nil {
		mmCreatePaymentOrder.mock.t.Fatalf("ShopPaymentMock.CreatePaymentOrder mock is already set by Set")
	}

	expectation := &ShopPaymentMockCreatePaymentOrderExpectation{
		mock:               mmCreatePaymentOrder.mock,
		params:             &ShopPaymentMockCreatePaymentOrderParams{ctx, input},
		expectationOrigins: ShopPaymentMockCreatePaymentOrderExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreatePaymentOrder.expectations = append(mmCreatePaymentOrder.expectations, expectation)
	return expectation
}

// Then sets up ShopPayment.CreatePaymentOrder return parameters for the expectation previously defined by the When method
func (e *ShopPaymentMockCreatePaymentOrderExpectation) Then(c2 model.CreateOrderOutput, err error) *ShopPaymentMock {
	e.results = &ShopPaymentMockCreatePaymentOrderResults{c2, err}
	return e.mock
}

// Times sets number of times ShopPayment.CreatePaymentOrder should be invoked
func (mmCreatePaymentOrder *mShopPaymentMockCreatePaymentOrder) Times(n uint64) *mShopPaymentMockCreatePaymentOrder {
	if n == 0 {
		mmCreatePaymentOrder.mock.t.Fatalf("Times of ShopPaymentMock.CreatePaymentOrder mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreatePaymentOrder.expectedInvocations, n)
	mmCreatePaymentOrder.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreatePaymentOrder
}

func (mmCreatePaymentOrder *mShopPaymentMockCreatePaymentOrder) invocationsDone() bool {
	if len(mmCreatePaymentOrder.expectations) == 0 && mmCreatePaymentOrder.defaultExpectation == nil && mmCreatePaymentOrder.mock.funcCreatePaymentOrder == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreatePaymentOrder.mock.afterCreatePaymentOrderCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreatePaymentOrder.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreatePaymentOrder implements mm_service.ShopPayment
func (mmCreatePaymentOrder *ShopPaymentMock) CreatePaymentOrder(ctx context.Context, input model.CreateOrderInput) (c2 model.CreateOrderOutput, err error) {
	mm_atomic.AddUint64(&mmCreatePaymentOrder.beforeCreatePaymentOrderCounter, 1)
	defer mm_atomic.AddUint64(&mmCreatePaymentOrder.afterCreatePaymentOrderCounter, 1)

	mmCreatePaymentOrder.t.Helper()

	if mmCreatePaymentOrder.inspectFuncCreatePaymentOrder != nil {
		mmCreatePaymentOrder.inspectFuncCreatePaymentOrder(ctx, input)
	}

	mm_params := ShopPaymentMockCreatePaymentOrderParams{ctx, input}

	// Record call args
	mmCreatePaymentOrder.CreatePaymentOrderMock.mutex.Lock()
	mmCreatePaymentOrder.CreatePaymentOrderMock.callArgs = append(mmCreatePaymentOrder.CreatePaymentOrderMock.callArgs, &mm_params)
	mmCreatePaymentOrder.CreatePaymentOrderMock.mutex.Unlock()

	for _, e := range mmCreatePaymentOrder.CreatePaymentOrderMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.c2, e.results.err
		}
	}

	if mmCreatePaymentOrder.CreatePaymentOrderMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreatePaymentOrder.CreatePaymentOrderMock.defaultExpectation.Counter, 1)
		mm_want := mmCreatePaymentOrder.CreatePaymentOrderMock.defaultExpectation.params
		mm_want_ptrs := mmCreatePaymentOrder.CreatePaymentOrderMock.defaultExpectation.paramPtrs

		mm_got := ShopPaymentMockCreatePaymentOrderParams{ctx, input}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreatePaymentOrder.t.Errorf("ShopPaymentMock.CreatePaymentOrder got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreatePaymentOrder.CreatePaymentOrderMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.input != nil && !minimock.Equal(*mm_want_ptrs.input, mm_got.input) {
				mmCreatePaymentOrder.t.Errorf("ShopPaymentMock.CreatePaymentOrder got unexpected parameter input, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreatePaymentOrder.CreatePaymentOrderMock.defaultExpectation.expectationOrigins.originInput, *mm_want_ptrs.input, mm_got.input, minimock.Diff(*mm_want_ptrs.input, mm_got.input))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreatePaymentOrder.t.Errorf("ShopPaymentMock.CreatePaymentOrder got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreatePaymentOrder.CreatePaymentOrderMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreatePaymentOrder.CreatePaymentOrderMock.defaultExpectation.results
		if mm_results == nil {
			mmCreatePaymentOrder.t.Fatal("No results are set for the ShopPaymentMock.CreatePaymentOrder")
		}
		return (*mm_results).c2, (*mm_results).err
	}
	if mmCreatePaymentOrder.funcCreatePaymentOrder != nil {
		return mmCreatePaymentOrder.funcCreatePaymentOrder(ctx, input)
	}
	mmCreatePaymentOrder.t.Fatalf("Unexpected call to ShopPaymentMock.CreatePaymentOrder. %v %v", ctx, input)
	return
}

// CreatePaymentOrderAfterCounter returns a count of finished ShopPaymentMock.CreatePaymentOrder invocations
func (mmCreatePaymentOrder *ShopPaymentMock) CreatePaymentOrderAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreatePaymentOrder.afterCreatePaymentOrderCounter)
}

// CreatePaymentOrderBeforeCounter returns a count of ShopPaymentMock.CreatePaymentOrder invocations
func (mmCreatePaymentOrder *ShopPaymentMock) CreatePaymentOrderBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreatePaymentOrder.beforeCreatePaymentOrderCounter)
}

// Calls returns a list of arguments used in each call to ShopPaymentMock.CreatePaymentOrder.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreatePaymentOrder *mShopPaymentMockCreatePaymentOrder) Calls() []*ShopPaymentMockCreatePaymentOrderParams {
	mmCreatePaymentOrder.mutex.RLock()

	argCopy := make([]*ShopPaymentMockCreatePaymentOrderParams, len(mmCreatePaymentOrder.callArgs))
	copy(argCopy, mmCreatePaymentOrder.callArgs)

	mmCreatePaymentOrder.mutex.RUnlock()

	return argCopy
}

// MinimockCreatePaymentOrderDone returns true if the count of the CreatePaymentOrder invocations corresponds
// the number of defined expectations
func (m *ShopPaymentMock) MinimockCreatePaymentOrderDone() bool {
	if m.CreatePaymentOrderMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreatePaymentOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreatePaymentOrderMock.invocationsDone()
}

// MinimockCreatePaymentOrderInspect logs each unmet expectation
func (m *ShopPaymentMock) MinimockCreatePaymentOrderInspect() {
	for _, e := range m.CreatePaymentOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ShopPaymentMock.CreatePaymentOrder at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreatePaymentOrderCounter := mm_atomic.LoadUint64(&m.afterCreatePaymentOrderCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreatePaymentOrderMock.defaultExpectation != nil && afterCreatePaymentOrderCounter < 1 {
		if m.CreatePaymentOrderMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ShopPaymentMock.CreatePaymentOrder at\n%s", m.CreatePaymentOrderMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ShopPaymentMock.CreatePaymentOrder at\n%s with params: %#v", m.CreatePaymentOrderMock.defaultExpectation.expectationOrigins.origin, *m.CreatePaymentOrderMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreatePaymentOrder != nil && afterCreatePaymentOrderCounter < 1 {
		m.t.Errorf("Expected call to ShopPaymentMock.CreatePaymentOrder at\n%s", m.funcCreatePaymentOrderOrigin)
	}

	if !m.CreatePaymentOrderMock.invocationsDone() && afterCreatePaymentOrderCounter > 0 {
		m.t.Errorf("Expected %d calls to ShopPaymentMock.CreatePaymentOrder at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreatePaymentOrderMock.expectedInvocations), m.CreatePaymentOrderMock.expectedInvocationsOrigin, afterCreatePaymentOrderCounter)
	}
}

type mShopPaymentMockVerifyCallback struct {
	optional           bool
	mock               *ShopPaymentMock
	defaultExpectation *ShopPaymentMockVerifyCallbackExpectation
	expectations       []*ShopPaymentMockVerifyCallbackExpectation

	callArgs []*ShopPaymentMockVerifyCallbackParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ShopPaymentMockVerifyCallbackExpectation specifies expectation struct of the ShopPayment.VerifyCallback
type ShopPaymentMockVerifyCallbackExpectation struct {
	mock               *ShopPaymentMock
	params             *ShopPaymentMockVerifyCallbackParams
	paramPtrs          *ShopPaymentMockVerifyCallbackParamPtrs
	expectationOrigins ShopPaymentMockVerifyCallbackExpectationOrigins
	results            *ShopPaymentMockVerifyCallbackResults
	returnOrigin       string
	Counter            uint64
}

// ShopPaymentMockVerifyCallbackParams contains parameters of the ShopPayment.VerifyCallback
type ShopPaymentMockVerifyCallbackParams struct {
	input model.CallbackInput
}

// ShopPaymentMockVerifyCallbackParamPtrs contains pointers to parameters of the ShopPayment.VerifyCallback
type ShopPaymentMockVerifyCallbackParamPtrs struct {
	input *model.CallbackInput
}

// ShopPaymentMockVerifyCallbackResults contains results of the ShopPayment.VerifyCallback
type ShopPaymentMockVerifyCallbackResults struct {
	c1  model.CallbackOutput
	err error
}

// ShopPaymentMockVerifyCallbackOrigins contains origins of expectations of the ShopPayment.VerifyCallback
type ShopPaymentMockVerifyCallbackExpectationOrigins struct {
	origin      string
	originInput string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmVerifyCallback *mShopPaymentMockVerifyCallback) Optional() *mShopPaymentMockVerifyCallback {
	mmVerifyCallback.optional = true
	return mmVerifyCallback
}

// Expect sets up expected params for ShopPayment.VerifyCallback
func (mmVerifyCallback *mShopPaymentMockVerifyCallback) Expect(input model.CallbackInput) *mShopPaymentMockVerifyCallback {
	if mmVerifyCallback.mock.funcVerifyCallback != nil {
		mmVerifyCallback.mock.t.Fatalf("ShopPaymentMock.VerifyCallback mock is already set by Set")
	}

	if mmVerifyCallback.defaultExpectation == nil {
		mmVerifyCallback.defaultExpectation = &ShopPaymentMockVerifyCallbackExpectation{}
	}

	if mmVerifyCallback.defaultExpectation.paramPtrs != nil {
		mmVerifyCallback.mock.t.Fatalf("ShopPaymentMock.VerifyCallback mock is already set by ExpectParams functions")
	}

	mmVerifyCallback.defaultExpectation.params = &ShopPaymentMockVerifyCallbackParams{input}
	mmVerifyCallback.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmVerifyCallback.expectations {
		if minimock.Equal(e.params, mmVerifyCallback.defaultExpectation.params) {
			mmVerifyCallback.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmVerifyCallback.defaultExpectation.params)
		}
	}

	return mmVerifyCallback
}

// ExpectInputParam1 sets up expected param input for ShopPayment.VerifyCallback
func (mmVerifyCallback *mShopPaymentMockVerifyCallback) ExpectInputParam1(input model.CallbackInput) *mShopPaymentMockVerifyCallback {
	if mmVerifyCallback.mock.funcVerifyCallback != nil {
		mmVerifyCallback.mock.t.Fatalf("ShopPaymentMock.VerifyCallback mock is already set by Set")
	}

	if mmVerifyCallback.defaultExpectation == nil {
		mmVerifyCallback.defaultExpectation = &ShopPaymentMockVerifyCallbackExpectation{}
	}

	if mmVerifyCallback.defaultExpectation.params != nil {
		mmVerifyCallback.mock.t.Fatalf("ShopPaymentMock.VerifyCallback mock is already set by Expect")
	}

	if mmVerifyCallback.defaultExpectation.paramPtrs == nil {
		mmVerifyCallback.defaultExpectation.paramPtrs = &ShopPaymentMockVerifyCallbackParamPtrs{}
	}
	mmVerifyCallback.defaultExpectation.paramPtrs.input = &input
	mmVerifyCallback.defaultExpectation.expectationOrigins.originInput = minimock.CallerInfo(1)

	return mmVerifyCallback
}

// Inspect accepts an inspector function that has same arguments as the ShopPayment.VerifyCallback
func (mmVerifyCallback *mShopPaymentMockVerifyCallback) Inspect(f func(input model.CallbackInput)) *mShopPaymentMockVerifyCallback {
	if mmVerifyCallback.mock.inspectFuncVerifyCallback != nil {
		mmVerifyCallback.mock.t.Fatalf("Inspect function is already set for ShopPaymentMock.VerifyCallback")
	}

	mmVerifyCallback.mock.inspectFuncVerifyCallback = f

	return mmVerifyCallback
}

// Return sets up results that will be returned by ShopPayment.VerifyCallback
func (mmVerifyCallback *mShopPaymentMockVerifyCallback) Return(c1 model.CallbackOutput, err error) *ShopPaymentMock {
	if mmVerifyCallback.mock.funcVerifyCallback != nil {
		mmVerifyCallback.mock.t.Fatalf("ShopPaymentMock.VerifyCallback mock is already set by Set")
	}

	if mmVerifyCallback.defaultExpectation == nil {
		mmVerifyCallback.defaultExpectation = &ShopPaymentMockVerifyCallbackExpectation{mock: mmVerifyCallback.mock}
	}
	mmVerifyCallback.defaultExpectation.results = &ShopPaymentMockVerifyCallbackResults{c1, err}
	mmVerifyCallback.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmVerifyCallback.mock
}

// Set uses given function f to mock the ShopPayment.VerifyCallback method
func (mmVerifyCallback *mShopPaymentMockVerifyCallback) Set(f func(input model.CallbackInput) (c1 model.CallbackOutput, err error)) *ShopPaymentMock {
	if mmVerifyCallback.defaultExpectation != nil {
		mmVerifyCallback.mock.t.Fatalf("Default expectation is already set for the ShopPayment.VerifyCallback method")
	}

	if len(mmVerifyCallback.expectations) > 0 {
		mmVerifyCallback.mock.t.Fatalf("Some expectations are already set for the ShopPayment.VerifyCallback method")
	}

	mmVerifyCallback.mock.funcVerifyCallback = f
	mmVerifyCallback.mock.funcVerifyCallbackOrigin = minimock.CallerInfo(1)
	return mmVerifyCallback.mock
}

// When sets expectation for the ShopPayment.VerifyCallback which will trigger the result defined by the following
// Then helper
func (mmVerifyCallback *mShopPaymentMockVerifyCallback) When(input model.CallbackInput) *ShopPaymentMockVerifyCallbackExpectation {
	if mmVerifyCallback.mock.funcVerifyCallback != nil {
		mmVerifyCallback.mock.t.Fatalf("ShopPaymentMock.VerifyCallback mock is already set by Set")
	}

	expectation := &ShopPaymentMockVerifyCallbackExpectation{
		mock:               mmVerifyCallback.mock,
		params:             &ShopPaymentMockVerifyCallbackParams{input},
		expectationOrigins: ShopPaymentMockVerifyCallbackExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmVerifyCallback.expectations = append(mmVerifyCallback.expectations, expectation)
	return expectation
}

// Then sets up ShopPayment.VerifyCallback return parameters for the expectation previously defined by the When method
func (e *ShopPaymentMockVerifyCallbackExpectation) Then(c1 model.CallbackOutput, err error) *ShopPaymentMock {
	e.results = &ShopPaymentMockVerifyCallbackResults{c1, err}
	return e.mock
}

// Times sets number of times ShopPayment.VerifyCallback should be invoked
func (mmVerifyCallback *mShopPaymentMockVerifyCallback) Times(n uint64) *mShopPaymentMockVerifyCallback {
	if n == 0 {
		mmVerifyCallback.mock.t.Fatalf("Times of ShopPaymentMock.VerifyCallback mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmVerifyCallback.expectedInvocations, n)
	mmVerifyCallback.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmVerifyCallback
}

func (mmVerifyCallback *mShopPaymentMockVerifyCallback) invocationsDone() bool {
	if len(mmVerifyCallback.expectations) == 0 && mmVerifyCallback.defaultExpectation == nil && mmVerifyCallback.mock.funcVerifyCallback == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmVerifyCallback.mock.afterVerifyCallbackCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmVerifyCallback.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// VerifyCallback implements mm_service.ShopPayment
func (mmVerifyCallback *ShopPaymentMock) VerifyCallback(input model.CallbackInput) (c1 model.CallbackOutput, err error) {
	mm_atomic.AddUint64(&mmVerifyCallback.beforeVerifyCallbackCounter, 1)
	defer mm_atomic.AddUint64(&mmVerifyCallback.afterVerifyCallbackCounter, 1)

	mmVerifyCallback.t.Helper()

	if mmVerifyCallback.inspectFuncVerifyCallback != nil {
		mmVerifyCallback.inspectFuncVerifyCallback(input)
	}

	mm_params := ShopPaymentMockVerifyCallbackParams{input}

	// Record call args
	mmVerifyCallback.VerifyCallbackMock.mutex.Lock()
	mmVerifyCallback.VerifyCallbackMock.callArgs = append(mmVerifyCallback.VerifyCallbackMock.callArgs, &mm_params)
	mmVerifyCallback.VerifyCallbackMock.mutex.Unlock()

	for _, e := range mmVerifyCallback.VerifyCallbackMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.c1, e.results.err
		}
	}

	if mmVerifyCallback.VerifyCallbackMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmVerifyCallback.VerifyCallbackMock.defaultExpectation.Counter, 1)
		mm_want := mmVerifyCallback.VerifyCallbackMock.defaultExpectation.params
		mm_want_ptrs := mmVerifyCallback.VerifyCallbackMock.defaultExpectation.paramPtrs

		mm_got := ShopPaymentMockVerifyCallbackParams{input}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.input != nil && !minimock.Equal(*mm_want_ptrs.input, mm_got.input) {
				mmVerifyCallback.t.Errorf("ShopPaymentMock.VerifyCallback got unexpected parameter input, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmVerifyCallback.VerifyCallbackMock.defaultExpectation.expectationOrigins.originInput, *mm_want_ptrs.input, mm_got.input, minimock.Diff(*mm_want_ptrs.input, mm_got.input))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmVerifyCallback.t.Errorf("ShopPaymentMock.VerifyCallback got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmVerifyCallback.VerifyCallbackMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmVerifyCallback.VerifyCallbackMock.defaultExpectation.results
		if mm_results == nil {
			mmVerifyCallback.t.Fatal("No results are set for the ShopPaymentMock.VerifyCallback")
		}
		return (*mm_results).c1, (*mm_results).err
	}
	if mmVerifyCallback.funcVerifyCallback != nil {
		return mmVerifyCallback.funcVerifyCallback(input)
	}
	mmVerifyCallback.t.Fatalf("Unexpected call to ShopPaymentMock.VerifyCallback. %v", input)
	return
}

// VerifyCallbackAfterCounter returns a count of finished ShopPaymentMock.VerifyCallback invocations
func (mmVerifyCallback *ShopPaymentMock) VerifyCallbackAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmVerifyCallback.afterVerifyCallbackCounter)
}

// VerifyCallbackBeforeCounter returns a count of ShopPaymentMock.VerifyCallback invocations
func (mmVerifyCallback *ShopPaymentMock) VerifyCallbackBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmVerifyCallback.beforeVerifyCallbackCounter)
}

// Calls returns a list of arguments used in each call to ShopPaymentMock.VerifyCallback.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmVerifyCallback *mShopPaymentMockVerifyCallback) Calls() []*ShopPaymentMockVerifyCallbackParams {
	mmVerifyCallback.mutex.RLock()

	argCopy := make([]*ShopPaymentMockVerifyCallbackParams, len(mmVerifyCallback.callArgs))
	copy(argCopy, mmVerifyCallback.callArgs)

	mmVerifyCallback.mutex.RUnlock()

	return argCopy
}

// MinimockVerifyCallbackDone returns true if the count of the VerifyCallback invocations corresponds
// the number of defined expectations
func (m *ShopPaymentMock) MinimockVerifyCallbackDone() bool {
	if m.VerifyCallbackMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.VerifyCallbackMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.VerifyCallbackMock.invocationsDone()
}

// MinimockVerifyCallbackInspect logs each unmet expectation
func (m *ShopPaymentMock) MinimockVerifyCallbackInspect() {
	for _, e := range m.VerifyCallbackMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ShopPaymentMock.VerifyCallback at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterVerifyCallbackCounter := mm_atomic.LoadUint64(&m.afterVerifyCallbackCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.VerifyCallbackMock.defaultExpectation != nil && afterVerifyCallbackCounter < 1 {
		if m.VerifyCallbackMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ShopPaymentMock.VerifyCallback at\n%s", m.VerifyCallbackMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ShopPaymentMock.VerifyCallback at\n%s with params: %#v", m.VerifyCallbackMock.defaultExpectation.expectationOrigins.origin, *m.VerifyCallbackMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcVerifyCallback != nil && afterVerifyCallbackCounter < 1 {
		m.t.Errorf("Expected call to ShopPaymentMock.VerifyCallback at\n%s", m.funcVerifyCallbackOrigin)
	}

	if !m.VerifyCallbackMock.invocationsDone() && afterVerifyCallbackCounter > 0 {
		m.t.Errorf("Expected %d calls to ShopPaymentMock.VerifyCallback at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.VerifyCallbackMock.expectedInvocations), m.VerifyCallbackMock.expectedInvocationsOrigin, afterVerifyCallbackCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ShopPaymentMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreatePaymentOrderInspect()

			m.MinimockVerifyCallbackInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ShopPaymentMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ShopPaymentMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreatePaymentOrderDone() &&
		m.MinimockVerifyCallbackDone()
}
