// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i control-plane/internal/service.ShopOutbox -o shop_outbox_mock.go -n ShopOutboxMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ShopOutboxMock implements mm_service.ShopOutbox
type ShopOutboxMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSaveOutboxEvent          func(ctx context.Context, eventType string, payload any) (err error)
	funcSaveOutboxEventOrigin    string
	inspectFuncSaveOutboxEvent   func(ctx context.Context, eventType string, payload any)
	afterSaveOutboxEventCounter  uint64
	beforeSaveOutboxEventCounter uint64
	SaveOutboxEventMock          mShopOutboxMockSaveOutboxEvent
}

// NewShopOutboxMock returns a mock for mm_service.ShopOutbox
func NewShopOutboxMock(t minimock.Tester) *ShopOutboxMock {
	m := &ShopOutboxMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SaveOutboxEventMock = mShopOutboxMockSaveOutboxEvent{mock: m}
	m.SaveOutboxEventMock.callArgs = []*ShopOutboxMockSaveOutboxEventParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mShopOutboxMockSaveOutboxEvent struct {
	optional           bool
	mock               *ShopOutboxMock
	defaultExpectation *ShopOutboxMockSaveOutboxEventExpectation
	expectations       []*ShopOutboxMockSaveOutboxEventExpectation

	callArgs []*ShopOutboxMockSaveOutboxEventParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ShopOutboxMockSaveOutboxEventExpectation specifies expectation struct of the ShopOutbox.SaveOutboxEvent
type ShopOutboxMockSaveOutboxEventExpectation struct {
	mock               *ShopOutboxMock
	params             *ShopOutboxMockSaveOutboxEventParams
	paramPtrs          *ShopOutboxMockSaveOutboxEventParamPtrs
	expectationOrigins ShopOutboxMockSaveOutboxEventExpectationOrigins
	results            *ShopOutboxMockSaveOutboxEventResults
	returnOrigin       string
	Counter            uint64
}

// ShopOutboxMockSaveOutboxEventParams contains parameters of the ShopOutbox.SaveOutboxEvent
type ShopOutboxMockSaveOutboxEventParams struct {
	ctx       context.Context
	eventType string
	payload   any
}

// ShopOutboxMockSaveOutboxEventParamPtrs contains pointers to parameters of the ShopOutbox.SaveOutboxEvent
type ShopOutboxMockSaveOutboxEventParamPtrs struct {
	ctx       *context.Context
	eventType *string
	payload   *any
}

// ShopOutboxMockSaveOutboxEventResults contains results of the ShopOutbox.SaveOutboxEvent
type ShopOutboxMockSaveOutboxEventResults struct {
	err error
}

// ShopOutboxMockSaveOutboxEventOrigins contains origins of expectations of the ShopOutbox.SaveOutboxEvent
type ShopOutboxMockSaveOutboxEventExpectationOrigins struct {
	origin          string
	originCtx       string
	originEventType string
	originPayload   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSaveOutboxEvent *mShopOutboxMockSaveOutboxEvent) Optional() *mShopOutboxMockSaveOutboxEvent {
	mmSaveOutboxEvent.optional = true
	return mmSaveOutboxEvent
}

// Expect sets up expected params for ShopOutbox.SaveOutboxEvent
func (mmSaveOutboxEvent *mShopOutboxMockSaveOutboxEvent) Expect(ctx context.Context, eventType string, payload any) *mShopOutboxMockSaveOutboxEvent {
	if mmSaveOutboxEvent.mock.funcSaveOutboxEvent != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("ShopOutboxMock.SaveOutboxEvent mock is already set by Set")
	}

	if mmSaveOutboxEvent.defaultExpectation == nil {
		mmSaveOutboxEvent.defaultExpectation = &ShopOutboxMockSaveOutboxEventExpectation{}
	}

	if mmSaveOutboxEvent.defaultExpectation.paramPtrs != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("ShopOutboxMock.SaveOutboxEvent mock is already set by ExpectParams functions")
	}

	mmSaveOutboxEvent.defaultExpectation.params = &ShopOutboxMockSaveOutboxEventParams{ctx, eventType, payload}
	mmSaveOutboxEvent.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSaveOutboxEvent.expectations {
		if minimock.Equal(e.params, mmSaveOutboxEvent.defaultExpectation.params) {
			mmSaveOutboxEvent.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSaveOutboxEvent.defaultExpectation.params)
		}
	}

	return mmSaveOutboxEvent
}

// ExpectCtxParam1 sets up expected param ctx for ShopOutbox.SaveOutboxEvent
func (mmSaveOutboxEvent *mShopOutboxMockSaveOutboxEvent) ExpectCtxParam1(ctx context.Context) *mShopOutboxMockSaveOutboxEvent {
	if mmSaveOutboxEvent.mock.funcSaveOutboxEvent != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("ShopOutboxMock.SaveOutboxEvent mock is already set by Set")
	}

	if mmSaveOutboxEvent.defaultExpectation == nil {
		mmSaveOutboxEvent.defaultExpectation = &ShopOutboxMockSaveOutboxEventExpectation{}
	}

	if mmSaveOutboxEvent.defaultExpectation.params != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("ShopOutboxMock.SaveOutboxEvent mock is already set by Expect")
	}

	if mmSaveOutboxEvent.defaultExpectation.paramPtrs == nil {
		mmSaveOutboxEvent.defaultExpectation.paramPtrs = &ShopOutboxMockSaveOutboxEventParamPtrs{}
	}
	mmSaveOutboxEvent.defaultExpectation.paramPtrs.ctx = &ctx
	mmSaveOutboxEvent.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSaveOutboxEvent
}

// ExpectEventTypeParam2 sets up expected param eventType for ShopOutbox.SaveOutboxEvent
func (mmSaveOutboxEvent *mShopOutboxMockSaveOutboxEvent) ExpectEventTypeParam2(eventType string) *mShopOutboxMockSaveOutboxEvent {
	if mmSaveOutboxEvent.mock.funcSaveOutboxEvent != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("ShopOutboxMock.SaveOutboxEvent mock is already set by Set")
	}

	if mmSaveOutboxEvent.defaultExpectation == nil {
		mmSaveOutboxEvent.defaultExpectation = &ShopOutboxMockSaveOutboxEventExpectation{}
	}

	if mmSaveOutboxEvent.defaultExpectation.params != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("ShopOutboxMock.SaveOutboxEvent mock is already set by Expect")
	}

	if mmSaveOutboxEvent.defaultExpectation.paramPtrs == nil {
		mmSaveOutboxEvent.defaultExpectation.paramPtrs = &ShopOutboxMockSaveOutboxEventParamPtrs{}
	}
	mmSaveOutboxEvent.defaultExpectation.paramPtrs.eventType = &eventType
	mmSaveOutboxEvent.defaultExpectation.expectationOrigins.originEventType = minimock.CallerInfo(1)

	return mmSaveOutboxEvent
}

// ExpectPayloadParam3 sets up expected param payload for ShopOutbox.SaveOutboxEvent
func (mmSaveOutboxEvent *mShopOutboxMockSaveOutboxEvent) ExpectPayloadParam3(payload any) *mShopOutboxMockSaveOutboxEvent {
	if mmSaveOutboxEvent.mock.funcSaveOutboxEvent != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("ShopOutboxMock.SaveOutboxEvent mock is already set by Set")
	}

	if mmSaveOutboxEvent.defaultExpectation == nil {
		mmSaveOutboxEvent.defaultExpectation = &ShopOutboxMockSaveOutboxEventExpectation{}
	}

	if mmSaveOutboxEvent.defaultExpectation.params != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("ShopOutboxMock.SaveOutboxEvent mock is already set by Expect")
	}

	if mmSaveOutboxEvent.defaultExpectation.paramPtrs == nil {
		mmSaveOutboxEvent.defaultExpectation.paramPtrs = &ShopOutboxMockSaveOutboxEventParamPtrs{}
	}
	mmSaveOutboxEvent.defaultExpectation.paramPtrs.payload = &payload
	mmSaveOutboxEvent.defaultExpectation.expectationOrigins.originPayload = minimock.CallerInfo(1)

	return mmSaveOutboxEvent
}

// Inspect accepts an inspector function that has same arguments as the ShopOutbox.SaveOutboxEvent
func (mmSaveOutboxEvent *mShopOutboxMockSaveOutboxEvent) Inspect(f func(ctx context.Context, eventType string, payload any)) *mShopOutboxMockSaveOutboxEvent {
	if mmSaveOutboxEvent.mock.inspectFuncSaveOutboxEvent != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("Inspect function is already set for ShopOutboxMock.SaveOutboxEvent")
	}

	mmSaveOutboxEvent.mock.inspectFuncSaveOutboxEvent = f

	return mmSaveOutboxEvent
}

// Return sets up results that will be returned by ShopOutbox.SaveOutboxEvent
func (mmSaveOutboxEvent *mShopOutboxMockSaveOutboxEvent) Return(err error) *ShopOutboxMock {
	if mmSaveOutboxEvent.mock.funcSaveOutboxEvent != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("ShopOutboxMock.SaveOutboxEvent mock is already set by Set")
	}

	if mmSaveOutboxEvent.defaultExpectation == nil {
		mmSaveOutboxEvent.defaultExpectation = &ShopOutboxMockSaveOutboxEventExpectation{mock: mmSaveOutboxEvent.mock}
	}
	mmSaveOutboxEvent.defaultExpectation.results = &ShopOutboxMockSaveOutboxEventResults{err}
	mmSaveOutboxEvent.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSaveOutboxEvent.mock
}

// Set uses given function f to mock the ShopOutbox.SaveOutboxEvent method
func (mmSaveOutboxEvent *mShopOutboxMockSaveOutboxEvent) Set(f func(ctx context.Context, eventType string, payload any) (err error)) *ShopOutboxMock {
	if mmSaveOutboxEvent.defaultExpectation != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("Default expectation is already set for the ShopOutbox.SaveOutboxEvent method")
	}

	if len(mmSaveOutboxEvent.expectations) > 0 {
		mmSaveOutboxEvent.mock.t.Fatalf("Some expectations are already set for the ShopOutbox.SaveOutboxEvent method")
	}

	mmSaveOutboxEvent.mock.funcSaveOutboxEvent = f
	mmSaveOutboxEvent.mock.funcSaveOutboxEventOrigin = minimock.CallerInfo(1)
	return mmSaveOutboxEvent.mock
}

// When sets expectation for the ShopOutbox.SaveOutboxEvent which will trigger the result defined by the following
// Then helper
func (mmSaveOutboxEvent *mShopOutboxMockSaveOutboxEvent) When(ctx context.Context, eventType string, payload any) *ShopOutboxMockSaveOutboxEventExpectation {
	if mmSaveOutboxEvent.mock.funcSaveOutboxEvent != nil {
		mmSaveOutboxEvent.mock.t.Fatalf("ShopOutboxMock.SaveOutboxEvent mock is already set by Set")
	}

	expectation := &ShopOutboxMockSaveOutboxEventExpectation{
		mock:               mmSaveOutboxEvent.mock,
		params:             &ShopOutboxMockSaveOutboxEventParams{ctx, eventType, payload},
		expectationOrigins: ShopOutboxMockSaveOutboxEventExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSaveOutboxEvent.expectations = append(mmSaveOutboxEvent.expectations, expectation)
	return expectation
}

// Then sets up ShopOutbox.SaveOutboxEvent return parameters for the expectation previously defined by the When method
func (e *ShopOutboxMockSaveOutboxEventExpectation) Then(err error) *ShopOutboxMock {
	e.results = &ShopOutboxMockSaveOutboxEventResults{err}
	return e.mock
}

// Times sets number of times ShopOutbox.SaveOutboxEvent should be invoked
func (mmSaveOutboxEvent *mShopOutboxMockSaveOutboxEvent) Times(n uint64) *mShopOutboxMockSaveOutboxEvent {
	if n == 0 {
		mmSaveOutboxEvent.mock.t.Fatalf("Times of ShopOutboxMock.SaveOutboxEvent mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSaveOutboxEvent.expectedInvocations, n)
	mmSaveOutboxEvent.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSaveOutboxEvent
}

func (mmSaveOutboxEvent *mShopOutboxMockSaveOutboxEvent) invocationsDone() bool {
	if len(mmSaveOutboxEvent.expectations) == 0 && mmSaveOutboxEvent.defaultExpectation == nil && mmSaveOutboxEvent.mock.funcSaveOutboxEvent == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSaveOutboxEvent.mock.afterSaveOutboxEventCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSaveOutboxEvent.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SaveOutboxEvent implements mm_service.ShopOutbox
func (mmSaveOutboxEvent *ShopOutboxMock) SaveOutboxEvent(ctx context.Context, eventType string, payload any) (err error) {
	mm_atomic.AddUint64(&mmSaveOutboxEvent.beforeSaveOutboxEventCounter, 1)
	defer mm_atomic.AddUint64(&mmSaveOutboxEvent.afterSaveOutboxEventCounter, 1)

	mmSaveOutboxEvent.t.Helper()

	if mmSaveOutboxEvent.inspectFuncSaveOutboxEvent != nil {
		mmSaveOutboxEvent.inspectFuncSaveOutboxEvent(ctx, eventType, payload)
	}

	mm_params := ShopOutboxMockSaveOutboxEventParams{ctx, eventType, payload}

	// Record call args
	mmSaveOutboxEvent.SaveOutboxEventMock.mutex.Lock()
	mmSaveOutboxEvent.SaveOutboxEventMock.callArgs = append(mmSaveOutboxEvent.SaveOutboxEventMock.callArgs, &mm_params)
	mmSaveOutboxEvent.SaveOutboxEventMock.mutex.Unlock()

	for _, e := range mmSaveOutboxEvent.SaveOutboxEventMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSaveOutboxEvent.SaveOutboxEventMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSaveOutboxEvent.SaveOutboxEventMock.defaultExpectation.Counter, 1)
		mm_want := mmSaveOutboxEvent.SaveOutboxEventMock.defaultExpectation.params
		mm_want_ptrs := mmSaveOutboxEvent.SaveOutboxEventMock.defaultExpectation.paramPtrs

		mm_got := ShopOutboxMockSaveOutboxEventParams{ctx, eventType, payload}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSaveOutboxEvent.t.Errorf("ShopOutboxMock.SaveOutboxEvent got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveOutboxEvent.SaveOutboxEventMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.eventType != nil && !minimock.Equal(*mm_want_ptrs.eventType, mm_got.eventType) {
				mmSaveOutboxEvent.t.Errorf("ShopOutboxMock.SaveOutboxEvent got unexpected parameter eventType, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveOutboxEvent.SaveOutboxEventMock.defaultExpectation.expectationOrigins.originEventType, *mm_want_ptrs.eventType, mm_got.eventType, minimock.Diff(*mm_want_ptrs.eventType, mm_got.eventType))
			}

			if mm_want_ptrs.payload != nil && !minimock.Equal(*mm_want_ptrs.payload, mm_got.payload) {
				mmSaveOutboxEvent.t.Errorf("ShopOutboxMock.SaveOutboxEvent got unexpected parameter payload, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveOutboxEvent.SaveOutboxEventMock.defaultExpectation.expectationOrigins.originPayload, *mm_want_ptrs.payload, mm_got.payload, minimock.Diff(*mm_want_ptrs.payload, mm_got.payload))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSaveOutboxEvent.t.Errorf("ShopOutboxMock.SaveOutboxEvent got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSaveOutboxEvent.SaveOutboxEventMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSaveOutboxEvent.SaveOutboxEventMock.defaultExpectation.results
		if mm_results == nil {
			mmSaveOutboxEvent.t.Fatal("No results are set for the ShopOutboxMock.SaveOutboxEvent")
		}
		return (*mm_results).err
	}
	if mmSaveOutboxEvent.funcSaveOutboxEvent != nil {
		return mmSaveOutboxEvent.funcSaveOutboxEvent(ctx, eventType, payload)
	}
	mmSaveOutboxEvent.t.Fatalf("Unexpected call to ShopOutboxMock.SaveOutboxEvent. %v %v %v", ctx, eventType, payload)
	return
}

// SaveOutboxEventAfterCounter returns a count of finished ShopOutboxMock.SaveOutboxEvent invocations
func (mmSaveOutboxEvent *ShopOutboxMock) SaveOutboxEventAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveOutboxEvent.afterSaveOutboxEventCounter)
}

// SaveOutboxEventBeforeCounter returns a count of ShopOutboxMock.SaveOutboxEvent invocations
func (mmSaveOutboxEvent *ShopOutboxMock) SaveOutboxEventBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveOutboxEvent.beforeSaveOutboxEventCounter)
}

// Calls returns a list of arguments used in each call to ShopOutboxMock.SaveOutboxEvent.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSaveOutboxEvent *mShopOutboxMockSaveOutboxEvent) Calls() []*ShopOutboxMockSaveOutboxEventParams {
	mmSaveOutboxEvent.mutex.RLock()

	argCopy := make([]*ShopOutboxMockSaveOutboxEventParams, len(mmSaveOutboxEvent.callArgs))
	copy(argCopy, mmSaveOutboxEvent.callArgs)

	mmSaveOutboxEvent.mutex.RUnlock()

	return argCopy
}

// MinimockSaveOutboxEventDone returns true if the count of the SaveOutboxEvent invocations corresponds
// the number of defined expectations
func (m *ShopOutboxMock) MinimockSaveOutboxEventDone() bool {
	if m.SaveOutboxEventMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SaveOutboxEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SaveOutboxEventMock.invocationsDone()
}

// MinimockSaveOutboxEventInspect logs each unmet expectation
func (m *ShopOutboxMock) MinimockSaveOutboxEventInspect() {
	for _, e := range m.SaveOutboxEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ShopOutboxMock.SaveOutboxEvent at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSaveOutboxEventCounter := mm_atomic.LoadUint64(&m.afterSaveOutboxEventCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SaveOutboxEventMock.defaultExpectation != nil && afterSaveOutboxEventCounter < 1 {
		if m.SaveOutboxEventMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ShopOutboxMock.SaveOutboxEvent at\n%s", m.SaveOutboxEventMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ShopOutboxMock.SaveOutboxEvent at\n%s with params: %#v", m.SaveOutboxEventMock.defaultExpectation.expectationOrigins.origin, *m.SaveOutboxEventMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSaveOutboxEvent != nil && afterSaveOutboxEventCounter < 1 {
		m.t.Errorf("Expected call to ShopOutboxMock.SaveOutboxEvent at\n%s", m.funcSaveOutboxEventOrigin)
	}

	if !m.SaveOutboxEventMock.invocationsDone() && afterSaveOutboxEventCounter > 0 {
		m.t.Errorf("Expected %d calls to ShopOutboxMock.SaveOutboxEvent at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SaveOutboxEventMock.expectedInvocations), m.SaveOutboxEventMock.expectedInvocationsOrigin, afterSaveOutboxEventCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ShopOutboxMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSaveOutboxEventInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ShopOutboxMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ShopOutboxMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSaveOutboxEventDone()
}
